// Code generated by Thrift Compiler (0.26.0). DO NOT EDIT.

package edge

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"regexp"
	"strings"
	"time"

	thrift "github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO

// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

var L []int32
var L2 []int32
var M map[string]int32
var M2 map[string]int32
var S []int32
var S2 []int32

const STRING_FOR_ENUM = 0
const FROM_INT = 2

var ENUM_LIST []E
var ENUM_MAP map[E]E

const INT_AS_DOUBLE = 1

var OUTER *Outer

func init() {
	L = []int32{
		1,
		2,
	}
	L2 = []int32{}
	M = map[string]int32{
		"k": 1,
	}
	M2 = map[string]int32{}
	S = []int32{
		1,
	}
	S2 = []int32{}
	ENUM_LIST = []E{
		1,
		2,
		-3,
	}
	ENUM_MAP = map[E]E{
		1: 2,
		2: -3,
	}
	OUTER = &Outer{
		Inner: &Inner{
			E: 1,
			Es: []E{
				1,
				2,
			},
		},
		Inners: map[string]*Inner{
			"x": &Inner{
				E: -3,
			},
		},
		L: []int32{
			3,
		},
	}
}
