// Code generated by Thrift Compiler (0.26.0). DO NOT EDIT.

package edge

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"regexp"
	"strings"
	"time"

	thrift "github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO

// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

type E int64

const (
	E_A E = 1
	E_B E = 2
	E_C E = -3
	E_D E = -2
)

var knownEValues = []E{
	E_A,
	E_B,
	E_C,
	E_D,
}

func EValues() iter.Seq[E] {
	return func(yield func(E) bool) {
		for _, v := range knownEValues {
			if !yield(v) {
				return
			}
		}
	}
}
func (p E) String() string {
	switch p {
	case E_A:
		return "A"
	case E_B:
		return "B"
	case E_C:
		return "C"
	case E_D:
		return "D"
	}
	return fmt.Sprintf("E(%d)", p)
}

func EFromString(s string) (E, error) {
	switch s {
	case "A":
		return E_A, nil
	case "B":
		return E_B, nil
	case "C":
		return E_C, nil
	case "D":
		return E_D, nil
	}
	return E(0), fmt.Errorf("not a valid E string")
}

func (p E) IsDefined() bool {
	switch p {
	case E_A:
		return true
	case E_B:
		return true
	case E_C:
		return true
	case E_D:
		return true
	}
	return false
}

//go:fix inline
func EPtr(v E) *E { return new(v) }

func (p E) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *E) UnmarshalText(text []byte) error {
	q, err := EFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *E) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = E(v)
	return nil
}

func (p *E) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Z int64

const (
	Z_ZERO Z = 0
)

var knownZValues = []Z{
	Z_ZERO,
}

func ZValues() iter.Seq[Z] {
	return func(yield func(Z) bool) {
		for _, v := range knownZValues {
			if !yield(v) {
				return
			}
		}
	}
}
func (p Z) String() string {
	switch p {
	case Z_ZERO:
		return "ZERO"
	}
	return fmt.Sprintf("Z(%d)", p)
}

func ZFromString(s string) (Z, error) {
	switch s {
	case "ZERO":
		return Z_ZERO, nil
	}
	return Z(0), fmt.Errorf("not a valid Z string")
}

func (p Z) IsDefined() bool {
	switch p {
	case Z_ZERO:
		return true
	}
	return false
}

//go:fix inline
func ZPtr(v Z) *Z { return new(v) }

func (p Z) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *Z) UnmarshalText(text []byte) error {
	q, err := ZFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *Z) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = Z(v)
	return nil
}

func (p *Z) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Attributes:
//   - E
//   - Es
type Inner struct {
	E  E   `thrift:"e,1" db:"e" json:"e"`
	Es []E `thrift:"es,2" db:"es" json:"es"`
}

func NewInner() *Inner {
	return &Inner{}
}

func (p *Inner) GetE() E {
	return p.E
}

func (p *Inner) GetEs() []E {
	return p.Es
}

func (p *Inner) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Inner) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		temp := E(v)
		p.E = temp
	}
	return nil
}

func (p *Inner) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]E, 0, thrift.PreallocSize(size))
	p.Es = tSlice
	for i := 0; i < size; i++ {
		var _elem0 E
		if v, err := iprot.ReadI32(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			temp := E(v)
			_elem0 = temp
		}
		p.Es = append(p.Es, _elem0)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *Inner) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Inner"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Inner) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "e", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:e: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.E)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.e (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:e: ", p), err)
	}
	return err
}

func (p *Inner) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "es", thrift.LIST, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:es: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.I32, len(p.Es)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Es {
		if err := oprot.WriteI32(ctx, int32(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:es: ", p), err)
	}
	return err
}

func (p *Inner) Equals(other *Inner) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.E != other.E {
		return false
	}
	if len(p.Es) != len(other.Es) {
		return false
	}
	for i, _tgt := range p.Es {
		_src1 := other.Es[i]
		if _tgt != _src1 {
			return false
		}
	}
	return true
}

func (p *Inner) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Inner(%+v)", *p)
}

func (p *Inner) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*edge.Inner",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*Inner)(nil)

func (p *Inner) Validate() error {
	return nil
}

// Attributes:
//   - Inner
//   - Inners
//   - L
//   - E
type Outer struct {
	Inner  *Inner            `thrift:"inner,1" db:"inner" json:"inner"`
	Inners map[string]*Inner `thrift:"inners,2" db:"inners" json:"inners"`
	L      []int32           `thrift:"l,3" db:"l" json:"l"`
	E      E                 `thrift:"e,4" db:"e" json:"e"`
}

func NewOuter() *Outer {
	return &Outer{
		L: []int32{},
		E: 1,
	}
}

var Outer_Inner_DEFAULT *Inner

func (p *Outer) GetInner() *Inner {
	if !p.IsSetInner() {
		return Outer_Inner_DEFAULT
	}
	return p.Inner
}

func (p *Outer) GetInners() map[string]*Inner {
	return p.Inners
}

func (p *Outer) GetL() []int32 {
	return p.L
}

func (p *Outer) GetE() E {
	return p.E
}

func (p *Outer) IsSetInner() bool {
	return p.Inner != nil
}

func (p *Outer) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Outer) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Inner = &Inner{}
	if err := p.Inner.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Inner), err)
	}
	return nil
}

func (p *Outer) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]*Inner, thrift.PreallocSize(size))
	p.Inners = tMap
	for i := 0; i < size; i++ {
		var _key2 string
		if v, err := iprot.ReadString(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key2 = v
		}
		_val3 := &Inner{}
		if err := _val3.Read(ctx, iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _val3), err)
		}
		p.Inners[_key2] = _val3
	}
	if err := iprot.ReadMapEnd(ctx); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *Outer) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]int32, 0, thrift.PreallocSize(size))
	p.L = tSlice
	for i := 0; i < size; i++ {
		var _elem4 int32
		if v, err := iprot.ReadI32(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem4 = v
		}
		p.L = append(p.L, _elem4)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *Outer) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		temp := E(v)
		p.E = temp
	}
	return nil
}

func (p *Outer) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Outer"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Outer) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetInner() {
		if err := oprot.WriteFieldBegin(ctx, "inner", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:inner: ", p), err)
		}
		if err := p.Inner.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Inner), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:inner: ", p), err)
		}
	}
	return err
}

func (p *Outer) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "inners", thrift.MAP, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:inners: ", p), err)
	}
	if err := oprot.WriteMapBegin(ctx, thrift.STRING, thrift.STRUCT, len(p.Inners)); err != nil {
		return thrift.PrependError("error writing map begin: ", err)
	}
	for k, v := range p.Inners {
		if err := oprot.WriteString(ctx, string(k)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
		if err := v.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteMapEnd(ctx); err != nil {
		return thrift.PrependError("error writing map end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:inners: ", p), err)
	}
	return err
}

func (p *Outer) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "l", thrift.LIST, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:l: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.I32, len(p.L)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.L {
		if err := oprot.WriteI32(ctx, int32(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:l: ", p), err)
	}
	return err
}

func (p *Outer) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "e", thrift.I32, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:e: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.E)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.e (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:e: ", p), err)
	}
	return err
}

func (p *Outer) Equals(other *Outer) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.Inner.Equals(other.Inner) {
		return false
	}
	if len(p.Inners) != len(other.Inners) {
		return false
	}
	for k, _tgt := range p.Inners {
		_src5, ok := other.Inners[k]
		if !ok {
			return false
		}
		if !_tgt.Equals(_src5) {
			return false
		}
	}
	if len(p.L) != len(other.L) {
		return false
	}
	for i, _tgt := range p.L {
		_src6 := other.L[i]
		if _tgt != _src6 {
			return false
		}
	}
	if p.E != other.E {
		return false
	}
	return true
}

func (p *Outer) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Outer(%+v)", *p)
}

func (p *Outer) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*edge.Outer",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*Outer)(nil)

func (p *Outer) Validate() error {
	return nil
}

// Attributes:
//   - Code
type Err struct {
	Code int32 `thrift:"code,1" db:"code" json:"code"`
}

func NewErr() *Err {
	return &Err{}
}

func (p *Err) GetCode() int32 {
	return p.Code
}

func (p *Err) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Err) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Code = v
	}
	return nil
}

func (p *Err) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Err"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Err) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "code", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:code: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Code)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.code (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:code: ", p), err)
	}
	return err
}

func (p *Err) Equals(other *Err) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Code != other.Code {
		return false
	}
	return true
}

func (p *Err) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Err(%+v)", *p)
}

func (p *Err) Error() string {
	return p.String()
}

func (Err) TExceptionType() thrift.TExceptionType {
	return thrift.TExceptionTypeCompiled
}

var _ thrift.TException = (*Err)(nil)

func (p *Err) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*edge.Err",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*Err)(nil)

func (p *Err) Validate() error {
	return nil
}

// Attributes:
//   - E
//   - Es
//   - Em
//   - Ess
//   - Oe
type HoldsErr struct {
	E   *Err            `thrift:"e,1" db:"e" json:"e"`
	Es  []*Err          `thrift:"es,2" db:"es" json:"es"`
	Em  map[string]*Err `thrift:"em,3" db:"em" json:"em"`
	Ess []*Err          `thrift:"ess,4" db:"ess" json:"ess"`
	Oe  *Err            `thrift:"oe,5" db:"oe" json:"oe,omitempty"`
}

func NewHoldsErr() *HoldsErr {
	return &HoldsErr{}
}

var HoldsErr_E_DEFAULT *Err

func (p *HoldsErr) GetE() *Err {
	if !p.IsSetE() {
		return HoldsErr_E_DEFAULT
	}
	return p.E
}

func (p *HoldsErr) GetEs() []*Err {
	return p.Es
}

func (p *HoldsErr) GetEm() map[string]*Err {
	return p.Em
}

func (p *HoldsErr) GetEss() []*Err {
	return p.Ess
}

var HoldsErr_Oe_DEFAULT *Err

func (p *HoldsErr) GetOe() *Err {
	if !p.IsSetOe() {
		return HoldsErr_Oe_DEFAULT
	}
	return p.Oe
}

func (p *HoldsErr) IsSetE() bool {
	return p.E != nil
}

func (p *HoldsErr) IsSetOe() bool {
	return p.Oe != nil
}

func (p *HoldsErr) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.SET {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField5(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *HoldsErr) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.E = &Err{}
	if err := p.E.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.E), err)
	}
	return nil
}

func (p *HoldsErr) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*Err, 0, thrift.PreallocSize(size))
	p.Es = tSlice
	for i := 0; i < size; i++ {
		_elem7 := &Err{}
		if err := _elem7.Read(ctx, iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem7), err)
		}
		p.Es = append(p.Es, _elem7)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *HoldsErr) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]*Err, thrift.PreallocSize(size))
	p.Em = tMap
	for i := 0; i < size; i++ {
		var _key8 string
		if v, err := iprot.ReadString(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key8 = v
		}
		_val9 := &Err{}
		if err := _val9.Read(ctx, iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _val9), err)
		}
		p.Em[_key8] = _val9
	}
	if err := iprot.ReadMapEnd(ctx); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *HoldsErr) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadSetBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading set begin: ", err)
	}
	tSet := make([]*Err, 0, thrift.PreallocSize(size))
	p.Ess = tSet
	for i := 0; i < size; i++ {
		_elem10 := &Err{}
		if err := _elem10.Read(ctx, iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem10), err)
		}
		p.Ess = append(p.Ess, _elem10)
	}
	if err := iprot.ReadSetEnd(ctx); err != nil {
		return thrift.PrependError("error reading set end: ", err)
	}
	return nil
}

func (p *HoldsErr) ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
	p.Oe = &Err{}
	if err := p.Oe.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Oe), err)
	}
	return nil
}

func (p *HoldsErr) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "HoldsErr"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField5(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *HoldsErr) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetE() {
		if err := oprot.WriteFieldBegin(ctx, "e", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:e: ", p), err)
		}
		if err := p.E.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.E), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:e: ", p), err)
		}
	}
	return err
}

func (p *HoldsErr) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "es", thrift.LIST, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:es: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.STRUCT, len(p.Es)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Es {
		if err := v.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:es: ", p), err)
	}
	return err
}

func (p *HoldsErr) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "em", thrift.MAP, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:em: ", p), err)
	}
	if err := oprot.WriteMapBegin(ctx, thrift.STRING, thrift.STRUCT, len(p.Em)); err != nil {
		return thrift.PrependError("error writing map begin: ", err)
	}
	for k, v := range p.Em {
		if err := oprot.WriteString(ctx, string(k)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
		if err := v.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteMapEnd(ctx); err != nil {
		return thrift.PrependError("error writing map end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:em: ", p), err)
	}
	return err
}

func (p *HoldsErr) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "ess", thrift.SET, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:ess: ", p), err)
	}
	if err := oprot.WriteSetBegin(ctx, thrift.STRUCT, len(p.Ess)); err != nil {
		return thrift.PrependError("error writing set begin: ", err)
	}
	for i := 0; i < len(p.Ess); i++ {
		for j := i + 1; j < len(p.Ess); j++ {
			if func(tgt, src *Err) bool {
				if !tgt.Equals(src) {
					return false
				}
				return true
			}(p.Ess[i], p.Ess[j]) {
				return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("%T error writing set field %q: slice is not unique", p.Ess, "p.Ess"))
			}
		}
	}
	for _, v := range p.Ess {
		if err := v.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteSetEnd(ctx); err != nil {
		return thrift.PrependError("error writing set end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:ess: ", p), err)
	}
	return err
}

func (p *HoldsErr) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetOe() {
		if err := oprot.WriteFieldBegin(ctx, "oe", thrift.STRUCT, 5); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:oe: ", p), err)
		}
		if err := p.Oe.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Oe), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 5:oe: ", p), err)
		}
	}
	return err
}

func (p *HoldsErr) Equals(other *HoldsErr) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.E.Equals(other.E) {
		return false
	}
	if len(p.Es) != len(other.Es) {
		return false
	}
	for i, _tgt := range p.Es {
		_src11 := other.Es[i]
		if !_tgt.Equals(_src11) {
			return false
		}
	}
	if len(p.Em) != len(other.Em) {
		return false
	}
	for k, _tgt := range p.Em {
		_src12, ok := other.Em[k]
		if !ok {
			return false
		}
		if !_tgt.Equals(_src12) {
			return false
		}
	}
	if len(p.Ess) != len(other.Ess) {
		return false
	}
	if !thrift.UnorderedEqual(p.Ess, other.Ess, func(_tgt, _src *Err) bool {
		if !_tgt.Equals(_src) {
			return false
		}
		return true
	}) {
		return false
	}
	if !p.Oe.Equals(other.Oe) {
		return false
	}
	return true
}

func (p *HoldsErr) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HoldsErr(%+v)", *p)
}

func (p *HoldsErr) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*edge.HoldsErr",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*HoldsErr)(nil)

func (p *HoldsErr) Validate() error {
	return nil
}

type ErrService interface {
	// Parameters:
	//   - E
	Echo(ctx context.Context, e *Err) (_r *Err, _err error)
}

type ErrServiceClient struct {
	c    thrift.TClient
	meta thrift.ResponseMeta
}

func NewErrServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ErrServiceClient {
	return &ErrServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewErrServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ErrServiceClient {
	return &ErrServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewErrServiceClient(c thrift.TClient) *ErrServiceClient {
	return &ErrServiceClient{
		c: c,
	}
}

func (p *ErrServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *ErrServiceClient) LastResponseMeta_() thrift.ResponseMeta {
	return p.meta
}

func (p *ErrServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
	p.meta = meta
}

// Parameters:
//   - E
func (p *ErrServiceClient) Echo(ctx context.Context, e *Err) (_r *Err, _err error) {
	var _args13 ErrServiceEchoArgs
	_args13.E = e
	var _result15 ErrServiceEchoResult
	var _meta14 thrift.ResponseMeta
	_meta14, _err = p.Client_().Call(ctx, "echo", &_args13, &_result15)
	p.SetLastResponseMeta_(_meta14)
	if _err != nil {
		return
	}
	switch {
	case _result15.Err != nil:
		return _r, _result15.Err
	}

	return _result15.GetSuccess(), nil
}

type ErrServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      ErrService
}

func (p *ErrServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *ErrServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *ErrServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewErrServiceProcessor(handler ErrService) *ErrServiceProcessor {

	self16 := &ErrServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self16.processorMap["echo"] = &errServiceProcessorEcho{handler: handler}
	return self16
}

func (p *ErrServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
	if err2 != nil {
		return false, thrift.WrapTException(err2)
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(ctx, thrift.STRUCT)
	iprot.ReadMessageEnd(ctx)
	x17 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
	x17.Write(ctx, oprot)
	oprot.WriteMessageEnd(ctx)
	oprot.Flush(ctx)
	return false, x17
}

type errServiceProcessorEcho struct {
	handler ErrService
}

func (p *errServiceProcessorEcho) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err18 thrift.TException
	args := ErrServiceEchoArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "echo", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := ErrServiceEchoResult{}
	if retval, err2 := p.handler.Echo(ctx, args.E); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		switch v := err2.(type) {
		case *Err:
			result.Err = v
		default:
			if errors.Is(err2, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err2),
					EndpointError: err,
				}
			}
			if errors.Is(err2, context.Canceled) {
				if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
					return false, &thrift.ProcessorError{
						WriteError:    thrift.WrapTException(err3),
						EndpointError: err,
					}
				}
			}
			_exc19 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing echo: "+err2.Error())
			if err2 := oprot.WriteMessageBegin(ctx, "echo", thrift.EXCEPTION, seqId); err2 != nil {
				_write_err18 = thrift.WrapTException(err2)
			}
			if err2 := _exc19.Write(ctx, oprot); _write_err18 == nil && err2 != nil {
				_write_err18 = thrift.WrapTException(err2)
			}
			if err2 := oprot.WriteMessageEnd(ctx); _write_err18 == nil && err2 != nil {
				_write_err18 = thrift.WrapTException(err2)
			}
			if err2 := oprot.Flush(ctx); _write_err18 == nil && err2 != nil {
				_write_err18 = thrift.WrapTException(err2)
			}
			if _write_err18 != nil {
				return false, &thrift.ProcessorError{
					WriteError:    _write_err18,
					EndpointError: err,
				}
			}
			return true, err
		}
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "echo", thrift.REPLY, seqId); err2 != nil {
		_write_err18 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err18 == nil && err2 != nil {
		_write_err18 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err18 == nil && err2 != nil {
		_write_err18 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err18 == nil && err2 != nil {
		_write_err18 = thrift.WrapTException(err2)
	}
	if _write_err18 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err18,
			EndpointError: err,
		}
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//   - E
type ErrServiceEchoArgs struct {
	E *Err `thrift:"e,1" db:"e" json:"e"`
}

func NewErrServiceEchoArgs() *ErrServiceEchoArgs {
	return &ErrServiceEchoArgs{}
}

var ErrServiceEchoArgs_E_DEFAULT *Err

func (p *ErrServiceEchoArgs) GetE() *Err {
	if !p.IsSetE() {
		return ErrServiceEchoArgs_E_DEFAULT
	}
	return p.E
}

func (p *ErrServiceEchoArgs) IsSetE() bool {
	return p.E != nil
}

func (p *ErrServiceEchoArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ErrServiceEchoArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.E = &Err{}
	if err := p.E.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.E), err)
	}
	return nil
}

func (p *ErrServiceEchoArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "echo_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ErrServiceEchoArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetE() {
		if err := oprot.WriteFieldBegin(ctx, "e", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:e: ", p), err)
		}
		if err := p.E.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.E), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:e: ", p), err)
		}
	}
	return err
}

func (p *ErrServiceEchoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ErrServiceEchoArgs(%+v)", *p)
}

func (p *ErrServiceEchoArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*edge.ErrServiceEchoArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ErrServiceEchoArgs)(nil)

// Attributes:
//   - Success
//   - Err
type ErrServiceEchoResult struct {
	Success *Err `thrift:"success,0" db:"success" json:"success,omitempty"`
	Err     *Err `thrift:"err,1" db:"err" json:"err,omitempty"`
}

func NewErrServiceEchoResult() *ErrServiceEchoResult {
	return &ErrServiceEchoResult{}
}

var ErrServiceEchoResult_Success_DEFAULT *Err

func (p *ErrServiceEchoResult) GetSuccess() *Err {
	if !p.IsSetSuccess() {
		return ErrServiceEchoResult_Success_DEFAULT
	}
	return p.Success
}

var ErrServiceEchoResult_Err_DEFAULT *Err

func (p *ErrServiceEchoResult) GetErr() *Err {
	if !p.IsSetErr() {
		return ErrServiceEchoResult_Err_DEFAULT
	}
	return p.Err
}

func (p *ErrServiceEchoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ErrServiceEchoResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *ErrServiceEchoResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ErrServiceEchoResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &Err{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *ErrServiceEchoResult) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Err = &Err{}
	if err := p.Err.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Err), err)
	}
	return nil
}

func (p *ErrServiceEchoResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "echo_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ErrServiceEchoResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *ErrServiceEchoResult) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetErr() {
		if err := oprot.WriteFieldBegin(ctx, "err", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:err: ", p), err)
		}
		if err := p.Err.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Err), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:err: ", p), err)
		}
	}
	return err
}

func (p *ErrServiceEchoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ErrServiceEchoResult(%+v)", *p)
}

func (p *ErrServiceEchoResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*edge.ErrServiceEchoResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ErrServiceEchoResult)(nil)
