/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package php

import (
	"strconv"
	"strings"

	"github.com/apache/thrift/compiler/go/generate/internal/emit"
	"github.com/apache/thrift/compiler/go/internal/version"
	"github.com/apache/thrift/compiler/go/sema"
)

// Generator is t_php_generator.
type Generator struct {
	program     *sema.Program
	opts        Options
	serviceName string
	indentLevel int
	tmpCounter  int

	packageDir string // package_dir_

	// fTypes is f_types_: the shared Types.php builder used only when
	// opts.Classmap is set. It is opened in initGenerator and written
	// once in closeGenerator.
	fTypes     strings.Builder
	fTypesName string

	// fService is f_service_: the shared per-service builder used only
	// when opts.Classmap is set. It is opened fresh in generateService
	// and written once at the end of generateService.
	fService     strings.Builder
	fServiceName string
}

// New is the t_php_generator constructor.
func New(program *sema.Program, opts Options) *Generator {
	return &Generator{program: program, opts: opts}
}

// Generate is t_generator::generate_program.
func (g *Generator) Generate() (err error) {
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(*emit.Error); ok {
				err = e
				return
			}
			if e, ok := r.(*sema.Error); ok {
				err = e
				return
			}
			panic(r)
		}
	}()
	g.initGenerator()
	for _, e := range g.program.Enums() {
		g.generateEnum(e)
	}
	for _, t := range g.program.Typedefs() {
		g.generateTypedef(t)
	}
	for _, s := range g.program.Objects() {
		if s.IsXception() {
			g.generateXception(s)
		} else {
			g.generateStruct(s)
		}
	}
	g.generateConsts(g.program.Consts())
	for _, s := range g.program.Services() {
		g.serviceName = s.Name()
		g.generateService(s)
	}
	g.closeGenerator()
	return nil
}

// ---- t_generator and t_oop_generator helpers ----

func (g *Generator) indentUp()   { g.indentLevel++ }
func (g *Generator) indentDown() { g.indentLevel-- }

// indent is indent(): t_php_generator overrides indent_str() to four
// spaces (the base t_generator default is two).
func (g *Generator) indent() string {
	return strings.Repeat("    ", g.indentLevel)
}

func (g *Generator) scopeUp(out *strings.Builder) {
	out.WriteString(g.indent() + "{\n")
	g.indentUp()
}

func (g *Generator) scopeDown(out *strings.Builder) {
	g.indentDown()
	out.WriteString(g.indent() + "}\n")
}

func (g *Generator) tmp(name string) string {
	s := name + strconv.Itoa(g.tmpCounter)
	g.tmpCounter++
	return s
}

func (g *Generator) outDir() string {
	if g.program.IsOutPathAbsolute() {
		return g.program.OutPath() + "/"
	}
	return g.program.OutPath() + g.opts.OutDirBase() + "/"
}

func autogenSummary() string {
	return "Autogenerated by Thrift Compiler (" + version.Version + ")"
}

func autogenComment() string {
	return "/**\n" + " * " + autogenSummary() + "\n" + " *\n" +
		" * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n" +
		" *  @generated\n" + " */\n"
}

// phpAutogenComment is php_autogen_comment: it splices "phpcs:disable"
// lines into the closing of the standard autogen comment for the file
// shapes that contain the identifiers those sniffs would flag.
func phpAutogenComment(phpcsDisables []string) string {
	s := autogenComment()
	if len(phpcsDisables) == 0 {
		return s
	}
	closer := strings.LastIndex(s, " */")
	block := " *\n"
	for _, rule := range phpcsDisables {
		block += " * phpcs:disable " + rule + "\n"
	}
	return s[:closer] + block + s[closer:]
}

// Cross-Thrift naming conventions whose violations must be silenced per
// file shape. Hoisted to one place so a future rename or addition is a
// one-line edit.
var phpcsDisablesClassmap = []string{
	"PSR1.Classes.ClassDeclaration.MultipleClasses",
	"PSR1.Methods.CamelCapsMethodName",
	"Squiz.Classes.ValidClassName",
}

var phpcsDisablesSnakeCaseMethods = []string{
	"PSR1.Methods.CamelCapsMethodName",
}

var phpcsDisablesServiceHelpers = []string{
	"Squiz.Classes.ValidClassName",
}

func itoa(i int64) string { return strconv.FormatInt(i, 10) }

// formatDouble mimics `ostream << double` with the default precision of
// six significant digits.
func formatDouble(f float64) string {
	return strconv.FormatFloat(f, 'g', 6, 64)
}

// phpEscapeString is t_php_generator's escape_string: the base
// t_generator table plus '$' -> "\\$", set in the constructor.
func phpEscapeString(in string) string {
	var sb strings.Builder
	for i := 0; i < len(in); i++ {
		switch c := in[i]; c {
		case '\n':
			sb.WriteString(`\n`)
		case '\r':
			sb.WriteString(`\r`)
		case '\t':
			sb.WriteString(`\t`)
		case '"':
			sb.WriteString(`\"`)
		case '\\':
			sb.WriteString(`\\`)
		case '$':
			sb.WriteString(`\$`)
		default:
			sb.WriteByte(c)
		}
	}
	return sb.String()
}

func getEscapedString(v *sema.ConstValue) string { return phpEscapeString(v.String()) }

// ---- naming helpers (classify, split, capitalize) ----

// classify transforms class_method into ClassMethod.
func classify(s string) string {
	var out strings.Builder
	for _, part := range strings.Split(s, "_") {
		out.WriteString(capitalize(part))
	}
	return out.String()
}

// capitalize upper-cases the first byte of s, as t_generator::capitalize
// and t_php_generator's private duplicate both do.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	b := []byte(s)
	b[0] = toUpper(b[0])
	return string(b)
}

func toUpper(c byte) byte {
	if c >= 'a' && c <= 'z' {
		return c - 'a' + 'A'
	}
	return c
}

// getCapName is get_cap_name: the first-letter-capitalized field name.
func getCapName(name string) string {
	if name == "" {
		return name
	}
	b := []byte(name)
	b[0] = toUpper(b[0])
	return string(b)
}

// ---- namespace helpers ----

// nsglobal is the NSGLOBAL macro: nsglobal_.size() ? nsglobal_ : "",
// which is simply nsglobal_ either way.
func (g *Generator) nsglobal() string { return g.opts.NSGlobal }

func (g *Generator) nsglobalA() string  { return "\\" + g.nsglobal() }
func (g *Generator) nsglobalB() string  { return g.nsglobal() + "\\" }
func (g *Generator) nsglobalAB() string { return "\\" + g.nsglobal() + "\\" }

// phpNamespaceBase is php_namespace_base.
func phpNamespaceBase(p *sema.Program) string {
	return strings.ReplaceAll(p.Namespace("php"), ".", `\`)
}

// phpNamespace is php_namespace: general use namespace prefixing,
// \my\namespace\ or my_namespace_.
func (g *Generator) phpNamespace(p *sema.Program) string {
	ns := phpNamespaceBase(p)
	prefix := g.nsglobalB()
	if g.nsglobal() != "" {
		prefix = g.nsglobalAB()
	}
	if ns != "" {
		return prefix + ns + "\\"
	}
	return prefix
}

// phpNamespaceSuffix is php_namespace_suffix: the namespace of a file,
// global\ns\sub\ns or global\ns or sub\ns.
func (g *Generator) phpNamespaceSuffix(p *sema.Program) string {
	ns := phpNamespaceBase(p)
	sep := ""
	if ns != "" && g.nsglobal() != "" {
		sep = "\\"
	}
	return g.nsglobal() + sep + ns
}

// phpNamespaceDirectory adds a directory to an already existing
// namespace. It is declared but never called in t_php_generator.cc.
func phpNamespaceDirectory(directory string, end bool) string {
	_ = directory
	if end {
		return ";"
	}
	return ""
}

// phpNamespaceAutoload writes an autoload identifier into globals:
// my\namespace\ or my_namespace_. It is declared but never called in
// t_php_generator.cc.
func (g *Generator) phpNamespaceAutoload(p *sema.Program) string {
	ns := phpNamespaceBase(p)
	prefix := g.nsglobal()
	if g.nsglobal() != "" {
		prefix = g.nsglobalB()
	}
	if ns != "" {
		return prefix + ns + "\\"
	}
	return prefix
}

// phpNamespaceDeclaration declares a type: typename or
// my_namespace_typename.
func phpNamespaceDeclaration(t sema.Type) string { return t.Name() }

// phpPath is declared but never called in t_php_generator.cc.
func phpPath(p *sema.Program) string {
	ns := p.Namespace("php.path")
	if ns == "" {
		return p.Name()
	}
	return strings.ReplaceAll(ns, ".", "/") + "/"
}

// isValidNamespace is t_php_generator::is_valid_namespace.
func isValidNamespace(subNamespace string) bool {
	return subNamespace == "path"
}

// ---- init and close ----

// initGenerator is t_php_generator::init_generator.
func (g *Generator) initGenerator() {
	emit.Mkdir(g.outDir())

	// Create real directory namespaces.
	nsx := strings.Split(g.phpNamespaceSuffix(g.program), `\`)
	g.packageDir = g.outDir()
	if len(nsx) == 1 && nsx[0] == "" {
		nsx = nil
	}
	for _, seg := range nsx {
		g.packageDir = g.packageDir + seg + "/"
		emit.Mkdir(g.packageDir)
	}

	if g.opts.Classmap {
		g.fTypesName = g.packageDir + "Types.php"
		g.generateProgramHeader(&g.fTypes, phpcsDisablesClassmap)
	}
}

// closeGenerator is t_php_generator::close_generator.
func (g *Generator) closeGenerator() {
	if g.opts.Classmap {
		emit.WriteFile(g.fTypesName, g.fTypes.String())
	}
}

func (g *Generator) displayName() string { return "PHP" }

// phpIsScalar is php_is_scalar.
func phpIsScalar(t sema.Type) bool {
	t = sema.TrueType(t)
	return t.IsBaseType() || t.IsEnum()
}

// ---- doc comments ----

// phpDocstringComment is generate_php_docstring_comment: like the base
// generate_docstring_comment with prefix " * ", except an empty line
// prints " *" (no trailing space) rather than a bare " * ".
func (g *Generator) phpDocstringComment(out *strings.Builder, contents string) {
	out.WriteString(g.indent() + "/**\n")
	rest := contents
	for rest != "" {
		var line string
		nl := strings.IndexByte(rest, '\n')
		truncated := false
		switch {
		case nl >= 0 && nl < 1023:
			line, rest = rest[:nl], rest[nl+1:]
		case nl < 0 && len(rest) < 1024:
			line, rest = rest, ""
		default:
			line, rest = rest[:1023], ""
			truncated = true
		}
		eof := nl < 0
		if len(line) > 0 {
			out.WriteString(g.indent() + " * " + line + "\n")
		} else if !eof {
			out.WriteString(g.indent() + " *\n")
		}
		if truncated {
			break
		}
	}
	out.WriteString(g.indent() + " */\n")
}

type docHaver interface {
	HasDoc() bool
	Doc() string
}

// phpDoc is generate_php_doc(ostream&, t_doc*).
func (g *Generator) phpDoc(out *strings.Builder, d docHaver) {
	if d.HasDoc() {
		g.phpDocstringComment(out, d.Doc())
	}
}

// phpDocField is generate_php_doc(ostream&, t_field*).
func (g *Generator) phpDocField(out *strings.Builder, field *sema.Field) {
	t := sema.TrueType(field.Type())
	hasUserDoc := field.HasDoc()
	varAddsValue := t.IsContainer()
	if !hasUserDoc && !varAddsValue {
		return
	}
	var ss strings.Builder
	if hasUserDoc {
		ss.WriteString(field.Doc() + "\n")
	}
	if varAddsValue {
		ss.WriteString("@var " + g.typeToPHPDoc(t) + "\n")
	}
	g.phpDocstringComment(out, ss.String())
}

// phpDocFunction is generate_php_doc(ostream&, t_function*).
func (g *Generator) phpDocFunction(out *strings.Builder, f *sema.Function) {
	var ss strings.Builder
	if f.HasDoc() {
		ss.WriteString(f.Doc() + "\n")
	}
	for _, arg := range f.Arglist().Members() {
		ss.WriteString("@param " + g.typeToPHPDoc(arg.Type()) + " $" + arg.Name())
		if arg.HasDoc() {
			ss.WriteString(" " + arg.Doc())
		}
		ss.WriteString("\n")
	}
	retType := f.ReturnType()
	if !retType.IsVoid() || retType.HasDoc() {
		ss.WriteString("@return " + g.typeToPHPDoc(retType))
		if retType.HasDoc() {
			ss.WriteString(" " + retType.Doc())
		}
		ss.WriteString("\n")
	}
	for _, exc := range f.Xceptions().Members() {
		ss.WriteString("@throws " + g.typeToPHPDoc(exc.Type()))
		if exc.HasDoc() {
			ss.WriteString(" " + exc.Doc())
		}
		ss.WriteString("\n")
	}
	g.phpDocstringComment(out, ss.String())
}

// ---- file headers ----

// phpIncludes is php_includes: prints standard php includes.
func (g *Generator) phpIncludes() string {
	includes := "use Thrift\\Base\\TBase;\n" +
		"use Thrift\\Type\\TType;\n" +
		"use Thrift\\Type\\TMessageType;\n" +
		"use Thrift\\Exception\\TException;\n" +
		"use Thrift\\Exception\\TProtocolException;\n" +
		"use Thrift\\Protocol\\TProtocol;\n" +
		"use Thrift\\Protocol\\TBinaryProtocol;\n" +
		"use Thrift\\Protocol\\TBinaryProtocolAccelerated;\n" +
		"use Thrift\\Exception\\TApplicationException;\n"

	if g.opts.Inlined {
		includes += "use Thrift\\Transport\\TTransport;\n"
	}
	if g.opts.JSON {
		includes += "use JsonSerializable;\n" +
			"use stdClass;\n"
	}
	return includes
}

// emitFileHeader is emit_file_header: the standard <?php + autogen
// docblock + namespace + use block at the top of a generated file.
func (g *Generator) emitFileHeader(program *sema.Program, file *strings.Builder, phpcsDisables []string) {
	file.WriteString("<?php" + "\n" + "\n")
	file.WriteString(phpAutogenComment(phpcsDisables) + "\n")
	file.WriteString("declare(strict_types=1);" + "\n" + "\n")
	if g.phpNamespaceSuffix(program) != "" {
		file.WriteString("namespace " + g.phpNamespaceSuffix(program) + ";" + "\n" + "\n")
	}
	file.WriteString(g.phpIncludes() + "\n")
}

func (g *Generator) generateServiceHeader(s *sema.Service, file *strings.Builder, phpcsDisables []string) {
	g.emitFileHeader(s.Program(), file, phpcsDisables)
}

func (g *Generator) generateProgramHeader(file *strings.Builder, phpcsDisables []string) {
	g.emitFileHeader(g.program, file, phpcsDisables)
}

// ---- type conversions ----

// declareField is declare_field: declares a field, optionally with
// initialization.
func (g *Generator) declareField(field *sema.Field, initv, obj bool) string {
	result := "$" + field.Name()
	if initv {
		t := sema.TrueType(field.Type())
		switch {
		case t.IsBaseType():
			switch t.(*sema.BaseType).Base() {
			case sema.TypeVoid:
			case sema.TypeString, sema.TypeUUID:
				result += " = ''"
			case sema.TypeBool:
				result += " = false"
			case sema.TypeI8, sema.TypeI16, sema.TypeI32, sema.TypeI64:
				result += " = 0"
			case sema.TypeDouble:
				result += " = 0.0"
			default:
				emit.Throw("compiler error: no PHP initializer for base type %s", sema.BaseName(t.(*sema.BaseType).Base()))
			}
		case t.IsEnum():
			result += " = 0"
		case t.IsContainer():
			result += " = []"
		case t.IsStruct() || t.IsXception():
			if obj {
				result += " = new " + g.phpNamespace(t.Program()) + t.Name() + "()"
			} else {
				result += " = null"
			}
		}
	}
	return result + ";"
}

// functionSignature renders a function signature of the form
// 'name(args): type'.
func (g *Generator) functionSignature(f *sema.Function, prefix string) string {
	return prefix + f.Name() + "(" + g.argumentList(f.Arglist(), true) + ")" + g.typeToReturn(f.ReturnType())
}

// argumentList renders a field list.
func (g *Generator) argumentList(s *sema.Struct, addTypeHints bool) string {
	var result strings.Builder
	first := true
	for _, field := range s.Members() {
		if first {
			first = false
		} else {
			result.WriteString(", ")
		}
		if addTypeHints {
			// Thrift fields admit null at construction (?T); same
			// convention for service-method parameters keeps PHP
			// callers BC-compatible while still narrowing accepted
			// types under strict_types.
			result.WriteString("?" + g.typeToNative(field.Type()) + " ")
		}
		result.WriteString("$" + field.Name())
	}
	return result.String()
}

// typeToReturn renders a PHP return-type clause for the given Thrift
// type, e.g. ": void" for void returns or ": ?T" for value returns
// (nullable to allow the exception-result idiom).
func (g *Generator) typeToReturn(t sema.Type) string {
	if t.IsVoid() {
		return ": void"
	}
	return ": ?" + g.typeToNative(t)
}

// typeToCast gets a typecast string for a particular type.
func typeToCast(t sema.Type) string {
	switch {
	case t.IsBaseType():
		switch t.(*sema.BaseType).Base() {
		case sema.TypeBool:
			return "(bool)"
		case sema.TypeI8, sema.TypeI16, sema.TypeI32, sema.TypeI64:
			return "(int)"
		case sema.TypeDouble:
			return "(float)"
		case sema.TypeString:
			return "(string)"
		case sema.TypeUUID:
			return "(string)"
		default:
			return ""
		}
	case t.IsEnum():
		return "(int)"
	}
	return ""
}

// typeToEnum converts the parse type to a TType constant.
func typeToEnum(t sema.Type) string {
	t = sema.TrueType(t)
	switch {
	case t.IsBaseType():
		switch t.(*sema.BaseType).Base() {
		case sema.TypeVoid:
			emit.Throw("NO T_VOID CONSTRUCT")
		case sema.TypeString:
			return "TType::STRING"
		case sema.TypeBool:
			return "TType::BOOL"
		case sema.TypeI8:
			return "TType::BYTE"
		case sema.TypeI16:
			return "TType::I16"
		case sema.TypeI32:
			return "TType::I32"
		case sema.TypeI64:
			return "TType::I64"
		case sema.TypeDouble:
			return "TType::DOUBLE"
		case sema.TypeUUID:
			return "TType::UUID"
		default:
			emit.Throw("compiler error: unhandled type")
		}
	case t.IsEnum():
		return "TType::I32"
	case t.IsStruct() || t.IsXception():
		return "TType::STRUCT"
	case t.IsMap():
		return "TType::MAP"
	case t.IsSet():
		return "TType::SET"
	case t.IsList():
		return "TType::LST"
	}
	emit.Throw("INVALID TYPE IN type_to_enum: %s", t.Name())
	return ""
}

// typeToPHPDoc converts the parse type to a PHPDoc string for the given
// type.
func (g *Generator) typeToPHPDoc(t sema.Type) string {
	t = sema.TrueType(t)
	switch {
	case t.IsBaseType():
		switch t.(*sema.BaseType).Base() {
		case sema.TypeVoid:
			return "void"
		case sema.TypeString:
			return "string"
		case sema.TypeBool:
			return "bool"
		case sema.TypeI8, sema.TypeI16, sema.TypeI32, sema.TypeI64:
			return "int"
		case sema.TypeDouble:
			return "double"
		case sema.TypeUUID:
			return "string"
		default:
			emit.Throw("compiler error: unhandled type")
		}
	case t.IsEnum():
		return "int"
	case t.IsStruct() || t.IsXception():
		return g.phpNamespace(t.Program()) + t.Name()
	case t.IsMap():
		return "array"
	case t.IsSet():
		elem := t.(*sema.Set).ElemType()
		if elem.IsContainer() {
			return "(" + g.typeToPHPDoc(elem) + ")[]"
		}
		return g.typeToPHPDoc(elem) + "[]"
	case t.IsList():
		elem := t.(*sema.List).ElemType()
		if elem.IsContainer() {
			return "(" + g.typeToPHPDoc(elem) + ")[]"
		}
		return g.typeToPHPDoc(elem) + "[]"
	}
	emit.Throw("INVALID TYPE IN type_to_enum: %s", t.Name())
	return ""
}

// typeToNative renders a PHP native type declaration (without the
// leading "?") for the given Thrift type. Used for property and
// parameter type hints; callers add the nullable prefix since all
// Thrift fields default to null.
func (g *Generator) typeToNative(t sema.Type) string {
	t = sema.TrueType(t)
	switch {
	case t.IsBaseType():
		switch t.(*sema.BaseType).Base() {
		case sema.TypeString, sema.TypeUUID:
			return "string"
		case sema.TypeBool:
			return "bool"
		case sema.TypeI8, sema.TypeI16, sema.TypeI32, sema.TypeI64:
			return "int"
		case sema.TypeDouble:
			return "float"
		default:
			emit.Throw("compiler error: unhandled base type in type_to_native")
		}
	case t.IsEnum():
		return "int"
	case t.IsStruct() || t.IsXception():
		// Same-namespace references resolve via the file-level
		// "namespace ...;" declaration, so emit the short class name
		// and let PHP resolve it. Cross-namespace references fall
		// back to a fully-qualified name. phpNamespace already
		// includes the leading backslash.
		if t.Program() == g.program {
			return t.Name()
		}
		return g.phpNamespace(t.Program()) + t.Name()
	case t.IsContainer():
		return "array"
	}
	emit.Throw("INVALID TYPE IN type_to_native: %s", t.Name())
	return ""
}

// langKeywordsForValidation is t_php_generator::lang_keywords_for_validation.
// update_keywords_for_validation() feeds the result into keywords_ in the
// constructor; t_generator::validate_id then rejects any declared
// identifier that collides with one of these, from validate_input()
// (called by main.cc right before generate_program()). See
// validatePHPIdentifiers below.
func langKeywordsForValidation() map[string]bool {
	words := []string{
		"BEGIN", "END", "__CLASS__", "__DIR__", "__FILE__", "__FUNCTION__",
		"__LINE__", "__METHOD__", "__NAMESPACE__", "abstract", "alias", "and", "args", "as",
		"assert", "begin", "break", "case", "catch", "class", "clone", "continue", "declare",
		"def", "default", "del", "delete", "do", "dynamic", "elif", "else", "elseif", "elsif",
		"end", "enddeclare", "endfor", "endforeach", "endif", "endswitch", "endwhile", "ensure",
		"except", "exec", "finally", "float", "for", "foreach", "from", "function", "global",
		"goto", "if", "implements", "import", "in", "inline", "instanceof", "interface", "is",
		"lambda", "module", "native", "new", "next", "nil", "not", "or", "package", "pass",
		"public", "print", "private", "protected", "raise", "redo", "rescue", "retry", "register",
		"return", "self", "sizeof", "static", "super", "switch", "synchronized", "then", "this",
		"throw", "transient", "try", "undef", "unless", "unsigned", "until", "use", "var",
		"virtual", "volatile", "when", "while", "with", "xor", "yield",
	}
	m := make(map[string]bool, len(words))
	for _, w := range words {
		m[w] = true
	}
	return m
}

// phpKeywords is keywords_ as update_keywords_for_validation() sets it in
// the t_php_generator constructor.
var phpKeywords = langKeywordsForValidation()

// validatePHPIdentifiers is t_generator::validate_input restricted to a
// generator with lang_keywords_for_validation overridden: it walks the
// program the way t_generator::validate does (enums and their constants,
// typedefs, objects and their members, consts, services and their
// functions with each function's arglist and xceptions struct and their
// members) and fails on the first declared identifier that collides
// with a PHP keyword, exactly as validate_id does.
func validatePHPIdentifiers(p *sema.Program) error {
	check := func(name string) error {
		if phpKeywords[name] {
			return &emit.Error{Msg: "Cannot use reserved language keyword \"" + name + "\" with target language PHP"}
		}
		return nil
	}
	checkFields := func(fields []*sema.Field) error {
		for _, f := range fields {
			if err := check(f.Name()); err != nil {
				return err
			}
		}
		return nil
	}
	for _, e := range p.Enums() {
		if err := check(e.Name()); err != nil {
			return err
		}
		for _, v := range e.Constants() {
			if err := check(v.Name()); err != nil {
				return err
			}
		}
	}
	for _, t := range p.Typedefs() {
		if err := check(t.Name()); err != nil {
			return err
		}
	}
	for _, s := range p.Objects() {
		if err := check(s.Name()); err != nil {
			return err
		}
		if err := checkFields(s.Members()); err != nil {
			return err
		}
	}
	for _, c := range p.Consts() {
		if err := check(c.Name()); err != nil {
			return err
		}
	}
	for _, s := range p.Services() {
		if err := check(s.Name()); err != nil {
			return err
		}
		for _, f := range s.Functions() {
			if err := check(f.Name()); err != nil {
				return err
			}
			if err := check(f.Arglist().Name()); err != nil {
				return err
			}
			if err := checkFields(f.Arglist().Members()); err != nil {
				return err
			}
			if err := check(f.Xceptions().Name()); err != nil {
				return err
			}
			if err := checkFields(f.Xceptions().Members()); err != nil {
				return err
			}
		}
	}
	return nil
}
