// Code generated by Thrift Compiler (0.26.0). DO NOT EDIT.

package recursive

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"regexp"
	"strings"
	"time"

	thrift "github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO

// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

// Attributes:
//   - Children
//   - Item
type RecTree struct {
	Children []*RecTree `thrift:"children,1" db:"children" json:"children"`
	Item     int16      `thrift:"item,2" db:"item" json:"item"`
}

func NewRecTree() *RecTree {
	return &RecTree{}
}

func (p *RecTree) GetChildren() []*RecTree {
	return p.Children
}

func (p *RecTree) GetItem() int16 {
	return p.Item
}

func (p *RecTree) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I16 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *RecTree) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*RecTree, 0, thrift.PreallocSize(size))
	p.Children = tSlice
	for i := 0; i < size; i++ {
		_elem0 := &RecTree{}
		if err := _elem0.Read(ctx, iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem0), err)
		}
		p.Children = append(p.Children, _elem0)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *RecTree) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI16(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Item = v
	}
	return nil
}

func (p *RecTree) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "RecTree"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *RecTree) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "children", thrift.LIST, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:children: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.STRUCT, len(p.Children)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Children {
		if err := v.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:children: ", p), err)
	}
	return err
}

func (p *RecTree) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "item", thrift.I16, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:item: ", p), err)
	}
	if err := oprot.WriteI16(ctx, int16(p.Item)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.item (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:item: ", p), err)
	}
	return err
}

func (p *RecTree) Equals(other *RecTree) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if len(p.Children) != len(other.Children) {
		return false
	}
	for i, _tgt := range p.Children {
		_src1 := other.Children[i]
		if !_tgt.Equals(_src1) {
			return false
		}
	}
	if p.Item != other.Item {
		return false
	}
	return true
}

func (p *RecTree) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecTree(%+v)", *p)
}

func (p *RecTree) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.RecTree",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*RecTree)(nil)

func (p *RecTree) Validate() error {
	return nil
}

// Attributes:
//   - Nextitem
//   - Item
type RecList struct {
	Nextitem *RecList `thrift:"nextitem,1" db:"nextitem" json:"nextitem"`
	// unused field # 2
	Item int16 `thrift:"item,3" db:"item" json:"item"`
}

func NewRecList() *RecList {
	return &RecList{}
}

var RecList_Nextitem_DEFAULT *RecList

func (p *RecList) GetNextitem() *RecList {
	if !p.IsSetNextitem() {
		return RecList_Nextitem_DEFAULT
	}
	return p.Nextitem
}

func (p *RecList) GetItem() int16 {
	return p.Item
}

func (p *RecList) IsSetNextitem() bool {
	return p.Nextitem != nil
}

func (p *RecList) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.I16 {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *RecList) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Nextitem = &RecList{}
	if err := p.Nextitem.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Nextitem), err)
	}
	return nil
}

func (p *RecList) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI16(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Item = v
	}
	return nil
}

func (p *RecList) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "RecList"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *RecList) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetNextitem() {
		if err := oprot.WriteFieldBegin(ctx, "nextitem", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:nextitem: ", p), err)
		}
		if err := p.Nextitem.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Nextitem), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:nextitem: ", p), err)
		}
	}
	return err
}

func (p *RecList) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "item", thrift.I16, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:item: ", p), err)
	}
	if err := oprot.WriteI16(ctx, int16(p.Item)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.item (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:item: ", p), err)
	}
	return err
}

func (p *RecList) Equals(other *RecList) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.Nextitem.Equals(other.Nextitem) {
		return false
	}
	if p.Item != other.Item {
		return false
	}
	return true
}

func (p *RecList) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecList(%+v)", *p)
}

func (p *RecList) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.RecList",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*RecList)(nil)

func (p *RecList) Validate() error {
	return nil
}

// Attributes:
//   - Other
type CoRec struct {
	Other *CoRec2 `thrift:"other,1" db:"other" json:"other"`
}

func NewCoRec() *CoRec {
	return &CoRec{}
}

var CoRec_Other_DEFAULT *CoRec2

func (p *CoRec) GetOther() *CoRec2 {
	if !p.IsSetOther() {
		return CoRec_Other_DEFAULT
	}
	return p.Other
}

func (p *CoRec) IsSetOther() bool {
	return p.Other != nil
}

func (p *CoRec) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CoRec) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Other = &CoRec2{}
	if err := p.Other.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Other), err)
	}
	return nil
}

func (p *CoRec) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "CoRec"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CoRec) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetOther() {
		if err := oprot.WriteFieldBegin(ctx, "other", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:other: ", p), err)
		}
		if err := p.Other.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Other), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:other: ", p), err)
		}
	}
	return err
}

func (p *CoRec) Equals(other *CoRec) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.Other.Equals(other.Other) {
		return false
	}
	return true
}

func (p *CoRec) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CoRec(%+v)", *p)
}

func (p *CoRec) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.CoRec",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*CoRec)(nil)

func (p *CoRec) Validate() error {
	return nil
}

// Attributes:
//   - Other
type CoRec2 struct {
	Other *CoRec `thrift:"other,1" db:"other" json:"other"`
}

func NewCoRec2() *CoRec2 {
	return &CoRec2{}
}

var CoRec2_Other_DEFAULT *CoRec

func (p *CoRec2) GetOther() *CoRec {
	if !p.IsSetOther() {
		return CoRec2_Other_DEFAULT
	}
	return p.Other
}

func (p *CoRec2) IsSetOther() bool {
	return p.Other != nil
}

func (p *CoRec2) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CoRec2) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Other = &CoRec{}
	if err := p.Other.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Other), err)
	}
	return nil
}

func (p *CoRec2) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "CoRec2"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CoRec2) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetOther() {
		if err := oprot.WriteFieldBegin(ctx, "other", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:other: ", p), err)
		}
		if err := p.Other.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Other), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:other: ", p), err)
		}
	}
	return err
}

func (p *CoRec2) Equals(other *CoRec2) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.Other.Equals(other.Other) {
		return false
	}
	return true
}

func (p *CoRec2) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CoRec2(%+v)", *p)
}

func (p *CoRec2) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.CoRec2",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*CoRec2)(nil)

func (p *CoRec2) Validate() error {
	return nil
}

// Attributes:
//   - Other
type CoUnion struct {
	Other *CoUnion2 `thrift:"other,1" db:"other" json:"other,omitempty"`
}

func NewCoUnion() *CoUnion {
	return &CoUnion{}
}

var CoUnion_Other_DEFAULT *CoUnion2

func (p *CoUnion) GetOther() *CoUnion2 {
	if !p.IsSetOther() {
		return CoUnion_Other_DEFAULT
	}
	return p.Other
}

func (p *CoUnion) CountSetFieldsCoUnion() int {
	if p == nil {
		return 0
	}
	count := 0
	if p.IsSetOther() {
		count++
	}
	return count

}

func (p *CoUnion) IsSetOther() bool {
	return p.Other != nil
}

func (p *CoUnion) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CoUnion) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Other = &CoUnion2{}
	if err := p.Other.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Other), err)
	}
	return nil
}

func (p *CoUnion) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if c := p.CountSetFieldsCoUnion(); c != 1 {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("%T write union: exactly one field must be set (%d set)", p, c))
	}
	if err := oprot.WriteStructBegin(ctx, "CoUnion"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CoUnion) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetOther() {
		if err := oprot.WriteFieldBegin(ctx, "other", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:other: ", p), err)
		}
		if err := p.Other.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Other), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:other: ", p), err)
		}
	}
	return err
}

func (p *CoUnion) Equals(other *CoUnion) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.Other.Equals(other.Other) {
		return false
	}
	return true
}

func (p *CoUnion) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CoUnion(%+v)", *p)
}

func (p *CoUnion) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.CoUnion",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*CoUnion)(nil)

func (p *CoUnion) Validate() error {
	return nil
}

// Attributes:
//   - Other
type CoUnion2 struct {
	Other *CoUnion `thrift:"other,1" db:"other" json:"other,omitempty"`
}

func NewCoUnion2() *CoUnion2 {
	return &CoUnion2{}
}

var CoUnion2_Other_DEFAULT *CoUnion

func (p *CoUnion2) GetOther() *CoUnion {
	if !p.IsSetOther() {
		return CoUnion2_Other_DEFAULT
	}
	return p.Other
}

func (p *CoUnion2) CountSetFieldsCoUnion2() int {
	if p == nil {
		return 0
	}
	count := 0
	if p.IsSetOther() {
		count++
	}
	return count

}

func (p *CoUnion2) IsSetOther() bool {
	return p.Other != nil
}

func (p *CoUnion2) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CoUnion2) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Other = &CoUnion{}
	if err := p.Other.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Other), err)
	}
	return nil
}

func (p *CoUnion2) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if c := p.CountSetFieldsCoUnion2(); c != 1 {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("%T write union: exactly one field must be set (%d set)", p, c))
	}
	if err := oprot.WriteStructBegin(ctx, "CoUnion2"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CoUnion2) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetOther() {
		if err := oprot.WriteFieldBegin(ctx, "other", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:other: ", p), err)
		}
		if err := p.Other.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Other), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:other: ", p), err)
		}
	}
	return err
}

func (p *CoUnion2) Equals(other *CoUnion2) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.Other.Equals(other.Other) {
		return false
	}
	return true
}

func (p *CoUnion2) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CoUnion2(%+v)", *p)
}

func (p *CoUnion2) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.CoUnion2",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*CoUnion2)(nil)

func (p *CoUnion2) Validate() error {
	return nil
}

// Attributes:
//   - Other
type CoError struct {
	Other *CoError2 `thrift:"other,1" db:"other" json:"other"`
}

func NewCoError() *CoError {
	return &CoError{}
}

var CoError_Other_DEFAULT *CoError2

func (p *CoError) GetOther() *CoError2 {
	if !p.IsSetOther() {
		return CoError_Other_DEFAULT
	}
	return p.Other
}

func (p *CoError) IsSetOther() bool {
	return p.Other != nil
}

func (p *CoError) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CoError) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Other = &CoError2{}
	if err := p.Other.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Other), err)
	}
	return nil
}

func (p *CoError) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "CoError"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CoError) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetOther() {
		if err := oprot.WriteFieldBegin(ctx, "other", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:other: ", p), err)
		}
		if err := p.Other.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Other), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:other: ", p), err)
		}
	}
	return err
}

func (p *CoError) Equals(other *CoError) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.Other.Equals(other.Other) {
		return false
	}
	return true
}

func (p *CoError) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CoError(%+v)", *p)
}

func (p *CoError) Error() string {
	return p.String()
}

func (CoError) TExceptionType() thrift.TExceptionType {
	return thrift.TExceptionTypeCompiled
}

var _ thrift.TException = (*CoError)(nil)

func (p *CoError) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.CoError",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*CoError)(nil)

func (p *CoError) Validate() error {
	return nil
}

// Attributes:
//   - Other
type CoError2 struct {
	Other *CoError `thrift:"other,1" db:"other" json:"other"`
}

func NewCoError2() *CoError2 {
	return &CoError2{}
}

var CoError2_Other_DEFAULT *CoError

func (p *CoError2) GetOther() *CoError {
	if !p.IsSetOther() {
		return CoError2_Other_DEFAULT
	}
	return p.Other
}

func (p *CoError2) IsSetOther() bool {
	return p.Other != nil
}

func (p *CoError2) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CoError2) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Other = &CoError{}
	if err := p.Other.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Other), err)
	}
	return nil
}

func (p *CoError2) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "CoError2"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CoError2) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetOther() {
		if err := oprot.WriteFieldBegin(ctx, "other", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:other: ", p), err)
		}
		if err := p.Other.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Other), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:other: ", p), err)
		}
	}
	return err
}

func (p *CoError2) Equals(other *CoError2) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.Other.Equals(other.Other) {
		return false
	}
	return true
}

func (p *CoError2) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CoError2(%+v)", *p)
}

func (p *CoError2) Error() string {
	return p.String()
}

func (CoError2) TExceptionType() thrift.TExceptionType {
	return thrift.TExceptionTypeCompiled
}

var _ thrift.TException = (*CoError2)(nil)

func (p *CoError2) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.CoError2",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*CoError2)(nil)

func (p *CoError2) Validate() error {
	return nil
}

// Attributes:
//   - Lister
type VectorTest struct {
	Lister []*RecList `thrift:"lister,1" db:"lister" json:"lister"`
}

func NewVectorTest() *VectorTest {
	return &VectorTest{}
}

func (p *VectorTest) GetLister() []*RecList {
	return p.Lister
}

func (p *VectorTest) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *VectorTest) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*RecList, 0, thrift.PreallocSize(size))
	p.Lister = tSlice
	for i := 0; i < size; i++ {
		_elem2 := &RecList{}
		if err := _elem2.Read(ctx, iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem2), err)
		}
		p.Lister = append(p.Lister, _elem2)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *VectorTest) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "VectorTest"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *VectorTest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "lister", thrift.LIST, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:lister: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.STRUCT, len(p.Lister)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Lister {
		if err := v.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:lister: ", p), err)
	}
	return err
}

func (p *VectorTest) Equals(other *VectorTest) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if len(p.Lister) != len(other.Lister) {
		return false
	}
	for i, _tgt := range p.Lister {
		_src3 := other.Lister[i]
		if !_tgt.Equals(_src3) {
			return false
		}
	}
	return true
}

func (p *VectorTest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VectorTest(%+v)", *p)
}

func (p *VectorTest) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.VectorTest",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*VectorTest)(nil)

func (p *VectorTest) Validate() error {
	return nil
}

type TestService interface {
	// Parameters:
	//   - Tree
	EchoTree(ctx context.Context, tree *RecTree) (_r *RecTree, _err error)
	// Parameters:
	//   - Lst
	EchoList(ctx context.Context, lst *RecList) (_r *RecList, _err error)
	// Parameters:
	//   - Item
	EchoCoRec(ctx context.Context, item *CoRec) (_r *CoRec, _err error)
	// Parameters:
	//   - Item
	EchoCoUnion(ctx context.Context, item *CoUnion) (_r *CoUnion, _err error)
}

type TestServiceClient struct {
	c    thrift.TClient
	meta thrift.ResponseMeta
}

func NewTestServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *TestServiceClient {
	return &TestServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewTestServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *TestServiceClient {
	return &TestServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewTestServiceClient(c thrift.TClient) *TestServiceClient {
	return &TestServiceClient{
		c: c,
	}
}

func (p *TestServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *TestServiceClient) LastResponseMeta_() thrift.ResponseMeta {
	return p.meta
}

func (p *TestServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
	p.meta = meta
}

// Parameters:
//   - Tree
func (p *TestServiceClient) EchoTree(ctx context.Context, tree *RecTree) (_r *RecTree, _err error) {
	var _args4 TestServiceEchoTreeArgs
	_args4.Tree = tree
	var _result6 TestServiceEchoTreeResult
	var _meta5 thrift.ResponseMeta
	_meta5, _err = p.Client_().Call(ctx, "echoTree", &_args4, &_result6)
	p.SetLastResponseMeta_(_meta5)
	if _err != nil {
		return
	}
	if _ret7 := _result6.GetSuccess(); _ret7 != nil {
		return _ret7, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "echoTree failed: unknown result")
}

// Parameters:
//   - Lst
func (p *TestServiceClient) EchoList(ctx context.Context, lst *RecList) (_r *RecList, _err error) {
	var _args8 TestServiceEchoListArgs
	_args8.Lst = lst
	var _result10 TestServiceEchoListResult
	var _meta9 thrift.ResponseMeta
	_meta9, _err = p.Client_().Call(ctx, "echoList", &_args8, &_result10)
	p.SetLastResponseMeta_(_meta9)
	if _err != nil {
		return
	}
	if _ret11 := _result10.GetSuccess(); _ret11 != nil {
		return _ret11, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "echoList failed: unknown result")
}

// Parameters:
//   - Item
func (p *TestServiceClient) EchoCoRec(ctx context.Context, item *CoRec) (_r *CoRec, _err error) {
	var _args12 TestServiceEchoCoRecArgs
	_args12.Item = item
	var _result14 TestServiceEchoCoRecResult
	var _meta13 thrift.ResponseMeta
	_meta13, _err = p.Client_().Call(ctx, "echoCoRec", &_args12, &_result14)
	p.SetLastResponseMeta_(_meta13)
	if _err != nil {
		return
	}
	switch {
	case _result14.Err != nil:
		return _r, _result14.Err
	}

	if _ret15 := _result14.GetSuccess(); _ret15 != nil {
		return _ret15, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "echoCoRec failed: unknown result")
}

// Parameters:
//   - Item
func (p *TestServiceClient) EchoCoUnion(ctx context.Context, item *CoUnion) (_r *CoUnion, _err error) {
	var _args16 TestServiceEchoCoUnionArgs
	_args16.Item = item
	var _result18 TestServiceEchoCoUnionResult
	var _meta17 thrift.ResponseMeta
	_meta17, _err = p.Client_().Call(ctx, "echoCoUnion", &_args16, &_result18)
	p.SetLastResponseMeta_(_meta17)
	if _err != nil {
		return
	}
	switch {
	case _result18.Err != nil:
		return _r, _result18.Err
	}

	if _ret19 := _result18.GetSuccess(); _ret19 != nil {
		return _ret19, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "echoCoUnion failed: unknown result")
}

type TestServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      TestService
}

func (p *TestServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *TestServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *TestServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewTestServiceProcessor(handler TestService) *TestServiceProcessor {

	self20 := &TestServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self20.processorMap["echoTree"] = &testServiceProcessorEchoTree{handler: handler}
	self20.processorMap["echoList"] = &testServiceProcessorEchoList{handler: handler}
	self20.processorMap["echoCoRec"] = &testServiceProcessorEchoCoRec{handler: handler}
	self20.processorMap["echoCoUnion"] = &testServiceProcessorEchoCoUnion{handler: handler}
	return self20
}

func (p *TestServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
	if err2 != nil {
		return false, thrift.WrapTException(err2)
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(ctx, thrift.STRUCT)
	iprot.ReadMessageEnd(ctx)
	x21 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
	x21.Write(ctx, oprot)
	oprot.WriteMessageEnd(ctx)
	oprot.Flush(ctx)
	return false, x21
}

type testServiceProcessorEchoTree struct {
	handler TestService
}

func (p *testServiceProcessorEchoTree) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err22 thrift.TException
	args := TestServiceEchoTreeArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "echoTree", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := TestServiceEchoTreeResult{}
	if retval, err2 := p.handler.EchoTree(ctx, args.Tree); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc23 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing echoTree: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "echoTree", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err22 = thrift.WrapTException(err2)
		}
		if err2 := _exc23.Write(ctx, oprot); _write_err22 == nil && err2 != nil {
			_write_err22 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err22 == nil && err2 != nil {
			_write_err22 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err22 == nil && err2 != nil {
			_write_err22 = thrift.WrapTException(err2)
		}
		if _write_err22 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err22,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "echoTree", thrift.REPLY, seqId); err2 != nil {
		_write_err22 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err22 == nil && err2 != nil {
		_write_err22 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err22 == nil && err2 != nil {
		_write_err22 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err22 == nil && err2 != nil {
		_write_err22 = thrift.WrapTException(err2)
	}
	if _write_err22 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err22,
			EndpointError: err,
		}
	}
	return true, err
}

type testServiceProcessorEchoList struct {
	handler TestService
}

func (p *testServiceProcessorEchoList) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err24 thrift.TException
	args := TestServiceEchoListArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "echoList", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := TestServiceEchoListResult{}
	if retval, err2 := p.handler.EchoList(ctx, args.Lst); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc25 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing echoList: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "echoList", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err24 = thrift.WrapTException(err2)
		}
		if err2 := _exc25.Write(ctx, oprot); _write_err24 == nil && err2 != nil {
			_write_err24 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err24 == nil && err2 != nil {
			_write_err24 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err24 == nil && err2 != nil {
			_write_err24 = thrift.WrapTException(err2)
		}
		if _write_err24 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err24,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "echoList", thrift.REPLY, seqId); err2 != nil {
		_write_err24 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err24 == nil && err2 != nil {
		_write_err24 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err24 == nil && err2 != nil {
		_write_err24 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err24 == nil && err2 != nil {
		_write_err24 = thrift.WrapTException(err2)
	}
	if _write_err24 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err24,
			EndpointError: err,
		}
	}
	return true, err
}

type testServiceProcessorEchoCoRec struct {
	handler TestService
}

func (p *testServiceProcessorEchoCoRec) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err26 thrift.TException
	args := TestServiceEchoCoRecArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "echoCoRec", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := TestServiceEchoCoRecResult{}
	if retval, err2 := p.handler.EchoCoRec(ctx, args.Item); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		switch v := err2.(type) {
		case *CoError:
			result.Err = v
		default:
			if errors.Is(err2, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err2),
					EndpointError: err,
				}
			}
			if errors.Is(err2, context.Canceled) {
				if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
					return false, &thrift.ProcessorError{
						WriteError:    thrift.WrapTException(err3),
						EndpointError: err,
					}
				}
			}
			_exc27 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing echoCoRec: "+err2.Error())
			if err2 := oprot.WriteMessageBegin(ctx, "echoCoRec", thrift.EXCEPTION, seqId); err2 != nil {
				_write_err26 = thrift.WrapTException(err2)
			}
			if err2 := _exc27.Write(ctx, oprot); _write_err26 == nil && err2 != nil {
				_write_err26 = thrift.WrapTException(err2)
			}
			if err2 := oprot.WriteMessageEnd(ctx); _write_err26 == nil && err2 != nil {
				_write_err26 = thrift.WrapTException(err2)
			}
			if err2 := oprot.Flush(ctx); _write_err26 == nil && err2 != nil {
				_write_err26 = thrift.WrapTException(err2)
			}
			if _write_err26 != nil {
				return false, &thrift.ProcessorError{
					WriteError:    _write_err26,
					EndpointError: err,
				}
			}
			return true, err
		}
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "echoCoRec", thrift.REPLY, seqId); err2 != nil {
		_write_err26 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err26 == nil && err2 != nil {
		_write_err26 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err26 == nil && err2 != nil {
		_write_err26 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err26 == nil && err2 != nil {
		_write_err26 = thrift.WrapTException(err2)
	}
	if _write_err26 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err26,
			EndpointError: err,
		}
	}
	return true, err
}

type testServiceProcessorEchoCoUnion struct {
	handler TestService
}

func (p *testServiceProcessorEchoCoUnion) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err28 thrift.TException
	args := TestServiceEchoCoUnionArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "echoCoUnion", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := TestServiceEchoCoUnionResult{}
	if retval, err2 := p.handler.EchoCoUnion(ctx, args.Item); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		switch v := err2.(type) {
		case *CoError:
			result.Err = v
		default:
			if errors.Is(err2, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err2),
					EndpointError: err,
				}
			}
			if errors.Is(err2, context.Canceled) {
				if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
					return false, &thrift.ProcessorError{
						WriteError:    thrift.WrapTException(err3),
						EndpointError: err,
					}
				}
			}
			_exc29 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing echoCoUnion: "+err2.Error())
			if err2 := oprot.WriteMessageBegin(ctx, "echoCoUnion", thrift.EXCEPTION, seqId); err2 != nil {
				_write_err28 = thrift.WrapTException(err2)
			}
			if err2 := _exc29.Write(ctx, oprot); _write_err28 == nil && err2 != nil {
				_write_err28 = thrift.WrapTException(err2)
			}
			if err2 := oprot.WriteMessageEnd(ctx); _write_err28 == nil && err2 != nil {
				_write_err28 = thrift.WrapTException(err2)
			}
			if err2 := oprot.Flush(ctx); _write_err28 == nil && err2 != nil {
				_write_err28 = thrift.WrapTException(err2)
			}
			if _write_err28 != nil {
				return false, &thrift.ProcessorError{
					WriteError:    _write_err28,
					EndpointError: err,
				}
			}
			return true, err
		}
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "echoCoUnion", thrift.REPLY, seqId); err2 != nil {
		_write_err28 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err28 == nil && err2 != nil {
		_write_err28 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err28 == nil && err2 != nil {
		_write_err28 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err28 == nil && err2 != nil {
		_write_err28 = thrift.WrapTException(err2)
	}
	if _write_err28 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err28,
			EndpointError: err,
		}
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//   - Tree
type TestServiceEchoTreeArgs struct {
	Tree *RecTree `thrift:"tree,1" db:"tree" json:"tree"`
}

func NewTestServiceEchoTreeArgs() *TestServiceEchoTreeArgs {
	return &TestServiceEchoTreeArgs{}
}

var TestServiceEchoTreeArgs_Tree_DEFAULT *RecTree

func (p *TestServiceEchoTreeArgs) GetTree() *RecTree {
	if !p.IsSetTree() {
		return TestServiceEchoTreeArgs_Tree_DEFAULT
	}
	return p.Tree
}

func (p *TestServiceEchoTreeArgs) IsSetTree() bool {
	return p.Tree != nil
}

func (p *TestServiceEchoTreeArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TestServiceEchoTreeArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Tree = &RecTree{}
	if err := p.Tree.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Tree), err)
	}
	return nil
}

func (p *TestServiceEchoTreeArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "echoTree_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TestServiceEchoTreeArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetTree() {
		if err := oprot.WriteFieldBegin(ctx, "tree", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:tree: ", p), err)
		}
		if err := p.Tree.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Tree), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:tree: ", p), err)
		}
	}
	return err
}

func (p *TestServiceEchoTreeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestServiceEchoTreeArgs(%+v)", *p)
}

func (p *TestServiceEchoTreeArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.TestServiceEchoTreeArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TestServiceEchoTreeArgs)(nil)

// Attributes:
//   - Success
type TestServiceEchoTreeResult struct {
	Success *RecTree `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewTestServiceEchoTreeResult() *TestServiceEchoTreeResult {
	return &TestServiceEchoTreeResult{}
}

var TestServiceEchoTreeResult_Success_DEFAULT *RecTree

func (p *TestServiceEchoTreeResult) GetSuccess() *RecTree {
	if !p.IsSetSuccess() {
		return TestServiceEchoTreeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *TestServiceEchoTreeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestServiceEchoTreeResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TestServiceEchoTreeResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &RecTree{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *TestServiceEchoTreeResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "echoTree_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TestServiceEchoTreeResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *TestServiceEchoTreeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestServiceEchoTreeResult(%+v)", *p)
}

func (p *TestServiceEchoTreeResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.TestServiceEchoTreeResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TestServiceEchoTreeResult)(nil)

// Attributes:
//   - Lst
type TestServiceEchoListArgs struct {
	Lst *RecList `thrift:"lst,1" db:"lst" json:"lst"`
}

func NewTestServiceEchoListArgs() *TestServiceEchoListArgs {
	return &TestServiceEchoListArgs{}
}

var TestServiceEchoListArgs_Lst_DEFAULT *RecList

func (p *TestServiceEchoListArgs) GetLst() *RecList {
	if !p.IsSetLst() {
		return TestServiceEchoListArgs_Lst_DEFAULT
	}
	return p.Lst
}

func (p *TestServiceEchoListArgs) IsSetLst() bool {
	return p.Lst != nil
}

func (p *TestServiceEchoListArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TestServiceEchoListArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Lst = &RecList{}
	if err := p.Lst.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Lst), err)
	}
	return nil
}

func (p *TestServiceEchoListArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "echoList_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TestServiceEchoListArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetLst() {
		if err := oprot.WriteFieldBegin(ctx, "lst", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:lst: ", p), err)
		}
		if err := p.Lst.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Lst), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:lst: ", p), err)
		}
	}
	return err
}

func (p *TestServiceEchoListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestServiceEchoListArgs(%+v)", *p)
}

func (p *TestServiceEchoListArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.TestServiceEchoListArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TestServiceEchoListArgs)(nil)

// Attributes:
//   - Success
type TestServiceEchoListResult struct {
	Success *RecList `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewTestServiceEchoListResult() *TestServiceEchoListResult {
	return &TestServiceEchoListResult{}
}

var TestServiceEchoListResult_Success_DEFAULT *RecList

func (p *TestServiceEchoListResult) GetSuccess() *RecList {
	if !p.IsSetSuccess() {
		return TestServiceEchoListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *TestServiceEchoListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestServiceEchoListResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TestServiceEchoListResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &RecList{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *TestServiceEchoListResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "echoList_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TestServiceEchoListResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *TestServiceEchoListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestServiceEchoListResult(%+v)", *p)
}

func (p *TestServiceEchoListResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.TestServiceEchoListResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TestServiceEchoListResult)(nil)

// Attributes:
//   - Item
type TestServiceEchoCoRecArgs struct {
	Item *CoRec `thrift:"item,1" db:"item" json:"item"`
}

func NewTestServiceEchoCoRecArgs() *TestServiceEchoCoRecArgs {
	return &TestServiceEchoCoRecArgs{}
}

var TestServiceEchoCoRecArgs_Item_DEFAULT *CoRec

func (p *TestServiceEchoCoRecArgs) GetItem() *CoRec {
	if !p.IsSetItem() {
		return TestServiceEchoCoRecArgs_Item_DEFAULT
	}
	return p.Item
}

func (p *TestServiceEchoCoRecArgs) IsSetItem() bool {
	return p.Item != nil
}

func (p *TestServiceEchoCoRecArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TestServiceEchoCoRecArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Item = &CoRec{}
	if err := p.Item.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Item), err)
	}
	return nil
}

func (p *TestServiceEchoCoRecArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "echoCoRec_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TestServiceEchoCoRecArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetItem() {
		if err := oprot.WriteFieldBegin(ctx, "item", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:item: ", p), err)
		}
		if err := p.Item.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Item), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:item: ", p), err)
		}
	}
	return err
}

func (p *TestServiceEchoCoRecArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestServiceEchoCoRecArgs(%+v)", *p)
}

func (p *TestServiceEchoCoRecArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.TestServiceEchoCoRecArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TestServiceEchoCoRecArgs)(nil)

// Attributes:
//   - Success
//   - Err
type TestServiceEchoCoRecResult struct {
	Success *CoRec   `thrift:"success,0" db:"success" json:"success,omitempty"`
	Err     *CoError `thrift:"err,1" db:"err" json:"err,omitempty"`
}

func NewTestServiceEchoCoRecResult() *TestServiceEchoCoRecResult {
	return &TestServiceEchoCoRecResult{}
}

var TestServiceEchoCoRecResult_Success_DEFAULT *CoRec

func (p *TestServiceEchoCoRecResult) GetSuccess() *CoRec {
	if !p.IsSetSuccess() {
		return TestServiceEchoCoRecResult_Success_DEFAULT
	}
	return p.Success
}

var TestServiceEchoCoRecResult_Err_DEFAULT *CoError

func (p *TestServiceEchoCoRecResult) GetErr() *CoError {
	if !p.IsSetErr() {
		return TestServiceEchoCoRecResult_Err_DEFAULT
	}
	return p.Err
}

func (p *TestServiceEchoCoRecResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestServiceEchoCoRecResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *TestServiceEchoCoRecResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TestServiceEchoCoRecResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &CoRec{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *TestServiceEchoCoRecResult) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Err = &CoError{}
	if err := p.Err.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Err), err)
	}
	return nil
}

func (p *TestServiceEchoCoRecResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "echoCoRec_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TestServiceEchoCoRecResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *TestServiceEchoCoRecResult) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetErr() {
		if err := oprot.WriteFieldBegin(ctx, "err", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:err: ", p), err)
		}
		if err := p.Err.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Err), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:err: ", p), err)
		}
	}
	return err
}

func (p *TestServiceEchoCoRecResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestServiceEchoCoRecResult(%+v)", *p)
}

func (p *TestServiceEchoCoRecResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.TestServiceEchoCoRecResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TestServiceEchoCoRecResult)(nil)

// Attributes:
//   - Item
type TestServiceEchoCoUnionArgs struct {
	Item *CoUnion `thrift:"item,1" db:"item" json:"item"`
}

func NewTestServiceEchoCoUnionArgs() *TestServiceEchoCoUnionArgs {
	return &TestServiceEchoCoUnionArgs{}
}

var TestServiceEchoCoUnionArgs_Item_DEFAULT *CoUnion

func (p *TestServiceEchoCoUnionArgs) GetItem() *CoUnion {
	if !p.IsSetItem() {
		return TestServiceEchoCoUnionArgs_Item_DEFAULT
	}
	return p.Item
}

func (p *TestServiceEchoCoUnionArgs) IsSetItem() bool {
	return p.Item != nil
}

func (p *TestServiceEchoCoUnionArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TestServiceEchoCoUnionArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Item = &CoUnion{}
	if err := p.Item.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Item), err)
	}
	return nil
}

func (p *TestServiceEchoCoUnionArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "echoCoUnion_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TestServiceEchoCoUnionArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetItem() {
		if err := oprot.WriteFieldBegin(ctx, "item", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:item: ", p), err)
		}
		if err := p.Item.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Item), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:item: ", p), err)
		}
	}
	return err
}

func (p *TestServiceEchoCoUnionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestServiceEchoCoUnionArgs(%+v)", *p)
}

func (p *TestServiceEchoCoUnionArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.TestServiceEchoCoUnionArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TestServiceEchoCoUnionArgs)(nil)

// Attributes:
//   - Success
//   - Err
type TestServiceEchoCoUnionResult struct {
	Success *CoUnion `thrift:"success,0" db:"success" json:"success,omitempty"`
	Err     *CoError `thrift:"err,1" db:"err" json:"err,omitempty"`
}

func NewTestServiceEchoCoUnionResult() *TestServiceEchoCoUnionResult {
	return &TestServiceEchoCoUnionResult{}
}

var TestServiceEchoCoUnionResult_Success_DEFAULT *CoUnion

func (p *TestServiceEchoCoUnionResult) GetSuccess() *CoUnion {
	if !p.IsSetSuccess() {
		return TestServiceEchoCoUnionResult_Success_DEFAULT
	}
	return p.Success
}

var TestServiceEchoCoUnionResult_Err_DEFAULT *CoError

func (p *TestServiceEchoCoUnionResult) GetErr() *CoError {
	if !p.IsSetErr() {
		return TestServiceEchoCoUnionResult_Err_DEFAULT
	}
	return p.Err
}

func (p *TestServiceEchoCoUnionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestServiceEchoCoUnionResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *TestServiceEchoCoUnionResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TestServiceEchoCoUnionResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &CoUnion{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *TestServiceEchoCoUnionResult) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Err = &CoError{}
	if err := p.Err.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Err), err)
	}
	return nil
}

func (p *TestServiceEchoCoUnionResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "echoCoUnion_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TestServiceEchoCoUnionResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *TestServiceEchoCoUnionResult) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetErr() {
		if err := oprot.WriteFieldBegin(ctx, "err", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:err: ", p), err)
		}
		if err := p.Err.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Err), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:err: ", p), err)
		}
	}
	return err
}

func (p *TestServiceEchoCoUnionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestServiceEchoCoUnionResult(%+v)", *p)
}

func (p *TestServiceEchoCoUnionResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*recursive.TestServiceEchoCoUnionResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TestServiceEchoCoUnionResult)(nil)
