/**
 * Autogenerated by Thrift Compiler (0.26.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@jakarta.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.26.0)", date = "2026-01-01")
public class Cpp implements org.apache.thrift.TBase<Cpp, Cpp._Fields>, java.io.Serializable, Cloneable, Comparable<Cpp> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Cpp");

  private static final org.apache.thrift.protocol.TField A_FIELD_DESC = new org.apache.thrift.protocol.TField("a", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField B_FIELD_DESC = new org.apache.thrift.protocol.TField("b", org.apache.thrift.protocol.TType.MAP, (short)2);
  private static final org.apache.thrift.protocol.TField C_FIELD_DESC = new org.apache.thrift.protocol.TField("c", org.apache.thrift.protocol.TType.SET, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CppStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CppTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> a; // required
  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.Integer> b; // required
  public @org.apache.thrift.annotation.Nullable java.util.Set<java.lang.Integer> c; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    A((short)1, "a"),
    B((short)2, "b"),
    C((short)3, "c");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // A
          return A;
        case 2: // B
          return B;
        case 3: // C
          return C;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.A, new org.apache.thrift.meta_data.FieldMetaData("a", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.B, new org.apache.thrift.meta_data.FieldMetaData("b", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.C, new org.apache.thrift.meta_data.FieldMetaData("c", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Cpp.class, metaDataMap);
  }

  public Cpp() {
  }

  public Cpp(
    java.util.List<java.lang.Integer> a,
    java.util.Map<java.lang.String,java.lang.Integer> b,
    java.util.Set<java.lang.Integer> c)
  {
    this();
    this.a = a;
    this.b = b;
    this.c = c;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Cpp(Cpp other) {
    if (other.isSetA()) {
      java.util.List<java.lang.Integer> __this__a = new java.util.ArrayList<java.lang.Integer>(other.a);
      this.a = __this__a;
    }
    if (other.isSetB()) {
      java.util.Map<java.lang.String,java.lang.Integer> __this__b = new java.util.HashMap<java.lang.String,java.lang.Integer>(other.b);
      this.b = __this__b;
    }
    if (other.isSetC()) {
      java.util.Set<java.lang.Integer> __this__c = new java.util.HashSet<java.lang.Integer>(other.c);
      this.c = __this__c;
    }
  }

  @Override
  public Cpp deepCopy() {
    return new Cpp(this);
  }

  @Override
  public void clear() {
    this.a = null;
    this.b = null;
    this.c = null;
  }

  public int getASize() {
    return (this.a == null) ? 0 : this.a.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Integer> getAIterator() {
    return (this.a == null) ? null : this.a.iterator();
  }

  public void addToA(int elem) {
    if (this.a == null) {
      this.a = new java.util.ArrayList<java.lang.Integer>();
    }
    this.a.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Integer> getA() {
    return this.a;
  }

  public Cpp setA(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> a) {
    this.a = a;
    return this;
  }

  public void unsetA() {
    this.a = null;
  }

  /** Returns true if field a is set (has been assigned a value) and false otherwise */
  public boolean isSetA() {
    return this.a != null;
  }

  public void setAIsSet(boolean value) {
    if (!value) {
      this.a = null;
    }
  }

  public int getBSize() {
    return (this.b == null) ? 0 : this.b.size();
  }

  public void putToB(java.lang.String key, int val) {
    if (this.b == null) {
      this.b = new java.util.HashMap<java.lang.String,java.lang.Integer>();
    }
    this.b.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String,java.lang.Integer> getB() {
    return this.b;
  }

  public Cpp setB(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.Integer> b) {
    this.b = b;
    return this;
  }

  public void unsetB() {
    this.b = null;
  }

  /** Returns true if field b is set (has been assigned a value) and false otherwise */
  public boolean isSetB() {
    return this.b != null;
  }

  public void setBIsSet(boolean value) {
    if (!value) {
      this.b = null;
    }
  }

  public int getCSize() {
    return (this.c == null) ? 0 : this.c.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Integer> getCIterator() {
    return (this.c == null) ? null : this.c.iterator();
  }

  public void addToC(int elem) {
    if (this.c == null) {
      this.c = new java.util.HashSet<java.lang.Integer>();
    }
    this.c.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Set<java.lang.Integer> getC() {
    return this.c;
  }

  public Cpp setC(@org.apache.thrift.annotation.Nullable java.util.Set<java.lang.Integer> c) {
    this.c = c;
    return this;
  }

  public void unsetC() {
    this.c = null;
  }

  /** Returns true if field c is set (has been assigned a value) and false otherwise */
  public boolean isSetC() {
    return this.c != null;
  }

  public void setCIsSet(boolean value) {
    if (!value) {
      this.c = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case A:
      if (value == null) {
        unsetA();
      } else {
        setA((java.util.List<java.lang.Integer>)value);
      }
      break;

    case B:
      if (value == null) {
        unsetB();
      } else {
        setB((java.util.Map<java.lang.String,java.lang.Integer>)value);
      }
      break;

    case C:
      if (value == null) {
        unsetC();
      } else {
        setC((java.util.Set<java.lang.Integer>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case A:
      return getA();

    case B:
      return getB();

    case C:
      return getC();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case A:
      return isSetA();
    case B:
      return isSetB();
    case C:
      return isSetC();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Cpp)
      return this.equals((Cpp)that);
    return false;
  }

  public boolean equals(Cpp that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_a = true && this.isSetA();
    boolean that_present_a = true && that.isSetA();
    if (this_present_a || that_present_a) {
      if (!(this_present_a && that_present_a))
        return false;
      if (!this.a.equals(that.a))
        return false;
    }

    boolean this_present_b = true && this.isSetB();
    boolean that_present_b = true && that.isSetB();
    if (this_present_b || that_present_b) {
      if (!(this_present_b && that_present_b))
        return false;
      if (!this.b.equals(that.b))
        return false;
    }

    boolean this_present_c = true && this.isSetC();
    boolean that_present_c = true && that.isSetC();
    if (this_present_c || that_present_c) {
      if (!(this_present_c && that_present_c))
        return false;
      if (!this.c.equals(that.c))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetA()) ? 131071 : 524287);
    if (isSetA())
      hashCode = hashCode * 8191 + a.hashCode();

    hashCode = hashCode * 8191 + ((isSetB()) ? 131071 : 524287);
    if (isSetB())
      hashCode = hashCode * 8191 + b.hashCode();

    hashCode = hashCode * 8191 + ((isSetC()) ? 131071 : 524287);
    if (isSetC())
      hashCode = hashCode * 8191 + c.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Cpp other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetA(), other.isSetA());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetA()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.a, other.a);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetB(), other.isSetB());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetB()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.b, other.b);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetC(), other.isSetC());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetC()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.c, other.c);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Cpp(");
    boolean first = true;

    sb.append("a:");
    if (this.a == null) {
      sb.append("null");
    } else {
      sb.append(this.a);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("b:");
    if (this.b == null) {
      sb.append("null");
    } else {
      sb.append(this.b);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("c:");
    if (this.c == null) {
      sb.append("null");
    } else {
      sb.append(this.c);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CppStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public CppStandardScheme getScheme() {
      return new CppStandardScheme();
    }
  }

  private static class CppStandardScheme extends org.apache.thrift.scheme.StandardScheme<Cpp> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Cpp struct) throws org.apache.thrift.TException {
      iprot.incrementRecursionDepth();
      try {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // A
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                  struct.a = new java.util.ArrayList<java.lang.Integer>(org.apache.thrift.TBaseHelper.preallocSize(_list8.size));
                  int _elem9;
                  for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                  {
                    _elem9 = iprot.readI32();
                    struct.a.add(_elem9);
                  }
                  iprot.readListEnd();
                }
                struct.setAIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // B
              if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                {
                  org.apache.thrift.protocol.TMap _map11 = iprot.readMapBegin();
                  struct.b = new java.util.HashMap<java.lang.String,java.lang.Integer>(org.apache.thrift.TBaseHelper.preallocSize(2*_map11.size));
                  @org.apache.thrift.annotation.Nullable java.lang.String _key12;
                  int _val13;
                  for (int _i14 = 0; _i14 < _map11.size; ++_i14)
                  {
                    _key12 = iprot.readString();
                    _val13 = iprot.readI32();
                    struct.b.put(_key12, _val13);
                  }
                  iprot.readMapEnd();
                }
                struct.setBIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // C
              if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
                {
                  org.apache.thrift.protocol.TSet _set15 = iprot.readSetBegin();
                  struct.c = new java.util.HashSet<java.lang.Integer>(org.apache.thrift.TBaseHelper.preallocSize(2*_set15.size));
                  int _elem16;
                  for (int _i17 = 0; _i17 < _set15.size; ++_i17)
                  {
                    _elem16 = iprot.readI32();
                    struct.c.add(_elem16);
                  }
                  iprot.readSetEnd();
                }
                struct.setCIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      } finally {
        iprot.decrementRecursionDepth();
      }
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Cpp struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.a != null) {
        oprot.writeFieldBegin(A_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.a.size()));
          for (int _iter18 : struct.a)
          {
            oprot.writeI32(_iter18);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.b != null) {
        oprot.writeFieldBegin(B_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.I32, struct.b.size()));
          for (java.util.Map.Entry<java.lang.String, java.lang.Integer> _iter19 : struct.b.entrySet())
          {
            oprot.writeString(_iter19.getKey());
            oprot.writeI32(_iter19.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.c != null) {
        oprot.writeFieldBegin(C_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I32, struct.c.size()));
          for (int _iter20 : struct.c)
          {
            oprot.writeI32(_iter20);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CppTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public CppTupleScheme getScheme() {
      return new CppTupleScheme();
    }
  }

  private static class CppTupleScheme extends org.apache.thrift.scheme.TupleScheme<Cpp> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Cpp struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetA()) {
        optionals.set(0);
      }
      if (struct.isSetB()) {
        optionals.set(1);
      }
      if (struct.isSetC()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetA()) {
        {
          oprot.writeI32(struct.a.size());
          for (int _iter21 : struct.a)
          {
            oprot.writeI32(_iter21);
          }
        }
      }
      if (struct.isSetB()) {
        {
          oprot.writeI32(struct.b.size());
          for (java.util.Map.Entry<java.lang.String, java.lang.Integer> _iter22 : struct.b.entrySet())
          {
            oprot.writeString(_iter22.getKey());
            oprot.writeI32(_iter22.getValue());
          }
        }
      }
      if (struct.isSetC()) {
        {
          oprot.writeI32(struct.c.size());
          for (int _iter23 : struct.c)
          {
            oprot.writeI32(_iter23);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Cpp struct) throws org.apache.thrift.TException {
      prot.incrementRecursionDepth();
      try {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list24 = iprot.readListBegin(org.apache.thrift.protocol.TType.I32);
            struct.a = new java.util.ArrayList<java.lang.Integer>(org.apache.thrift.TBaseHelper.preallocSize(_list24.size));
            int _elem25;
            for (int _i26 = 0; _i26 < _list24.size; ++_i26)
            {
              _elem25 = iprot.readI32();
              struct.a.add(_elem25);
            }
          }
          struct.setAIsSet(true);
        }
        if (incoming.get(1)) {
          {
            org.apache.thrift.protocol.TMap _map27 = iprot.readMapBegin(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.I32); 
            struct.b = new java.util.HashMap<java.lang.String,java.lang.Integer>(org.apache.thrift.TBaseHelper.preallocSize(2*_map27.size));
            @org.apache.thrift.annotation.Nullable java.lang.String _key28;
            int _val29;
            for (int _i30 = 0; _i30 < _map27.size; ++_i30)
            {
              _key28 = iprot.readString();
              _val29 = iprot.readI32();
              struct.b.put(_key28, _val29);
            }
          }
          struct.setBIsSet(true);
        }
        if (incoming.get(2)) {
          {
            org.apache.thrift.protocol.TSet _set31 = iprot.readSetBegin(org.apache.thrift.protocol.TType.I32);
            struct.c = new java.util.HashSet<java.lang.Integer>(org.apache.thrift.TBaseHelper.preallocSize(2*_set31.size));
            int _elem32;
            for (int _i33 = 0; _i33 < _set31.size; ++_i33)
            {
              _elem32 = iprot.readI32();
              struct.c.add(_elem32);
            }
          }
          struct.setCIsSet(true);
        }
      } finally {
        prot.decrementRecursionDepth();
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

