/**
 * Autogenerated by Thrift Compiler (0.26.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@jakarta.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.26.0)", date = "2026-01-01")
public class UsesT implements org.apache.thrift.TBase<UsesT, UsesT._Fields>, java.io.Serializable, Cloneable, Comparable<UsesT> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UsesT");

  private static final org.apache.thrift.protocol.TField T_FIELD_DESC = new org.apache.thrift.protocol.TField("t", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField TS_FIELD_DESC = new org.apache.thrift.protocol.TField("ts", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new UsesTStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new UsesTTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable Later t; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<Later> ts; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    T((short)1, "t"),
    TS((short)2, "ts");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // T
          return T;
        case 2: // TS
          return TS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.T, new org.apache.thrift.meta_data.FieldMetaData("t", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Later.class)));
    tmpMap.put(_Fields.TS, new org.apache.thrift.meta_data.FieldMetaData("ts", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Later.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UsesT.class, metaDataMap);
  }

  public UsesT() {
  }

  public UsesT(
    Later t,
    java.util.List<Later> ts)
  {
    this();
    this.t = t;
    this.ts = ts;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UsesT(UsesT other) {
    if (other.isSetT()) {
      this.t = new Later(other.t);
    }
    if (other.isSetTs()) {
      java.util.List<Later> __this__ts = new java.util.ArrayList<Later>(other.ts.size());
      for (Later other_element : other.ts) {
        __this__ts.add(new Later(other_element));
      }
      this.ts = __this__ts;
    }
  }

  @Override
  public UsesT deepCopy() {
    return new UsesT(this);
  }

  @Override
  public void clear() {
    this.t = null;
    this.ts = null;
  }

  @org.apache.thrift.annotation.Nullable
  public Later getT() {
    return this.t;
  }

  public UsesT setT(@org.apache.thrift.annotation.Nullable Later t) {
    this.t = t;
    return this;
  }

  public void unsetT() {
    this.t = null;
  }

  /** Returns true if field t is set (has been assigned a value) and false otherwise */
  public boolean isSetT() {
    return this.t != null;
  }

  public void setTIsSet(boolean value) {
    if (!value) {
      this.t = null;
    }
  }

  public int getTsSize() {
    return (this.ts == null) ? 0 : this.ts.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<Later> getTsIterator() {
    return (this.ts == null) ? null : this.ts.iterator();
  }

  public void addToTs(Later elem) {
    if (this.ts == null) {
      this.ts = new java.util.ArrayList<Later>();
    }
    this.ts.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<Later> getTs() {
    return this.ts;
  }

  public UsesT setTs(@org.apache.thrift.annotation.Nullable java.util.List<Later> ts) {
    this.ts = ts;
    return this;
  }

  public void unsetTs() {
    this.ts = null;
  }

  /** Returns true if field ts is set (has been assigned a value) and false otherwise */
  public boolean isSetTs() {
    return this.ts != null;
  }

  public void setTsIsSet(boolean value) {
    if (!value) {
      this.ts = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case T:
      if (value == null) {
        unsetT();
      } else {
        setT((Later)value);
      }
      break;

    case TS:
      if (value == null) {
        unsetTs();
      } else {
        setTs((java.util.List<Later>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case T:
      return getT();

    case TS:
      return getTs();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case T:
      return isSetT();
    case TS:
      return isSetTs();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof UsesT)
      return this.equals((UsesT)that);
    return false;
  }

  public boolean equals(UsesT that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_t = true && this.isSetT();
    boolean that_present_t = true && that.isSetT();
    if (this_present_t || that_present_t) {
      if (!(this_present_t && that_present_t))
        return false;
      if (!this.t.equals(that.t))
        return false;
    }

    boolean this_present_ts = true && this.isSetTs();
    boolean that_present_ts = true && that.isSetTs();
    if (this_present_ts || that_present_ts) {
      if (!(this_present_ts && that_present_ts))
        return false;
      if (!this.ts.equals(that.ts))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetT()) ? 131071 : 524287);
    if (isSetT())
      hashCode = hashCode * 8191 + t.hashCode();

    hashCode = hashCode * 8191 + ((isSetTs()) ? 131071 : 524287);
    if (isSetTs())
      hashCode = hashCode * 8191 + ts.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(UsesT other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetT(), other.isSetT());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetT()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.t, other.t);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTs(), other.isSetTs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ts, other.ts);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("UsesT(");
    boolean first = true;

    sb.append("t:");
    if (this.t == null) {
      sb.append("null");
    } else {
      sb.append(this.t);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ts:");
    if (this.ts == null) {
      sb.append("null");
    } else {
      sb.append(this.ts);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (t != null) {
      t.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UsesTStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public UsesTStandardScheme getScheme() {
      return new UsesTStandardScheme();
    }
  }

  private static class UsesTStandardScheme extends org.apache.thrift.scheme.StandardScheme<UsesT> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, UsesT struct) throws org.apache.thrift.TException {
      iprot.incrementRecursionDepth();
      try {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // T
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.t = new Later();
                struct.t.read(iprot);
                struct.setTIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // TS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                  struct.ts = new java.util.ArrayList<Later>(org.apache.thrift.TBaseHelper.preallocSize(_list0.size));
                  @org.apache.thrift.annotation.Nullable Later _elem1;
                  for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                  {
                    _elem1 = new Later();
                    _elem1.read(iprot);
                    struct.ts.add(_elem1);
                  }
                  iprot.readListEnd();
                }
                struct.setTsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      } finally {
        iprot.decrementRecursionDepth();
      }
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, UsesT struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.t != null) {
        oprot.writeFieldBegin(T_FIELD_DESC);
        struct.t.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.ts != null) {
        oprot.writeFieldBegin(TS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.ts.size()));
          for (Later _iter3 : struct.ts)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UsesTTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public UsesTTupleScheme getScheme() {
      return new UsesTTupleScheme();
    }
  }

  private static class UsesTTupleScheme extends org.apache.thrift.scheme.TupleScheme<UsesT> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UsesT struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetT()) {
        optionals.set(0);
      }
      if (struct.isSetTs()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetT()) {
        struct.t.write(oprot);
      }
      if (struct.isSetTs()) {
        {
          oprot.writeI32(struct.ts.size());
          for (Later _iter4 : struct.ts)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UsesT struct) throws org.apache.thrift.TException {
      prot.incrementRecursionDepth();
      try {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.t = new Later();
          struct.t.read(iprot);
          struct.setTIsSet(true);
        }
        if (incoming.get(1)) {
          {
            org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
            struct.ts = new java.util.ArrayList<Later>(org.apache.thrift.TBaseHelper.preallocSize(_list5.size));
            @org.apache.thrift.annotation.Nullable Later _elem6;
            for (int _i7 = 0; _i7 < _list5.size; ++_i7)
            {
              _elem6 = new Later();
              _elem6.read(iprot);
              struct.ts.add(_elem6);
            }
          }
          struct.setTsIsSet(true);
        }
      } finally {
        prot.decrementRecursionDepth();
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

