/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package dlang

import (
	"strconv"
	"strings"

	"github.com/apache/thrift/compiler/go/generate/internal/emit"
	"github.com/apache/thrift/compiler/go/internal/version"
	"github.com/apache/thrift/compiler/go/sema"
)

// Options are the "d:" generator options. The C++ generator's constructor
// registers none ("/* no options yet */") and throws "unknown option
// d:<key>" for anything it is handed; see ParseOptions.
type Options struct{}

// ParseOptions parses the part after "d:" of a --gen argument.
func ParseOptions(spec string) (Options, error) {
	var o Options
	for _, option := range strings.Split(spec, ",") {
		if option == "" {
			continue
		}
		key := option
		if i := strings.IndexByte(option, '='); i >= 0 {
			key = option[:i]
		}
		return o, &emit.Error{Msg: "unknown option d:" + key}
	}
	return o, nil
}

// dfile is ofstream_with_content_based_conditional_update: a buffered
// output file, written out with emit.WriteFile once complete.
type dfile struct {
	sb strings.Builder
}

func (f *dfile) write(s string) { f.sb.WriteString(s) }
func (f *dfile) String() string { return f.sb.String() }

// cppNamed is t_container's has_cpp_name()/get_cpp_name(), reached
// through a type assertion since t_container is not surfaced as an
// interface in sema.
type cppNamed interface {
	HasCppName() bool
	CppName() string
}

// Generator is t_d_generator for one program.
type Generator struct {
	program     *sema.Program
	opts        Options
	programName string // program_name_
	packageDir  string // package_dir_
	indentLevel int    // t_generator's indent_

	fTypes dfile // f_types_
}

func newGenerator(program *sema.Program, opts Options) *Generator {
	return &Generator{program: program, opts: opts, programName: program.Name()}
}

// ---- t_generator/t_oop_generator helpers ----

func (g *Generator) indentUp()   { g.indentLevel++ }
func (g *Generator) indentDown() { g.indentLevel-- }

// indent is indent(): t_d_generator does not override indent_str(), so
// the t_generator default of two spaces per level applies.
func (g *Generator) indent() string {
	return strings.Repeat("  ", g.indentLevel)
}

// outDir is get_out_dir() with out_dir_base_ "gen-d".
func (g *Generator) outDir() string {
	if g.program.IsOutPathAbsolute() {
		return g.program.OutPath() + "/"
	}
	return g.program.OutPath() + "gen-d/"
}

func autogenSummary() string {
	return "Autogenerated by Thrift Compiler (" + version.Version + ")"
}

func autogenComment() string {
	return "/**\n" + " * " + autogenSummary() + "\n" + " *\n" +
		" * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n" +
		" *  @generated\n" + " */\n"
}

// formatDouble mimics `ostream << double` with the default precision of
// six significant digits: t_d_generator never calls
// emit_double_as_string, so the field just streams through operator<<.
func formatDouble(f float64) string {
	return strconv.FormatFloat(f, 'g', 6, 64)
}

// dReservedWords is d_reserved_words, extracted from
// https://dlang.org/spec/lex.html and used by suffixIfReserved. The
// entry "macro " keeps the C++ list's trailing space verbatim: it means
// std::binary_search, and this lookup, never actually match the
// identifier "macro".
var dReservedWords = map[string]bool{
	"__FILE_FULL_PATH__": true, "__FILE__": true, "__FUNCTION__": true, "__LINE__": true, "__MODULE__": true,
	"__PRETTY_FUNCTION__": true, "__gshared": true, "__parameters": true, "__traits": true, "__vector": true,
	"abstract": true, "alias": true, "align": true, "asm": true, "assert": true, "auto": true, "body": true, "bool": true,
	"break": true, "byte": true, "case": true, "cast": true, "catch": true, "cdouble": true, "cent": true, "cfloat": true,
	"char": true, "class": true, "const": true, "continue": true, "creal": true, "dchar": true, "debug": true, "default": true,
	"delegate": true, "delete": true, "deprecated": true, "do": true, "double": true, "else": true, "enum": true,
	"export": true, "extern": true, "false": true, "final": true, "finally": true, "float": true, "for": true, "foreach": true,
	"foreach_reverse": true, "function": true, "goto": true, "idouble": true, "if": true, "ifloat": true, "immutable": true,
	"import": true, "in": true, "inout": true, "int": true, "interface": true, "invariant": true, "ireal": true, "is": true,
	"lazy": true, "long": true, "macro ": true, "mixin": true, "module": true, "new": true, "nothrow": true, "null": true, "out": true,
	"override": true, "package": true, "pragma": true, "private": true, "protected": true, "public": true, "pure": true,
	"real": true, "ref": true, "return": true, "scope": true, "shared": true, "short": true, "static": true, "struct": true,
	"super": true, "switch": true, "synchronized": true, "template": true, "this": true, "throw": true, "true": true, "try": true,
	"typeid": true, "typeof": true, "ubyte": true, "ucent": true, "uint": true, "ulong": true, "union": true, "unittest": true,
	"ushort": true, "version": true, "void": true, "wchar": true, "while": true, "with": true,
}

// suffixIfReserved is suffix_if_reserved: D reserved words are suffixed
// with an underscore.
func suffixIfReserved(name string) string {
	if dReservedWords[name] {
		return name + "_"
	}
	return name
}

// renderPackage is render_package: the D package to which modules for
// program are written, with a trailing dot when it is not empty.
func renderPackage(program *sema.Program) string {
	pkg := program.Namespace("d")
	if pkg == "" {
		return ""
	}
	return pkg + "."
}

// isImmutableType is is_immutable_type: whether a value of type is
// implicitly castable to immutable(type), i.e. allowed as an AA key
// without an explicit immutable() qualifier.
func (g *Generator) isImmutableType(typ sema.Type) bool {
	tt := sema.TrueType(typ)
	return tt.IsBaseType() || tt.IsEnum()
}

// renderReq is render_req: the D TReq enum member corresponding to req.
func (g *Generator) renderReq(req sema.Requiredness) string {
	switch req {
	case sema.OptInReqOut:
		return "TReq.OPT_IN_REQ_OUT"
	case sema.Optional:
		return "TReq.OPTIONAL"
	case sema.Required:
		return "TReq.REQUIRED"
	default:
		emit.Throw("Compiler error: Invalid requirement level %d", int(req))
		return ""
	}
}

// renderTypeName is render_type_name: the name of the D representation
// of ttype. If isArg is true, a const reference to the type is returned
// for structs.
func (g *Generator) renderTypeName(ttype sema.Type, isArg bool) string {
	if ttype.IsBaseType() {
		bt := ttype.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeVoid:
			return "void"
		case sema.TypeString:
			return "string"
		case sema.TypeBool:
			return "bool"
		case sema.TypeI8:
			return "byte"
		case sema.TypeI16:
			return "short"
		case sema.TypeI32:
			return "int"
		case sema.TypeI64:
			return "long"
		case sema.TypeDouble:
			return "double"
		default:
			emit.Throw("Compiler error: No D type name for base type %s", sema.BaseName(bt.Base()))
		}
	}

	if ttype.IsContainer() {
		if cn, ok := ttype.(cppNamed); ok && cn.HasCppName() {
			return cn.CppName()
		} else if ttype.IsMap() {
			m := ttype.(*sema.Map)
			ktype := m.KeyType()

			name := g.renderTypeName(m.ValType(), false) + "["
			if !g.isImmutableType(ktype) {
				name += "immutable("
			}
			name += g.renderTypeName(ktype, false)
			if !g.isImmutableType(ktype) {
				name += ")"
			}
			name += "]"
			return name
		} else if ttype.IsSet() {
			s := ttype.(*sema.Set)
			return "HashSet!(" + g.renderTypeName(s.ElemType(), false) + ")"
		} else if ttype.IsList() {
			l := ttype.(*sema.List)
			return g.renderTypeName(l.ElemType(), false) + "[]"
		}
	}

	if ttype.IsStruct() && isArg {
		return "ref const(" + ttype.Name() + ")"
	}
	return ttype.Name()
}

// renderConstValue is render_const_value: the D representation of value,
// guaranteed to be a single expression; for complex types, immediately
// called delegate literals are used to achieve this.
func (g *Generator) renderConstValue(typ sema.Type, value *sema.ConstValue) string {
	typ = sema.TrueType(typ)

	var out strings.Builder
	switch {
	case typ.IsBaseType():
		bt := typ.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeString:
			out.WriteString(`"` + emit.EscapeString(value.String()) + `"`)
		case sema.TypeBool:
			if value.Integer() > 0 {
				out.WriteString("true")
			} else {
				out.WriteString("false")
			}
		case sema.TypeI8, sema.TypeI16:
			out.WriteString("cast(" + g.renderTypeName(typ, false) + ")" + strconv.FormatInt(value.Integer(), 10))
		case sema.TypeI32:
			out.WriteString(strconv.FormatInt(value.Integer(), 10))
		case sema.TypeI64:
			out.WriteString(strconv.FormatInt(value.Integer(), 10) + "L")
		case sema.TypeDouble:
			if value.Kind() == sema.CVInteger {
				out.WriteString(strconv.FormatInt(value.Integer(), 10))
			} else {
				out.WriteString(formatDouble(value.Double()))
			}
		default:
			emit.Throw("Compiler error: No const of base type %s", sema.BaseName(bt.Base()))
		}
	case typ.IsEnum():
		out.WriteString("cast(" + g.renderTypeName(typ, false) + ")" + strconv.FormatInt(value.Integer(), 10))
	default:
		out.WriteString("{\n")
		g.indentUp()

		out.WriteString(g.indent() + g.renderTypeName(typ, false) + " v;\n")
		switch {
		case typ.IsStruct() || typ.IsXception():
			ctor := ""
			if typ.IsXception() {
				ctor = "new "
			}
			out.WriteString(g.indent() + "v = " + ctor + g.renderTypeName(typ, false) + "();\n")

			fields := typ.(*sema.Struct).Members()
			for _, e := range value.Map() {
				var fieldType sema.Type
				for _, f := range fields {
					if f.Name() == e.Key.String() {
						fieldType = f.Type()
					}
				}
				if fieldType == nil {
					emit.Throw("Type error: %s has no field %s", typ.Name(), e.Key.String())
				}
				val := g.renderConstValue(fieldType, e.Value)
				out.WriteString(g.indent() + "v.set!`" + e.Key.String() + "`(" + val + ");\n")
			}
		case typ.IsMap():
			m := typ.(*sema.Map)
			ktype, vtype := m.KeyType(), m.ValType()
			for _, e := range value.Map() {
				key := g.renderConstValue(ktype, e.Key)
				val := g.renderConstValue(vtype, e.Value)
				out.WriteString(g.indent() + "v[")
				if !g.isImmutableType(ktype) {
					out.WriteString("cast(immutable(" + g.renderTypeName(ktype, false) + "))")
				}
				out.WriteString(key + "] = " + val + ";\n")
			}
		case typ.IsList():
			etype := typ.(*sema.List).ElemType()
			for _, e := range value.List() {
				val := g.renderConstValue(etype, e)
				out.WriteString(g.indent() + "v ~= " + val + ";\n")
			}
		case typ.IsSet():
			etype := typ.(*sema.Set).ElemType()
			for _, e := range value.List() {
				val := g.renderConstValue(etype, e)
				out.WriteString(g.indent() + "v ~= " + val + ";\n")
			}
		default:
			emit.Throw("Compiler error: Invalid type in render_const_value: %s", typ.Name())
		}
		out.WriteString(g.indent() + "return v;\n")

		g.indentDown()
		out.WriteString(g.indent() + "}()")
	}

	return out.String()
}

// emitDoc is t_d_generator::emit_doc. Unlike t_generator's shared
// generate_docstring_comment (which this generator does not use),
// emit_doc indents only the "/**" and "*/" lines and the start of the
// doc text itself: the parser's doc comment reliably ends with a
// newline, so no per-line reindentation loop is needed, and a
// multi-line doc's interior lines are written exactly as parsed.
func (g *Generator) emitDoc(hasDoc bool, doc string, f *dfile) {
	if !hasDoc {
		return
	}
	f.write(g.indent() + "/**\n")
	g.indentUp()
	f.write(g.indent() + doc)
	g.indentDown()
	f.write(g.indent() + "*/\n")
}

// printDefaultImports is print_default_imports: the default list of
// imports written to every generated module.
func (g *Generator) printDefaultImports(f *dfile) {
	f.write(g.indent() + "import thrift.base;\n" + "import thrift.codegen.base;\n" + "import thrift.util.hashset;\n\n")
}

// ---- generate_program dispatch ----

// generateProgram is t_generator::generate_program's dispatch order,
// which t_d_generator does not override: init, enums, typedefs, structs
// and exceptions in declared order, consts, services, close.
func (g *Generator) generateProgram() {
	g.initGenerator()
	for _, e := range g.program.Enums() {
		g.generateEnum(e)
	}
	for _, t := range g.program.Typedefs() {
		g.generateTypedef(t)
	}
	for _, s := range g.program.Objects() {
		if s.IsXception() {
			g.generateXception(s)
		} else {
			g.generateStruct(s)
		}
	}
	g.generateConsts(g.program.Consts())
	for _, s := range g.program.Services() {
		g.generateService(s)
	}
	g.closeGenerator()
}

// initGenerator is init_generator: creates the output directory,
// including one nested directory per dot-separated namespace segment,
// and opens f_types_ with its header.
func (g *Generator) initGenerator() {
	emit.Mkdir(g.outDir())

	dir := g.program.Namespace("d")
	subdir := g.outDir()
	for {
		loc := strings.IndexByte(dir, '.')
		if loc < 0 {
			break
		}
		subdir = subdir + "/" + dir[:loc]
		emit.Mkdir(subdir)
		dir = dir[loc+1:]
	}
	if dir != "" {
		subdir = subdir + "/" + dir
		emit.Mkdir(subdir)
	}
	g.packageDir = subdir + "/"

	g.fTypes.write(autogenComment() + "module " + renderPackage(g.program) + g.programName + "_types;\n\n")
	g.printDefaultImports(&g.fTypes)

	includes := g.program.Includes()
	for _, inc := range includes {
		g.fTypes.write("public import " + renderPackage(inc) + inc.Name() + "_types;\n")
	}
	if len(includes) > 0 {
		g.fTypes.write("\n")
	}
}

// closeGenerator is close_generator: writes out f_types_.
func (g *Generator) closeGenerator() {
	emit.WriteFile(g.packageDir+g.programName+"_types.d", g.fTypes.String())
}

// generateConsts is t_d_generator::generate_consts, which overrides
// t_generator's default and is called once with the program's top-level
// constants. No file is written when consts is empty.
func (g *Generator) generateConsts(consts []*sema.Const) {
	if len(consts) == 0 {
		return
	}
	var f dfile
	f.write(autogenComment() + "module " + renderPackage(g.program) + g.programName + "_constants;\n\n")
	g.printDefaultImports(&f)
	f.write("import " + renderPackage(g.program) + g.programName + "_types;\n\n")

	for _, c := range consts {
		g.emitDoc(c.HasDoc(), c.Doc(), &f)
		name := suffixIfReserved(c.Name())
		typ := c.Type()
		f.write(g.indent() + "immutable(" + g.renderTypeName(typ, false) + ") " + name + ";\n")
	}

	f.write("\n" + "shared static this() {\n")
	g.indentUp()

	first := true
	for _, c := range consts {
		if first {
			first = false
		} else {
			f.write("\n")
		}
		typ := c.Type()
		f.write(g.indent() + suffixIfReserved(c.Name()) + " = ")
		if !g.isImmutableType(typ) {
			f.write("cast(immutable(" + g.renderTypeName(typ, false) + ")) ")
		}
		f.write(g.renderConstValue(typ, c.Value()) + ";\n")
	}
	g.indentDown()
	f.write(g.indent() + "}\n")

	emit.WriteFile(g.packageDir+g.programName+"_constants.d", f.String())
}

// generateTypedef is generate_typedef. The symbolic name is written as
// declared, without suffixIfReserved.
func (g *Generator) generateTypedef(t *sema.Typedef) {
	g.emitDoc(t.HasDoc(), t.Doc(), &g.fTypes)
	g.fTypes.write(g.indent() + "alias " + g.renderTypeName(t.Type(), false) + " " + t.Symbolic() + ";\n\n")
}

// generateEnum is generate_enum.
func (g *Generator) generateEnum(tenum *sema.Enum) {
	constants := tenum.Constants()

	g.emitDoc(tenum.HasDoc(), tenum.Doc(), &g.fTypes)
	enumName := suffixIfReserved(tenum.Name())
	g.fTypes.write(g.indent() + "enum " + enumName + " {\n")

	g.indentUp()

	for _, c := range constants {
		g.emitDoc(c.HasDoc(), c.Doc(), &g.fTypes)
		g.fTypes.write(g.indent() + suffixIfReserved(c.Name()))
		g.fTypes.write(" = " + strconv.FormatInt(int64(c.Value()), 10) + ",")
	}

	g.fTypes.write("\n")
	g.indentDown()
	g.fTypes.write(g.indent() + "}\n")

	g.fTypes.write("\n")
}

// generateStruct is generate_struct.
func (g *Generator) generateStruct(tstruct *sema.Struct) {
	g.printStructDefinition(&g.fTypes, tstruct, false)
}

// generateXception is generate_xception.
func (g *Generator) generateXception(txception *sema.Struct) {
	g.printStructDefinition(&g.fTypes, txception, true)
}

// printStructDefinition writes the definition of a struct or an
// exception type to out.
func (g *Generator) printStructDefinition(f *dfile, tstruct *sema.Struct, isException bool) {
	members := tstruct.Members()

	if isException {
		f.write(g.indent() + "class " + suffixIfReserved(tstruct.Name()) + " : TException {\n")
	} else {
		f.write(g.indent() + "struct " + suffixIfReserved(tstruct.Name()) + " {\n")
	}
	g.indentUp()

	// Declare all fields.
	for _, m := range members {
		f.write(g.indent() + g.renderTypeName(m.Type(), false) + " " + suffixIfReserved(m.Name()) + ";\n")
	}

	if len(members) > 0 {
		f.write(g.indent() + "\n")
	}
	f.write(g.indent() + "mixin TStructHelpers!(")

	if len(members) > 0 {
		// If there are any fields, construct the TFieldMeta array to pass
		// to TStructHelpers. We can't just pass an empty array if not
		// because [] doesn't pass the TFieldMeta[] constraint.
		f.write("[")
		g.indentUp()

		first := true
		for _, m := range members {
			if first {
				first = false
			} else {
				f.write(",")
			}
			f.write("\n")

			f.write(g.indent() + "TFieldMeta(`" + suffixIfReserved(m.Name()) + "`, " + strconv.FormatInt(int64(m.Key()), 10))

			cv := m.Value()
			req := m.Req()
			f.write(", " + g.renderReq(req))
			if cv != nil {
				f.write(", q{" + g.renderConstValue(m.Type(), cv) + "}")
			}
			f.write(")")
		}

		g.indentDown()
		f.write("\n" + g.indent() + "]")
	}

	f.write(");\n")

	g.indentDown()
	f.write(g.indent() + "}\n\n")
}

// printFunctionSignature prints the D function signature (including
// return type) for the given method. If isArg is true (in the field
// loop below), a const reference to a struct type is used.
func (g *Generator) printFunctionSignature(f *dfile, fn *sema.Function) {
	f.write(g.renderTypeName(fn.ReturnType(), false) + " " + suffixIfReserved(fn.Name()) + "(")

	fields := fn.Arglist().Members()
	first := true
	for _, field := range fields {
		if first {
			first = false
		} else {
			f.write(", ")
		}
		f.write(g.renderTypeName(field.Type(), true) + " " + suffixIfReserved(field.Name()))
	}

	f.write(")")
}

// generateService is generate_service.
func (g *Generator) generateService(tservice *sema.Service) {
	svcName := suffixIfReserved(tservice.Name())

	// Service implementation file includes.
	var fService dfile
	fService.write(autogenComment() + "module " + suffixIfReserved(renderPackage(g.program)) + svcName + ";\n\n")

	g.printDefaultImports(&fService)

	fService.write("import " + suffixIfReserved(renderPackage(g.program)) + g.programName + "_types;\n")

	extendsService := tservice.Extends()
	if extendsService != nil {
		fService.write("import " + suffixIfReserved(renderPackage(extendsService.Program())) +
			suffixIfReserved(extendsService.Name()) + ";\n")
	}

	fService.write("\n")

	extends := ""
	if tservice.Extends() != nil {
		extends = " : " + suffixIfReserved(g.renderTypeName(tservice.Extends(), false))
	}

	g.emitDoc(tservice.HasDoc(), tservice.Doc(), &fService)
	fService.write(g.indent() + "interface " + svcName + extends + " {\n")
	g.indentUp()

	// Collect all the exception types service methods can throw so we
	// can emit the necessary aliases later. The C++ compiler orders
	// these by t_type* pointer identity (a std::set<t_type*>), which is
	// not a reproducible order; first-encountered order is used here as
	// the closest deterministic stand-in.
	var exceptionTypes []sema.Type
	seenException := map[sema.Type]bool{}

	functions := tservice.Functions()
	for _, fn := range functions {
		g.emitDoc(fn.HasDoc(), fn.Doc(), &fService)
		fService.write(g.indent())
		g.printFunctionSignature(&fService, fn)
		fService.write(";\n")

		for _, ex := range fn.Xceptions().Members() {
			t := ex.Type()
			if !seenException[t] {
				seenException[t] = true
				exceptionTypes = append(exceptionTypes, t)
			}
		}
	}

	// Alias the exception types into the current scope. Note the alias
	// name is written from get_name() directly, without
	// suffixIfReserved, as in the C++ source.
	if len(exceptionTypes) > 0 {
		fService.write("\n")
	}
	for _, et := range exceptionTypes {
		fService.write(g.indent() + "alias " + renderPackage(et.Program()) + et.Program().Name() + "_types" +
			"." + et.Name() + " " + et.Name() + ";\n")
	}

	// Write the method metadata.
	var meta strings.Builder
	g.indentUp()
	first := true
	for _, fn := range functions {
		if len(fn.Arglist().Members()) == 0 && len(fn.Xceptions().Members()) == 0 && !fn.IsOneway() {
			continue
		}

		if first {
			first = false
		} else {
			meta.WriteString(",")
		}

		meta.WriteString("\n" + g.indent() + "TMethodMeta(`" + suffixIfReserved(fn.Name()) + "`, \n")
		g.indentUp()
		meta.WriteString(g.indent() + "[")

		firstParam := true
		params := fn.Arglist().Members()
		for _, p := range params {
			if firstParam {
				firstParam = false
			} else {
				meta.WriteString(", ")
			}

			meta.WriteString("TParamMeta(`" + suffixIfReserved(p.Name()) + "`, " + strconv.FormatInt(int64(p.Key()), 10))

			cv := p.Value()
			if cv != nil {
				meta.WriteString(", q{" + g.renderConstValue(p.Type(), cv) + "}")
			}
			meta.WriteString(")")
		}

		meta.WriteString("]")

		xceptions := fn.Xceptions().Members()
		if len(xceptions) > 0 || fn.IsOneway() {
			meta.WriteString(",\n" + g.indent() + "[")

			firstEx := true
			for _, ex := range xceptions {
				if firstEx {
					firstEx = false
				} else {
					meta.WriteString(", ")
				}

				meta.WriteString("TExceptionMeta(`" + suffixIfReserved(ex.Name()) + "`, " +
					strconv.FormatInt(int64(ex.Key()), 10) + ", `" + ex.Type().Name() + "`)")
			}

			meta.WriteString("]")
		}

		if fn.IsOneway() {
			meta.WriteString(",\n" + g.indent() + "TMethodType.ONEWAY")
		}

		g.indentDown()
		meta.WriteString("\n" + g.indent() + ")")
	}
	g.indentDown()

	metaStr := meta.String()
	if metaStr != "" {
		fService.write("\n" + g.indent() + "enum methodMeta = [" + metaStr + "\n" + g.indent() + "];\n")
	}

	g.indentDown()
	fService.write(g.indent() + "}\n")

	emit.WriteFile(g.packageDir+svcName+".d", fService.String())

	// Server skeleton generation.
	var fSkeleton dfile
	g.printServerSkeleton(&fSkeleton, tservice)
	emit.WriteFile(g.packageDir+svcName+"_server.skeleton.d", fSkeleton.String())
}

// printServerSkeleton writes a server skeleton for the passed service to
// out.
func (g *Generator) printServerSkeleton(f *dfile, tservice *sema.Service) {
	svcName := suffixIfReserved(tservice.Name())

	f.write("/*\n" +
		" * This auto-generated skeleton file illustrates how to build a server. If you\n" +
		" * intend to customize it, you should edit a copy with another file name to \n" +
		" * avoid overwriting it when running the generator again.\n" +
		" */\n" +
		"module " + renderPackage(tservice.Program()) + svcName + "_server;\n" +
		"\n" + "import std.stdio;\n" + "import thrift.codegen.processor;\n" +
		"import thrift.protocol.binary;\n" + "import thrift.server.simple;\n" +
		"import thrift.server.transport.socket;\n" + "import thrift.transport.buffered;\n" +
		"import thrift.util.hashset;\n\n" +
		"import " + renderPackage(tservice.Program()) + svcName + ";\n" +
		"import " + renderPackage(g.program) + g.programName + "_types;\n\n\n" +
		"class " + svcName + "Handler : " + svcName + " {\n")

	g.indentUp()
	f.write(g.indent() + "this() {\n" + g.indent() + "  // Your initialization goes here.\n" + g.indent() + "}\n\n")

	for _, fn := range tservice.Functions() {
		f.write(g.indent())
		g.printFunctionSignature(f, fn)
		f.write(" {\n")

		g.indentUp()

		f.write(g.indent() + "// Your implementation goes here.\n" + g.indent() + "writeln(\"" +
			suffixIfReserved(fn.Name()) + " called\");\n")

		rt := fn.ReturnType()
		if !rt.IsVoid() {
			f.write(g.indent() + "return typeof(return).init;\n")
		}

		g.indentDown()

		f.write(g.indent() + "}\n\n")
	}

	g.indentDown()
	f.write("}\n\n")

	f.write(g.indent() + "void main() {\n")
	g.indentUp()
	f.write(g.indent() + "auto protocolFactory = new TBinaryProtocolFactory!();\n" +
		g.indent() + "auto processor = new TServiceProcessor!" + svcName + "(new " + svcName + "Handler);\n" +
		g.indent() + "auto serverTransport = new TServerSocket(9090);\n" +
		g.indent() + "auto transportFactory = new TBufferedTransportFactory;\n" +
		g.indent() + "auto server = new TSimpleServer(\n" +
		g.indent() + "  processor, serverTransport, transportFactory, protocolFactory);\n" +
		g.indent() + "server.serve();\n")
	g.indentDown()
	f.write("}\n")
}
