/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Package javame is a port of t_javame_generator.cc. Every function keeps
// the name and the emission order of its C++ original, so that the output
// is byte-identical; the parity test in internal/parity holds it to that.
//
// Unlike the full Java generator, t_javame_generator.cc does not resolve
// typedefs before checking is_container()/is_binary()/is_typedef() in a
// few places (the copy constructor and the deep-copy helpers): this port
// reproduces that, using the field's declared (possibly typedef) type
// rather than its resolved type in exactly those spots. See structs.go
// and serialize.go for where that matters.
package javame

import (
	"strconv"
	"strings"

	"github.com/apache/thrift/compiler/go/generate/internal/emit"
	"github.com/apache/thrift/compiler/go/internal/version"
	"github.com/apache/thrift/compiler/go/sema"
)

// Generator is t_javame_generator.
type Generator struct {
	program     *sema.Program
	opts        Options
	programName string
	serviceName string
	indentLevel int
	tmpCounter  int

	packageName  string
	packageDir   string
	fService     strings.Builder
	fServiceName string
}

// New is the t_javame_generator constructor.
func New(program *sema.Program, opts Options) *Generator {
	return &Generator{program: program, opts: opts, programName: program.Name()}
}

// Generate is t_generator::generate_program, as t_javame_generator does
// not override it.
func (g *Generator) Generate() (err error) {
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(*emit.Error); ok {
				err = e
				return
			}
			if e, ok := r.(*sema.Error); ok {
				err = e
				return
			}
			panic(r)
		}
	}()
	g.initGenerator()
	for _, e := range g.program.Enums() {
		g.generateEnum(e)
	}
	// generate_typedef is a no-op (Java has no typedefs), so the C++
	// generate_program's typedef loop has nothing to call here.
	for _, s := range g.program.Objects() {
		if s.IsXception() {
			g.generateXception(s)
		} else {
			g.generateStruct(s)
		}
	}
	g.generateConsts(g.program.Consts())
	for _, s := range g.program.Services() {
		g.serviceName = s.Name()
		g.generateService(s)
	}
	g.closeGenerator()
	return nil
}

// ---- t_generator / t_oop_generator helpers ----

func (g *Generator) indentUp()   { g.indentLevel++ }
func (g *Generator) indentDown() { g.indentLevel-- }

func (g *Generator) indent() string {
	return strings.Repeat("  ", g.indentLevel)
}

func (g *Generator) scopeUp(out *strings.Builder) {
	out.WriteString(g.indent() + "{\n")
	g.indentUp()
}

func (g *Generator) scopeDown(out *strings.Builder) {
	g.indentDown()
	out.WriteString(g.indent() + "}\n")
}

func (g *Generator) tmp(name string) string {
	s := name + strconv.Itoa(g.tmpCounter)
	g.tmpCounter++
	return s
}

func (g *Generator) outDir() string {
	if g.program.IsOutPathAbsolute() {
		return g.program.OutPath() + "/"
	}
	return g.program.OutPath() + "gen-javame/"
}

func autogenComment() string {
	return "/**\n" + " * Autogenerated by Thrift Compiler (" + version.Version + ")\n" + " *\n" +
		" * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n" +
		" *  @generated\n" + " */\n"
}

func upcaseString(s string) string {
	b := []byte(s)
	for i, c := range b {
		b[i] = toUpper(c)
	}
	return string(b)
}

func toUpper(c byte) byte {
	if c >= 'a' && c <= 'z' {
		return c - 'a' + 'A'
	}
	return c
}

func isUpper(c byte) bool { return c >= 'A' && c <= 'Z' }

func itoa(i int64) string { return strconv.FormatInt(i, 10) }

func trueType(t sema.Type) sema.Type { return sema.TrueType(t) }

func baseOf(t sema.Type) sema.BaseKind { return t.(*sema.BaseType).Base() }

// formatDouble mimics `ostream << double` with the default precision of
// six significant digits: t_javame_generator::render_const_value streams
// the double straight onto an ostringstream without calling
// emit_double_as_string, unlike t_java_generator.cc.
func formatDouble(f float64) string {
	return strconv.FormatFloat(f, 'g', 6, 64)
}

// ---- docs (t_oop_generator, overridden by t_javame_generator) ----

// getEnumClassName is t_javame_generator::get_enum_class_name.
func (g *Generator) getEnumClassName(t sema.Type) string {
	pkg := ""
	if p := t.Program(); p != nil && p != g.program {
		pkg = p.Namespace("java") + "."
	}
	return pkg + t.Name()
}

func (g *Generator) javaDocstringComment(out *strings.Builder, contents string) {
	emit.DocstringComment(out, g.indent(), "/**\n", " * ", contents, " */\n")
}

// javaDocField is generate_java_doc(ostream&, t_field*). It checks the
// field's declared type, not its resolved type, unlike the base class
// t_oop_generator version.
func (g *Generator) javaDocField(out *strings.Builder, f *sema.Field) {
	if f.Type().IsEnum() {
		g.javaDocstringComment(out, f.Doc()+"\n@see "+g.getEnumClassName(f.Type()))
	} else {
		g.javaDoc(out, f)
	}
}

// javaDoc is generate_java_doc(ostream&, t_doc*).
func (g *Generator) javaDoc(out *strings.Builder, doc interface {
	HasDoc() bool
	Doc() string
}) {
	if doc.HasDoc() {
		g.javaDocstringComment(out, doc.Doc())
	}
}

// javaDocFunction is generate_java_doc(ostream&, t_function*).
func (g *Generator) javaDocFunction(out *strings.Builder, f *sema.Function) {
	if f.HasDoc() {
		var ss strings.Builder
		ss.WriteString(f.Doc())
		for _, p := range f.Arglist().Members() {
			ss.WriteString("\n@param " + p.Name())
			if p.HasDoc() {
				ss.WriteString(" " + p.Doc())
			}
		}
		emit.DocstringComment(out, g.indent(), "/**\n", " * ", ss.String(), " */\n")
	}
}

// ---- init and close ----

func (g *Generator) initGenerator() {
	emit.Mkdir(g.outDir())
	g.packageName = g.program.Namespace("java")

	dir := g.packageName
	subdir := g.outDir()
	for {
		loc := strings.IndexByte(dir, '.')
		if loc < 0 {
			break
		}
		subdir = subdir + "/" + dir[:loc]
		emit.Mkdir(subdir)
		dir = dir[loc+1:]
	}
	if len(dir) > 0 {
		subdir = subdir + "/" + dir
		emit.Mkdir(subdir)
	}
	g.packageDir = subdir
}

func (g *Generator) javaPackage() string {
	if g.packageName != "" {
		return "package " + g.packageName + ";\n\n"
	}
	return ""
}

func (g *Generator) javaTypeImports() string {
	return "import java.util.Hashtable;\n" +
		"import java.util.Vector;\n" +
		"import java.util.Enumeration;\n\n"
}

func (g *Generator) javaThriftImports() string {
	return "import org.apache.thrift.*;\n" +
		"import org.apache.thrift.meta_data.*;\n" +
		"import org.apache.thrift.transport.*;\n" +
		"import org.apache.thrift.protocol.*;\n\n"
}

func (g *Generator) closeGenerator() {}

// ---- predicates ----

// typeCanBeNull is the inline type_can_be_null in the class declaration.
func typeCanBeNull(t sema.Type) bool {
	t = trueType(t)
	return t.IsContainer() || t.IsStruct() || t.IsXception() || t.IsString() || t.IsEnum()
}

// ---- type names ----

// typeName is type_name(ttype, in_container, in_init, skip_generic). The
// C++ signature takes in_init and skip_generic too, but the body never
// uses them (they are cast to void), so this port drops them.
func (g *Generator) typeName(t sema.Type, inContainer bool) string {
	t = trueType(t)
	if t.IsBaseType() {
		return baseTypeName(t.(*sema.BaseType), inContainer)
	} else if t.IsMap() {
		return "Hashtable"
	} else if t.IsSet() {
		return "Hashtable"
	} else if t.IsList() {
		return "Vector"
	}

	if p := t.Program(); p != nil && p != g.program {
		if pkg := p.Namespace("java"); pkg != "" {
			return pkg + "." + t.Name()
		}
	}
	return t.Name()
}

func (g *Generator) tn(t sema.Type) string { return g.typeName(t, false) }

func baseTypeName(t *sema.BaseType, inContainer bool) string {
	pick := func(boxed, plain string) string {
		if inContainer {
			return boxed
		}
		return plain
	}
	switch t.Base() {
	case sema.TypeVoid:
		return "void"
	case sema.TypeString:
		if !t.IsBinary() {
			return "String"
		}
		return "byte[]"
	case sema.TypeBool:
		return pick("Boolean", "boolean")
	case sema.TypeI8:
		return pick("Byte", "byte")
	case sema.TypeI16:
		return pick("Short", "short")
	case sema.TypeI32:
		return pick("Integer", "int")
	case sema.TypeI64:
		return pick("Long", "long")
	case sema.TypeDouble:
		return pick("Double", "double")
	}
	emit.Throw("compiler error: no Java name for base type %s", sema.BaseName(t.Base()))
	return ""
}

// declareField is declare_field(tfield, init).
func (g *Generator) declareField(f *sema.Field, init bool) string {
	result := g.tn(f.Type()) + " " + f.Name()
	if init {
		tt := trueType(f.Type())
		if tt.IsBaseType() && f.Value() != nil {
			var dummy strings.Builder
			result += " = " + g.renderConstValue(&dummy, tt, f.Value())
		} else if tt.IsBaseType() {
			switch baseOf(tt) {
			case sema.TypeVoid:
				emit.Throw("NO T_VOID CONSTRUCT")
			case sema.TypeString:
				result += " = null"
			case sema.TypeBool:
				result += " = false"
			case sema.TypeI8, sema.TypeI16, sema.TypeI32, sema.TypeI64:
				result += " = 0"
			case sema.TypeDouble:
				result += " = (double)0"
			default:
				emit.Throw("compiler error: unhandled type")
			}
		} else if tt.IsEnum() {
			result += " = 0"
		} else {
			result += " = new " + g.typeName(tt, false) + "()"
		}
	}
	return result + ";"
}

func (g *Generator) functionSignature(f *sema.Function, prefix string) string {
	result := g.tn(f.ReturnType()) + " " + prefix + f.Name() + "(" + g.argumentList(f.Arglist(), true) + ") throws "
	for _, x := range f.Xceptions().Members() {
		result += g.typeName(x.Type(), false) + ", "
	}
	result += "TException"
	return result
}

func (g *Generator) argumentList(s *sema.Struct, includeTypes bool) string {
	result := ""
	first := true
	for _, f := range s.Members() {
		if first {
			first = false
		} else {
			result += ", "
		}
		if includeTypes {
			result += g.tn(f.Type()) + " "
		}
		result += f.Name()
	}
	return result
}

func (g *Generator) typeToEnum(t sema.Type) string {
	t = trueType(t)
	if t.IsBaseType() {
		switch baseOf(t) {
		case sema.TypeVoid:
			emit.Throw("NO T_VOID CONSTRUCT")
		case sema.TypeString:
			return "TType.STRING"
		case sema.TypeBool:
			return "TType.BOOL"
		case sema.TypeI8:
			return "TType.BYTE"
		case sema.TypeI16:
			return "TType.I16"
		case sema.TypeI32:
			return "TType.I32"
		case sema.TypeI64:
			return "TType.I64"
		case sema.TypeDouble:
			return "TType.DOUBLE"
		default:
			emit.Throw("compiler error: unhandled type")
		}
	} else if t.IsEnum() {
		return "TType.I32"
	} else if t.IsStruct() || t.IsXception() {
		return "TType.STRUCT"
	} else if t.IsMap() {
		return "TType.MAP"
	} else if t.IsSet() {
		return "TType.SET"
	} else if t.IsList() {
		return "TType.LIST"
	}
	emit.Throw("INVALID TYPE IN type_to_enum: %s", t.Name())
	return ""
}

// getCapName is get_cap_name: upper-case the first byte only.
func getCapName(name string) string {
	if name == "" {
		return name
	}
	b := []byte(name)
	b[0] = toUpper(b[0])
	return string(b)
}

// constantName is constant_name.
func constantName(name string) string {
	var b []byte
	isFirst := true
	wasPreviousUpper := false
	for i := 0; i < len(name); i++ {
		c := name[i]
		up := isUpper(c)
		if up && !isFirst && !wasPreviousUpper {
			b = append(b, '_')
		}
		b = append(b, toUpper(c))
		isFirst = false
		wasPreviousUpper = up
	}
	return string(b)
}

// ---- isset helpers ----

func (g *Generator) issetCheck(f *sema.Field) string { return g.issetCheckName(f.Name()) }

func issetFieldID(f *sema.Field) string { return "__" + upcaseString(f.Name()+"_isset_id") }

func (g *Generator) issetCheckName(name string) string {
	return "is" + getCapName("set") + getCapName(name) + "()"
}

func (g *Generator) issetSet(out *strings.Builder, f *sema.Field) {
	if !typeCanBeNull(f.Type()) {
		out.WriteString(g.indent() + "set" + getCapName(f.Name()) + getCapName("isSet") + "(true);\n")
	}
}

func (g *Generator) displayName() string { return "Java ME" }
