/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Package kotlin is a port of t_kotlin_generator.cc. Every function keeps
// the name and the emission order of its C++ original, so that the output
// is byte-identical; the parity test in internal/parity holds it to that.
package kotlin

import (
	"strings"

	"github.com/apache/thrift/compiler/go/generate/internal/emit"
	"github.com/apache/thrift/compiler/go/internal/version"
	"github.com/apache/thrift/compiler/go/sema"
)

// kotlinReservedWords is KOTLIN_RESERVED_WORDS_SET.
var kotlinReservedWords = map[string]bool{}

func init() {
	for _, w := range []string{
		"as", "as?", "break", "class", "continue", "do", "else",
		"false", "for", "fun", "if", "in", "!in", "interface",
		"is", "!is", "null", "object", "package", "return", "super",
		"this", "throw", "true", "try", "typealias", "typeof", "val",
		"var", "when", "while", "by", "catch", "constructor", "delegate",
		"dynamic", "field", "file", "finally", "get", "import", "init",
		"param", "property", "receiver", "set", "setparam", "value", "where",
	} {
		kotlinReservedWords[w] = true
	}
}

// Options are the "kotlin:..." generator options. The C++ constructor
// ignores parsed_options and option_string entirely (both parameters are
// commented out), and THRIFT_REGISTER_GENERATOR registers an empty doc
// string, so the generator takes no options at all.
type Options struct{}

// ParseOptions parses the part after "kotlin:" of a --gen argument. Since
// t_kotlin_generator defines no options, any key is unknown.
func ParseOptions(spec string) (Options, error) {
	var o Options
	for _, option := range strings.Split(spec, ",") {
		key := option
		if i := strings.IndexByte(option, '='); i >= 0 {
			key = option[:i]
		}
		switch key {
		case "":
		default:
			return o, &emit.Error{Msg: "unknown option kotlin:" + key}
		}
	}
	return o, nil
}

// Generator is t_kotlin_generator.
type Generator struct {
	program     *sema.Program
	indentLevel int

	packageName string // package_name_
	packageDir  string // package_dir_

	fTypes     strings.Builder // f_types_
	fTypesName string
}

// New is the t_kotlin_generator constructor.
func New(program *sema.Program) *Generator {
	return &Generator{program: program}
}

// Generate is t_generator::generate_program restricted to what
// t_kotlin_generator overrides. t_kotlin_generator does not override
// generate_forward_declaration, whose default in t_generator is a no-op,
// so no forward-declaration pass runs here.
func (g *Generator) Generate() (err error) {
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(*emit.Error); ok {
				err = e
				return
			}
			if e, ok := r.(*sema.Error); ok {
				err = e
				return
			}
			panic(r)
		}
	}()
	g.initGenerator()
	for _, e := range g.program.Enums() {
		g.generateEnum(e)
	}
	for _, t := range g.program.Typedefs() {
		g.generateTypedef(t)
	}
	for _, s := range g.program.Objects() {
		if s.IsXception() {
			g.generateXception(s)
		} else {
			g.generateStruct(s)
		}
	}
	g.generateConsts(g.program.Consts())
	for _, s := range g.program.Services() {
		g.generateService(s)
	}
	g.closeGenerator()
	return nil
}

// ---- t_generator and t_oop_generator helpers ----

func (g *Generator) indentUp()   { g.indentLevel++ }
func (g *Generator) indentDown() { g.indentLevel-- }

func (g *Generator) indent() string {
	return strings.Repeat("  ", g.indentLevel)
}

// scopeDown is scope_down(ostream&): t_kotlin_generator never calls
// scope_up, only scope_down, so that half of the pair is not ported.
func (g *Generator) scopeDown(out *strings.Builder) {
	g.indentDown()
	out.WriteString(g.indent() + "}\n")
}

func autogenSummary() string {
	return "Autogenerated by Thrift Compiler (" + version.Version + ")"
}

// autogenComment is t_generator::autogen_comment, not overridden here.
func autogenComment() string {
	return "/**\n" + " * " + autogenSummary() + "\n" + " *\n" +
		" * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n" +
		" *  @generated\n" + " */\n"
}

// outDir is get_out_dir(). t_kotlin_generator never sets out_dir_base_
// (unlike every other C++ generator, which sets it to "gen-<lang>" in its
// constructor), so out_dir_base_ keeps its default empty value and the
// base directory is just the out path with a trailing slash, whether or
// not -out gave an absolute path.
func (g *Generator) outDir() string {
	return g.program.OutPath() + "/"
}

// ---- init and close ----

// initGenerator is t_kotlin_generator::init_generator.
func (g *Generator) initGenerator() {
	emit.Mkdir(g.outDir())
	g.packageName = g.program.Namespace("java")
	dir := g.packageName
	subdir := g.outDir()
	for {
		loc := strings.IndexByte(dir, '.')
		if loc < 0 {
			break
		}
		subdir = subdir + "/" + dir[:loc]
		emit.Mkdir(subdir)
		dir = dir[loc+1:]
	}
	if len(dir) > 0 {
		subdir = subdir + "/" + dir
		emit.Mkdir(subdir)
	}
	g.packageDir = subdir

	g.fTypesName = g.packageDir + "/" + g.program.Name() + "Constants.kt"
	g.fTypes.WriteString(autogenComment() + g.kotlinPackage())
}

// closeGenerator is t_kotlin_generator::close_generator.
func (g *Generator) closeGenerator() {
	g.fTypes.WriteString("\n")
	emit.WriteFile(g.fTypesName, g.fTypes.String())
}

// kotlinPackage is t_kotlin_generator::kotlin_package.
func (g *Generator) kotlinPackage() string {
	if g.packageName != "" {
		return "package " + g.packageName + "\n" + "\n"
	}
	return ""
}

// warningSuppressions is t_kotlin_generator::warning_surpressions.
func warningSuppressions() string {
	return "@file:Suppress(\"ClassName\", \"PropertyName\", \"RedundantUnitReturnType\", " +
		"\"NestedLambdaShadowedImplicitParameter\", " +
		"\"RemoveRedundantQualifierName\")\n"
}

// isReserved is t_kotlin_generator::is_reserved.
func isReserved(name string) bool { return kotlinReservedWords[name] }

// kotlinSafeName is t_kotlin_generator::kotlin_safe_name.
func kotlinSafeName(name string) string {
	if isReserved(name) {
		return "`" + name + "`"
	}
	return name
}

// generateKdocComment is t_kotlin_generator::generate_kdoc_comment.
func (g *Generator) generateKdocComment(out *strings.Builder, doc interface {
	HasDoc() bool
	Doc() string
}) {
	if doc.HasDoc() {
		emit.DocstringComment(out, g.indent(), "/**\n", " * ", doc.Doc(), " */\n")
	}
}

// displayName is t_kotlin_generator::display_name. It names the generator
// in --help output only and does not affect generated output.
func displayName() string { return "Kotlin" }

// ---- type names ----

// baseTypeName is t_kotlin_generator::base_type_name.
func baseTypeName(t *sema.BaseType) string {
	switch t.Base() {
	case sema.TypeVoid:
		return "kotlin.Unit"
	case sema.TypeString:
		if t.IsBinary() {
			return "kotlin.ByteArray"
		}
		return "kotlin.String"
	case sema.TypeBool:
		return "kotlin.Boolean"
	case sema.TypeI8:
		return "kotlin.Byte"
	case sema.TypeI16:
		return "kotlin.Short"
	case sema.TypeI32:
		return "kotlin.Int"
	case sema.TypeI64:
		return "kotlin.Long"
	case sema.TypeUUID:
		return "java.util.UUID"
	case sema.TypeDouble:
		return "kotlin.Double"
	}
	emit.Throw("compiler error: no Kotlin name for base type %s", sema.BaseName(t.Base()))
	return ""
}

// typeName is t_kotlin_generator::type_name(ttype, in_init, skip_generic,
// force_namespace). in_init is kept as a parameter for fidelity with the
// C++ signature, but the C++ body sets the same prefix in both branches of
// every in_init check, so it never changes the result.
func (g *Generator) typeName(t sema.Type, inInit, skipGeneric, forceNamespace bool) string {
	_ = inInit
	t = sema.TrueType(t)
	if t.IsBaseType() {
		return baseTypeName(t.(*sema.BaseType))
	} else if t.IsMap() {
		m := t.(*sema.Map)
		prefix := "kotlin.collections.Map"
		if skipGeneric {
			return prefix
		}
		return prefix + "<" + g.typeName(m.KeyType(), true, false, false) + ", " + g.typeName(m.ValType(), true, false, false) + ">"
	} else if t.IsSet() {
		s := t.(*sema.Set)
		prefix := "kotlin.collections.Set"
		if skipGeneric {
			return prefix
		}
		return prefix + "<" + g.typeName(s.ElemType(), true, false, false) + ">"
	} else if t.IsList() {
		l := t.(*sema.List)
		prefix := "kotlin.collections.List"
		if skipGeneric {
			return prefix
		}
		return prefix + "<" + g.typeName(l.ElemType(), true, false, false) + ">"
	}

	if p := t.Program(); p != nil && (p != g.program || forceNamespace) {
		if pkg := p.Namespace("java"); pkg != "" {
			return pkg + "." + kotlinSafeName(t.Name())
		}
	}
	return kotlinSafeName(t.Name())
}

// tn is the common call typeName(t, false, false, false).
func (g *Generator) tn(t sema.Type) string { return g.typeName(t, false, false, false) }

// typeToEnum is t_kotlin_generator::type_to_enum.
func (g *Generator) typeToEnum(t sema.Type) string {
	t = sema.TrueType(t)
	if t.IsBaseType() {
		switch t.(*sema.BaseType).Base() {
		case sema.TypeVoid:
			emit.Throw("NO T_VOID CONSTRUCT")
		case sema.TypeString:
			return "org.apache.thrift.protocol.TType.STRING"
		case sema.TypeBool:
			return "org.apache.thrift.protocol.TType.BOOL"
		case sema.TypeI8:
			return "org.apache.thrift.protocol.TType.BYTE"
		case sema.TypeI16:
			return "org.apache.thrift.protocol.TType.I16"
		case sema.TypeI32:
			return "org.apache.thrift.protocol.TType.I32"
		case sema.TypeI64:
			return "org.apache.thrift.protocol.TType.I64"
		case sema.TypeUUID:
			return "org.apache.thrift.protocol.TType.UUID"
		case sema.TypeDouble:
			return "org.apache.thrift.protocol.TType.DOUBLE"
		default:
			emit.Throw("compiler error: unhandled type")
		}
	} else if t.IsEnum() {
		return "org.apache.thrift.protocol.TType.I32"
	} else if t.IsStruct() || t.IsXception() {
		return "org.apache.thrift.protocol.TType.STRUCT"
	} else if t.IsMap() {
		return "org.apache.thrift.protocol.TType.MAP"
	} else if t.IsSet() {
		return "org.apache.thrift.protocol.TType.SET"
	} else if t.IsList() {
		return "org.apache.thrift.protocol.TType.LIST"
	}
	emit.Throw("INVALID TYPE IN type_to_enum: %s", t.Name())
	return ""
}

// constantName is t_kotlin_generator::constant_name.
func constantName(name string) string {
	var b []byte
	isFirst := true
	wasPreviousUpper := false
	for i := 0; i < len(name); i++ {
		c := name[i]
		up := c >= 'A' && c <= 'Z'
		if up && !isFirst && !wasPreviousUpper {
			b = append(b, '_')
		}
		b = append(b, toUpperByte(c))
		isFirst = false
		wasPreviousUpper = up
	}
	return string(b)
}

func toUpperByte(c byte) byte {
	if c >= 'a' && c <= 'z' {
		return c - 'a' + 'A'
	}
	return c
}

// ---- dead code ----
//
// inner_enum_type_name, is_enum_set and is_enum_map are declared and
// defined in t_kotlin_generator.cc (apparently carried over from the Java
// generator it was cloned from) but never called from anywhere else in
// that file. They are ported here for fidelity but are themselves unused.

// innerEnumTypeName is t_kotlin_generator::inner_enum_type_name.
func (g *Generator) innerEnumTypeName(t sema.Type) string {
	t = sema.TrueType(t)
	if t.IsMap() {
		return g.typeName(sema.TrueType(t.(*sema.Map).KeyType()), true, false, false) + ".class"
	} else if t.IsSet() {
		return g.typeName(sema.TrueType(t.(*sema.Set).ElemType()), true, false, false) + ".class"
	}
	return ""
}

// isEnumSet is t_kotlin_generator::is_enum_set.
func isEnumSet(t sema.Type) bool {
	t = sema.TrueType(t)
	if t.IsSet() {
		return sema.TrueType(t.(*sema.Set).ElemType()).IsEnum()
	}
	return false
}

// isEnumMap is t_kotlin_generator::is_enum_map.
func isEnumMap(t sema.Type) bool {
	t = sema.TrueType(t)
	if t.IsMap() {
		return sema.TrueType(t.(*sema.Map).KeyType()).IsEnum()
	}
	return false
}
