/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Package lua is a method-for-method port of
// compiler/cpp/src/thrift/generate/t_lua_generator.cc. Every function keeps
// the name and the emission order of its C++ original, so that the output
// is byte-identical; the parity test in internal/parity holds it to that.
package lua

import (
	"strconv"
	"strings"

	"github.com/apache/thrift/compiler/go/generate/internal/emit"
	"github.com/apache/thrift/compiler/go/sema"
)

// Generator is t_lua_generator for one program.
type Generator struct {
	program *sema.Program
	opts    Options

	// indentLevel is indent_: the current code indentation level,
	// shared mutable state across the whole generation of the program.
	indentLevel int
	tmpCounter  int

	fTypes     strings.Builder
	fTypesName string

	fConsts     strings.Builder
	fConstsName string
}

// New is the t_lua_generator constructor.
func New(program *sema.Program, opts Options) *Generator {
	return &Generator{program: program, opts: opts}
}

// Generate is t_generator::generate_program restricted to the calls the
// Lua generator overrides.
func (g *Generator) Generate() (err error) {
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(*emit.Error); ok {
				err = e
				return
			}
			if e, ok := r.(*sema.Error); ok {
				err = e
				return
			}
			panic(r)
		}
	}()
	g.initGenerator()

	for _, e := range g.program.Enums() {
		g.generateEnum(e)
	}
	for _, t := range g.program.Typedefs() {
		g.generateTypedef(t)
	}
	for _, s := range g.program.Objects() {
		if s.IsXception() {
			g.generateXception(s)
		} else {
			g.generateStruct(s)
		}
	}
	// generate_consts (the t_generator default): a plain loop over
	// generate_const.
	for _, c := range g.program.Consts() {
		g.generateConst(c)
	}
	for _, s := range g.program.Services() {
		g.generateService(s)
	}

	g.closeGenerator()
	return nil
}

// ---- t_generator helpers ----

func (g *Generator) indentUp()   { g.indentLevel++ }
func (g *Generator) indentDown() { g.indentLevel-- }

// indent is t_generator::indent(): two spaces per level, the base
// t_generator default that t_lua_generator does not override.
func (g *Generator) indent() string {
	return strings.Repeat("  ", g.indentLevel)
}

// line is `indent(out) << s << '\n'`.
func (g *Generator) line(out *strings.Builder, s string) {
	out.WriteString(g.indent() + s + "\n")
}

// indentRaw is `indent(out) << s`, with no trailing newline, for call
// sites that keep writing to the same line afterwards.
func (g *Generator) indentRaw(out *strings.Builder, s string) {
	out.WriteString(g.indent() + s)
}

// tmp is t_generator::tmp: name plus a shared, post-incremented counter.
func (g *Generator) tmp(name string) string {
	s := name + strconv.Itoa(g.tmpCounter)
	g.tmpCounter++
	return s
}

// outDir is t_generator::get_out_dir with out_dir_base_ == "gen-lua".
func (g *Generator) outDir() string {
	if g.program.IsOutPathAbsolute() {
		return g.program.OutPath() + "/"
	}
	return g.program.OutPath() + "gen-lua" + "/"
}

// autogenComment is t_lua_generator::autogen_comment.
func (g *Generator) autogenComment() string {
	return "--\n" +
		"-- Autogenerated by Thrift\n" +
		"--\n" +
		"-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n" +
		"-- @generated\n" +
		"--\n"
}

// luaIncludes is t_lua_generator::lua_includes.
func (g *Generator) luaIncludes() string {
	if !g.opts.OmitRequires {
		return "\n\nrequire 'Thrift'"
	}
	return ""
}

// getNamespace is t_lua_generator::get_namespace.
func getNamespace(program *sema.Program) string {
	realModule := program.Namespace("lua")
	if realModule == "" {
		return program.Name() + "_"
	}
	return realModule + "_"
}

// ---- init and close ----

// initGenerator is t_lua_generator::init_generator.
func (g *Generator) initGenerator() {
	outDir := g.outDir()
	emit.Mkdir(outDir)

	curNamespace := getNamespace(g.program)
	g.fConstsName = outDir + curNamespace + "constants.lua"
	g.fTypesName = outDir + curNamespace + "ttypes.lua"

	g.fConsts.WriteString(g.autogenComment() + g.luaIncludes())
	g.fTypes.WriteString(g.autogenComment() + g.luaIncludes())
	if !g.opts.OmitRequires {
		g.fTypes.WriteString("\n" + "require '" + curNamespace + "constants'")
	}
}

// closeGenerator is t_lua_generator::close_generator.
func (g *Generator) closeGenerator() {
	emit.WriteFile(g.fTypesName, g.fTypes.String())
	emit.WriteFile(g.fConstsName, g.fConsts.String())
}

// generateTypedef is t_lua_generator::generate_typedef: essentially a
// constant.
func (g *Generator) generateTypedef(t *sema.Typedef) {
	if t.Type().Name() == "" {
		return
	}
	g.fTypes.WriteString("\n\n" + g.indent() + t.Symbolic() + " = " + t.Type().Name())
}

// generateEnum is t_lua_generator::generate_enum: an enumerated type
// (table).
func (g *Generator) generateEnum(e *sema.Enum) {
	g.fTypes.WriteString("\n\n" + e.Name() + " = {\n")

	constants := e.Constants()
	for i, c := range constants {
		g.fTypes.WriteString("  " + c.Name() + " = " + strconv.FormatInt(int64(c.Value()), 10))
		if i != len(constants)-1 {
			g.fTypes.WriteString(",")
		}
		g.fTypes.WriteString("\n")
	}
	g.fTypes.WriteString("}")
}

// generateConst is t_lua_generator::generate_const: a constant (non-local)
// value.
func (g *Generator) generateConst(c *sema.Const) {
	g.fConsts.WriteString("\n\n" + c.Name() + " = ")
	g.fConsts.WriteString(g.renderConstValue(c.Type(), c.Value()))
}

// renderConstValue is t_lua_generator::render_const_value: the value of a
// constant with the given type.
func (g *Generator) renderConstValue(t sema.Type, value *sema.ConstValue) string {
	var out strings.Builder

	t = sema.TrueType(t)
	switch {
	case t.IsBaseType():
		bt := t.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeString:
			out.WriteString("'" + value.String() + "'")
		case sema.TypeBool:
			if value.Integer() > 0 {
				out.WriteString("true")
			} else {
				out.WriteString("false")
			}
		case sema.TypeI8, sema.TypeI16, sema.TypeI32:
			out.WriteString(strconv.FormatInt(value.Integer(), 10))
		case sema.TypeI64:
			out.WriteString("lualongnumber.new('" + strconv.FormatInt(value.Integer(), 10) + "')")
		case sema.TypeDouble:
			if value.Kind() == sema.CVInteger {
				out.WriteString(strconv.FormatInt(value.Integer(), 10))
			} else {
				out.WriteString(formatDouble(value.Double()))
			}
		case sema.TypeUUID:
			out.WriteString("TUUIDfromString(" + value.String() + ")")
		default:
			emit.Throw("compiler error: no const of base type %s", sema.BaseName(bt.Base()))
		}
	case t.IsEnum():
		out.WriteString(strconv.FormatInt(value.Integer(), 10))
	case t.IsStruct() || t.IsXception():
		out.WriteString(t.Name() + " = {\n")
		g.indentUp()

		fields := t.(*sema.Struct).Members()
		entries := value.Map()
		for i, entry := range entries {
			var fieldType sema.Type
			for _, f := range fields {
				if f.Name() == entry.Key.String() {
					fieldType = f.Type()
				}
			}
			if fieldType == nil {
				emit.Throw("type error: %s has no field %s", t.Name(), entry.Key.String())
			}

			out.WriteString(g.indent())
			out.WriteString(g.renderConstValue(sema.GlobalString, entry.Key))
			out.WriteString(" = ")
			out.WriteString(g.renderConstValue(fieldType, entry.Value))
			if i != len(entries)-1 {
				out.WriteString(",")
			}
		}

		out.WriteString("}")
		g.indentDown()
	case t.IsMap():
		m := t.(*sema.Map)
		out.WriteString(t.Name() + "{\n")
		g.indentUp()

		entries := value.Map()
		for i, entry := range entries {
			out.WriteString(g.indent() + "[" + g.renderConstValue(m.KeyType(), entry.Key) + "] = " + g.renderConstValue(m.ValType(), entry.Value))
			if i != len(entries)-1 {
				out.WriteString(",")
			}
			out.WriteString("\n")
		}
		g.indentDown()
		out.WriteString(g.indent() + "}")
	case t.IsList() || t.IsSet():
		var etype sema.Type
		if t.IsList() {
			etype = t.(*sema.List).ElemType()
		} else {
			etype = t.(*sema.Set).ElemType()
		}
		out.WriteString(t.Name() + " = {\n")
		entries := value.List()
		for i, e := range entries {
			out.WriteString(g.indent())
			out.WriteString("[" + g.renderConstValue(etype, e) + "]")
			if t.IsSet() {
				out.WriteString(" = true")
			} else {
				out.WriteString(" = false")
			}
			if i != len(entries)-1 {
				out.WriteString(",\n")
			}
		}
		out.WriteString("}")
	}
	return out.String()
}

// generateStruct is t_lua_generator::generate_struct: a thrift struct.
func (g *Generator) generateStruct(s *sema.Struct) {
	g.generateLuaStructDefinition(&g.fTypes, s, false)
}

// generateXception is t_lua_generator::generate_xception: a thrift
// exception.
func (g *Generator) generateXception(s *sema.Struct) {
	g.generateLuaStructDefinition(&g.fTypes, s, true)
}

// generateLuaStructDefinition is t_lua_generator::generate_lua_struct_definition:
// a thrift struct or exception (lua table).
func (g *Generator) generateLuaStructDefinition(out *strings.Builder, s *sema.Struct, isException bool) {
	members := s.Members()

	out.WriteString(g.indent() + "\n\n" + s.Name())
	if isException {
		out.WriteString(" = TException:new{\n" + g.indent() + "  __type = '" + s.Name() + "'")
		if len(members) > 0 {
			out.WriteString(",")
		}
		out.WriteString("\n")
	} else {
		out.WriteString(" = __TObject:new{\n")
	}
	g.indentUp()
	for i, m := range members {
		out.WriteString(g.indent())
		out.WriteString(m.Name())
		if i != len(members)-1 {
			out.WriteString(",\n")
		}
	}
	g.indentDown()
	out.WriteString(g.indent())
	out.WriteString("\n}")

	g.generateLuaStructReader(out, s)
	g.generateLuaStructWriter(out, s)
}

// generateLuaStructReader is t_lua_generator::generate_lua_struct_reader:
// a struct/exception reader.
func (g *Generator) generateLuaStructReader(out *strings.Builder, s *sema.Struct) {
	fields := s.Members()

	out.WriteString(g.indent() + "\n\n" + "function " + s.Name() + ":read(iprot)" + "\n")
	g.indentUp()

	g.line(out, "iprot:incrementRecursionDepth()")
	g.line(out, "local ok, err = pcall(function()")
	g.indentUp()
	g.line(out, "iprot:readStructBegin()")

	g.line(out, "while true do")
	g.indentUp()

	g.line(out, "local fname, ftype, fid = iprot:readFieldBegin()")
	g.line(out, "if ftype == TType.STOP then")
	g.indentUp()
	g.line(out, "break")

	for _, f := range fields {
		g.indentDown()
		g.line(out, "elseif fid == "+strconv.FormatInt(int64(f.Key()), 10)+" then")
		g.indentUp()
		g.line(out, "if ftype == "+g.typeToEnum(f.Type())+" then")
		g.indentUp()

		g.generateDeserializeField(out, f, false, "self.")

		g.indentDown()
		g.line(out, "else")
		g.line(out, "  iprot:skip(ftype)")
		g.line(out, "end")
	}

	g.indentDown()
	g.line(out, "else")
	g.line(out, "  iprot:skip(ftype)")
	g.line(out, "end")
	g.line(out, "iprot:readFieldEnd()")

	g.indentDown()
	g.line(out, "end")
	g.line(out, "iprot:readStructEnd()")
	g.indentDown()
	g.line(out, "end)")
	g.line(out, "iprot:decrementRecursionDepth()")
	g.line(out, "if not ok then error(err, 0) end")

	g.indentDown()
	out.WriteString(g.indent() + "end")
}

// generateLuaStructWriter is t_lua_generator::generate_lua_struct_writer:
// a struct/exception writer.
func (g *Generator) generateLuaStructWriter(out *strings.Builder, s *sema.Struct) {
	fields := s.Members()

	out.WriteString(g.indent() + "\n\n" + "function " + s.Name() + ":write(oprot)" + "\n")
	g.indentUp()

	g.line(out, "oprot:incrementRecursionDepth()")
	g.line(out, "local ok, err = pcall(function()")
	g.indentUp()
	g.line(out, "oprot:writeStructBegin('"+s.Name()+"')")
	for _, f := range fields {
		g.line(out, "if self."+f.Name()+" ~= nil then")
		g.indentUp()
		g.line(out, "oprot:writeFieldBegin('"+f.Name()+"', "+g.typeToEnum(f.Type())+", "+strconv.FormatInt(int64(f.Key()), 10)+")")

		g.generateSerializeField(out, f, "self.")

		g.line(out, "oprot:writeFieldEnd()")
		g.indentDown()
		g.line(out, "end")
	}
	g.line(out, "oprot:writeFieldStop()")
	g.line(out, "oprot:writeStructEnd()")
	g.indentDown()
	g.line(out, "end)")
	g.line(out, "oprot:decrementRecursionDepth()")
	g.line(out, "if not ok then error(err, 0) end")

	g.indentDown()
	out.WriteString(g.indent() + "end")
}

// functionSignature is t_lua_generator::function_signature. The C++
// original takes an unused prefix parameter; every call site omits it.
func (g *Generator) functionSignature(f *sema.Function) string {
	return f.Name() + "(" + g.argumentList(f.Arglist(), "") + ")"
}

// argumentList is t_lua_generator::argument_list.
func (g *Generator) argumentList(s *sema.Struct, prefix string) string {
	fields := s.Members()
	var ret strings.Builder
	for i, f := range fields {
		ret.WriteString(prefix + f.Name())
		if i != len(fields)-1 {
			ret.WriteString(", ")
		}
	}
	return ret.String()
}

// typeToEnum is t_lua_generator::type_to_enum.
func (g *Generator) typeToEnum(t sema.Type) string {
	t = sema.TrueType(t)

	switch {
	case t.IsBaseType():
		bt := t.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeVoid:
			emit.Throw("NO T_VOID CONSTRUCT")
		case sema.TypeString:
			return "TType.STRING"
		case sema.TypeBool:
			return "TType.BOOL"
		case sema.TypeI8:
			return "TType.BYTE"
		case sema.TypeI16:
			return "TType.I16"
		case sema.TypeI32:
			return "TType.I32"
		case sema.TypeI64:
			return "TType.I64"
		case sema.TypeDouble:
			return "TType.DOUBLE"
		case sema.TypeUUID:
			return "TType.UUID"
		default:
			emit.Throw("compiler error: unhandled type")
		}
	case t.IsEnum():
		return "TType.I32"
	case t.IsStruct() || t.IsXception():
		return "TType.STRUCT"
	case t.IsMap():
		return "TType.MAP"
	case t.IsSet():
		return "TType.SET"
	case t.IsList():
		return "TType.LIST"
	}

	emit.Throw("INVALID TYPE IN type_to_enum: %s", t.Name())
	panic("unreachable")
}

// formatDouble mimics `ostream << double` with the default precision of
// six significant digits, as golang.formatDouble does.
func formatDouble(f float64) string {
	return strconv.FormatFloat(f, 'g', 6, 64)
}
