/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package cglib

import (
	"strconv"
	"strings"

	"github.com/apache/thrift/compiler/go/generate/internal/emit"
	"github.com/apache/thrift/compiler/go/internal/version"
	"github.com/apache/thrift/compiler/go/sema"
)

// Options are the "c_glib:" generator options. The C++ generator's
// constructor registers none and throws "unknown option c_glib:<key>"
// for anything it is handed; see ParseOptions.
type Options struct{}

// ParseOptions parses the part after "c_glib:" of a --gen argument.
func ParseOptions(spec string) (Options, error) {
	var o Options
	for _, option := range strings.Split(spec, ",") {
		if option == "" {
			continue
		}
		key := option
		if i := strings.IndexByte(option, '='); i >= 0 {
			key = option[:i]
		}
		return o, &emit.Error{Msg: "unknown option c_glib:" + key}
	}
	return o, nil
}

// Generator is t_c_glib_generator for one program.
type Generator struct {
	program *sema.Program
	opts    Options

	// namespace variables, computed once as the constructor does.
	nspace   string
	nspaceUC string
	nspaceLC string

	// service_name_: the t_generator field set before each generate_service call.
	serviceName string

	ind        int
	tmpCounter int

	// file streams
	fTypes     strings.Builder
	fTypesImpl strings.Builder
	fHeader    strings.Builder
	fService   strings.Builder

	fTypesName     string
	fTypesImplName string
}

// New creates a generator for the program.
func New(program *sema.Program, opts Options) *Generator {
	g := &Generator{program: program, opts: opts}

	nspace := program.Namespace("c_glib")
	if nspace == "" {
		g.nspace, g.nspaceUC, g.nspaceLC = "", "", ""
	} else {
		// replace dots with underscores
		nspace = strings.ReplaceAll(nspace, ".", "_")
		g.nspace = nspace
		nspaceU := initialCapsToUnderscores(nspace)
		g.nspaceUC = toUpperCase(nspaceU) + "_"
		g.nspaceLC = toLowerCase(nspaceU) + "_"
	}
	return g
}

// outDir is t_generator::get_out_dir with out_dir_base_ == "gen-c_glib".
func (g *Generator) outDir() string {
	if g.program.IsOutPathAbsolute() {
		return g.program.OutPath() + "/"
	}
	return g.program.OutPath() + "gen-c_glib/"
}

// ---- indentation, scoping and temporaries, matching t_generator /
// t_oop_generator ----

const indentStr = "  "

func (g *Generator) indentUp()   { g.ind++ }
func (g *Generator) indentDown() { g.ind-- }

// indent is indent(): the current indentation prefix.
func (g *Generator) indent() string { return strings.Repeat(indentStr, g.ind) }

// tmp is t_generator::tmp.
func (g *Generator) tmp(name string) string {
	s := name + strconv.Itoa(g.tmpCounter)
	g.tmpCounter++
	return s
}

// scopeUp/scopeDown are t_oop_generator::scope_up/scope_down.
func (g *Generator) scopeUp(out *strings.Builder) {
	out.WriteString(g.indent() + "{\n")
	g.indentUp()
}

func (g *Generator) scopeDown(out *strings.Builder) {
	g.indentDown()
	out.WriteString(g.indent() + "}\n")
}

// autogenComment is t_generator::autogen_comment, unoverridden by
// t_c_glib_generator.
func autogenComment() string {
	return "/**\n" +
		" * Autogenerated by Thrift Compiler (" + version.Version + ")\n" +
		" *\n" +
		" * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n" +
		" *  @generated\n" +
		" */\n"
}

// formatDouble mimics `ostream << double` with the default precision of
// six significant digits.
func formatDouble(f float64) string {
	return strconv.FormatFloat(f, 'g', 6, 64)
}

// ---- case-conversion utility functions ----

func lowerByte(c byte) byte {
	if c >= 'A' && c <= 'Z' {
		return c + ('a' - 'A')
	}
	return c
}

func upperByte(c byte) byte {
	if c >= 'a' && c <= 'z' {
		return c - ('a' - 'A')
	}
	return c
}

// toUpperCase upper-cases a string.
func toUpperCase(name string) string {
	b := []byte(name)
	for i, c := range b {
		b[i] = upperByte(c)
	}
	return string(b)
}

// toLowerCase lower-cases a string.
func toLowerCase(name string) string {
	b := []byte(name)
	for i, c := range b {
		b[i] = lowerByte(c)
	}
	return string(b)
}

// initialCapsToUnderscores makes a string friendly to C code standards by
// lowercasing and adding underscores, with the exception of the first
// character. For example: "ZomgCamelCase" -> "zomg_camel_case".
func initialCapsToUnderscores(name string) string {
	if len(name) == 0 {
		// The C++ original indexes name[0] unconditionally, reading the
		// terminating NUL of an empty std::string.
		return "\x00"
	}
	var b strings.Builder
	b.WriteByte(lowerByte(name[0]))
	for i := 1; i < len(name); i++ {
		c := name[i]
		lc := lowerByte(c)
		if lc != c {
			b.WriteByte('_')
		}
		b.WriteByte(lc)
	}
	return b.String()
}

// underscoresToInitialCaps performs the reverse operation of
// initialCapsToUnderscores: "zomg_camel_case" -> "ZomgCamelCase".
func underscoresToInitialCaps(name string) string {
	var b strings.Builder
	uppercaseNext := true
	for i := 0; i < len(name); i++ {
		c := name[i]
		if c == '_' {
			uppercaseNext = true
		} else if uppercaseNext {
			b.WriteByte(upperByte(c))
			uppercaseNext = false
		} else {
			b.WriteByte(c)
		}
	}
	return b.String()
}

// ---- helper functions (t_c_glib_generator "HELPER FUNCTIONS" section) ----

// isComplexType returns true if ttype is not a primitive.
func (g *Generator) isComplexType(ttype sema.Type) bool {
	ttype = sema.TrueType(ttype)
	return ttype.IsContainer() || ttype.IsStruct() || ttype.IsXception()
}

func (g *Generator) isNumeric(ttype sema.Type) bool {
	return ttype.IsEnum() || (ttype.IsBaseType() && !ttype.IsString())
}

// containerCppName is t_container::has_cpp_name/get_cpp_name, reached
// through a type switch since the accessor is not on the Type interface.
func containerCppName(ttype sema.Type) (string, bool) {
	switch c := ttype.(type) {
	case *sema.Map:
		if c.HasCppName() {
			return c.CppName(), true
		}
	case *sema.List:
		if c.HasCppName() {
			return c.CppName(), true
		}
	case *sema.Set:
		if c.HasCppName() {
			return c.CppName(), true
		}
	}
	return "", false
}

// typeName maps a Thrift t_type to a C type.
func (g *Generator) typeName(ttype sema.Type, inTypedef, isConst bool) string {
	if ttype.IsBaseType() {
		bname := g.baseTypeName(ttype)
		if isConst {
			return "const " + bname
		}
		return bname
	}

	if ttype.IsContainer() {
		var cname string
		if cn, ok := containerCppName(ttype); ok {
			cname = cn
		} else if ttype.IsMap() {
			cname = "GHashTable"
		} else if ttype.IsSet() {
			// since a set requires unique elements, use a GHashTable, and
			// populate the keys and values with the same data, using keys for
			// the actual writes and reads.
			// TODO: discuss whether or not to implement TSet, THashSet or GHashSet
			cname = "GHashTable"
		} else if ttype.IsList() {
			etype := sema.TrueType(ttype.(*sema.List).ElemType())
			if etype.IsVoid() {
				emit.Throw("compiler error: list element type cannot be void")
			}
			// TODO: investigate other implementations besides GPtrArray
			if g.isNumeric(etype) {
				cname = "GArray"
			} else {
				cname = "GPtrArray"
			}
		}

		// Omit the dereference operator if we are aliasing this type within a
		// typedef, to allow the type to be used more naturally in client code;
		// otherwise, include it
		if !inTypedef {
			cname += " *"
		}

		if isConst {
			return "const " + cname
		}
		return cname
	}

	// check for a namespace
	var pname string
	if tprogram := ttype.Program(); tprogram != nil {
		pname = tprogram.Namespace("c_glib") + ttype.Name()
	} else {
		pname = ttype.Name()
	}

	if g.isComplexType(ttype) {
		pname += " *"
	}

	if isConst {
		return "const " + pname
	}
	return pname
}

// propertyTypeName maps a Thrift primitive to the type needed to hold its
// value when used as an object property.
//
// This method is needed because all integer properties of width less than
// 64 bits map to the same type, gint, as opposed to their width-specific
// type (gint8, gint16 or gint32).
func (g *Generator) propertyTypeName(ttype sema.Type, inTypedef, isConst bool) string {
	if ttype.IsBaseType() {
		bt := ttype.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeI8, sema.TypeI16, sema.TypeI32:
			if isConst {
				return "const gint"
			}
			return "gint"
		default:
			return g.typeName(ttype, inTypedef, isConst)
		}
	}
	return g.typeName(ttype, inTypedef, isConst)
}

// baseTypeName maps a Thrift primitive to a C primitive.
func (g *Generator) baseTypeName(t sema.Type) string {
	if t.IsEnum() {
		return g.typeName(t, false, false)
	}
	if !t.IsBaseType() {
		emit.Throw("Only base types are suppported.")
	}
	bt := t.(*sema.BaseType)
	switch bt.Base() {
	case sema.TypeVoid:
		return "void"
	case sema.TypeString:
		if bt.IsBinary() {
			return "GByteArray *"
		}
		return "gchar *"
	case sema.TypeBool:
		return "gboolean"
	case sema.TypeI8:
		return "gint8"
	case sema.TypeI16:
		return "gint16"
	case sema.TypeI32:
		return "gint32"
	case sema.TypeI64:
		return "gint64"
	case sema.TypeDouble:
		return "gdouble"
	default:
		emit.Throw("compiler error: no C base type name for base type %s", sema.BaseName(bt.Base()))
	}
	return ""
}

// typeToEnum returns a member of the ThriftType C enumeration in
// thrift_protocol.h for a Thrift type.
func (g *Generator) typeToEnum(t sema.Type) string {
	t = sema.TrueType(t)

	if t.IsBaseType() {
		bt := t.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeVoid:
			emit.Throw("NO T_VOID CONSTRUCT")
		case sema.TypeString:
			return "T_STRING"
		case sema.TypeBool:
			return "T_BOOL"
		case sema.TypeI8:
			return "T_BYTE"
		case sema.TypeI16:
			return "T_I16"
		case sema.TypeI32:
			return "T_I32"
		case sema.TypeI64:
			return "T_I64"
		case sema.TypeDouble:
			return "T_DOUBLE"
		}
	} else if t.IsEnum() {
		return "T_I32"
	} else if t.IsStruct() {
		return "T_STRUCT"
	} else if t.IsXception() {
		return "T_STRUCT"
	} else if t.IsMap() {
		return "T_MAP"
	} else if t.IsSet() {
		return "T_SET"
	} else if t.IsList() {
		return "T_LIST"
	}

	emit.Throw("INVALID TYPE IN type_to_enum: %s", t.Name())
	return ""
}

// constantLiteral returns a Thrift constant formatted as a literal for
// inclusion in C code.
func (g *Generator) constantLiteral(t sema.Type, value *sema.ConstValue) string {
	var render strings.Builder

	if t.IsBaseType() {
		bt := t.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeString:
			render.WriteString("\"" + value.String() + "\"")
		case sema.TypeBool:
			if value.Integer() != 0 {
				render.WriteString("TRUE")
			} else {
				render.WriteString("FALSE")
			}
		case sema.TypeI8, sema.TypeI16, sema.TypeI32, sema.TypeI64:
			render.WriteString(strconv.FormatInt(value.Integer(), 10))
		case sema.TypeDouble:
			render.WriteString(formatDouble(value.Double()))
		default:
			emit.Throw("compiler error: no const of base type %s", sema.BaseName(bt.Base()))
		}
	} else {
		switch value.Kind() {
		case sema.CVIdentifier, sema.CVInteger:
			render.WriteString(strconv.FormatInt(value.Integer(), 10))
		case sema.CVList:
			render.WriteString("{ ")
			elemType := t.(*sema.List).ElemType()
			list := value.List()
			for i, e := range list {
				if i == 0 {
					render.WriteString(g.constantLiteral(elemType, e))
				} else {
					render.WriteString(", " + g.constantLiteral(elemType, e))
				}
			}
			render.WriteString(" }")
		default:
			render.WriteString("NULL /* not supported */")
		}
	}

	return render.String()
}

// constantValue returns C code that represents a Thrift constant.
func (g *Generator) constantValue(name string, t sema.Type, value *sema.ConstValue) string {
	var render strings.Builder

	if t.IsBaseType() {
		bt := t.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeString:
			render.WriteString(`g_strdup ("` + value.String() + `")`)
		case sema.TypeBool:
			if value.Integer() != 0 {
				render.WriteString("1")
			} else {
				render.WriteString("0")
			}
		case sema.TypeI8, sema.TypeI16, sema.TypeI32:
			render.WriteString(strconv.FormatInt(value.Integer(), 10))
		case sema.TypeI64:
			render.WriteString("G_GINT64_CONSTANT (" + strconv.FormatInt(value.Integer(), 10) + ")")
		case sema.TypeDouble:
			if value.Kind() == sema.CVInteger {
				render.WriteString(strconv.FormatInt(value.Integer(), 10))
			} else {
				render.WriteString(formatDouble(value.Double()))
			}
		default:
			emit.Throw("compiler error: no const of base type %s", sema.BaseName(bt.Base()))
		}
	} else if t.IsEnum() {
		render.WriteString("(" + g.typeName(t, false, false) + ")" + strconv.FormatInt(value.Integer(), 10))
	} else if g.isComplexType(t) {
		render.WriteString("(" + g.nspaceLC + toLowerCase(name) + "_constant())")
	} else {
		render.WriteString("NULL /* not supported */")
	}

	return render.String()
}

// functionSignature is a lightweight stand-in for t_function, used only
// to build function signatures with functionSignature/argumentList/
// xceptionList the way the C++ generator constructs a throwaway
// t_function for the purpose.
type funcSig struct {
	returnType sema.Type
	name       string
	arglist    *sema.Struct
	xceptions  *sema.Struct
}

// newFuncSig3 is the two-argument (no xceptions) t_function constructor.
func newFuncSig3(returnType sema.Type, name string, arglist *sema.Struct) *funcSig {
	return &funcSig{returnType: returnType, name: name, arglist: arglist, xceptions: sema.NewStruct(nil)}
}

// newFuncSig is the t_function constructor that also takes xceptions.
func newFuncSig(returnType sema.Type, name string, arglist, xceptions *sema.Struct) *funcSig {
	return &funcSig{returnType: returnType, name: name, arglist: arglist, xceptions: xceptions}
}

// functionSignature renders a function signature of the form
// 'type name(args)'.
func (g *Generator) functionSignature(f *funcSig) string {
	fname := initialCapsToUnderscores(f.name)

	hasReturn := !f.returnType.IsVoid()
	noArgs := len(f.arglist.Members()) == 0
	noXceptions := len(f.xceptions.Members()) == 0

	s := "gboolean " + g.nspaceLC + fname + " (" + g.nspace + g.serviceName + "If * iface"
	if hasReturn {
		s += ", " + g.typeName(f.returnType, false, false) + "* _return"
	}
	if !noArgs {
		s += ", " + g.argumentList(f.arglist)
	}
	if !noXceptions {
		s += ", " + g.xceptionList(f.xceptions)
	}
	s += ", GError ** error)"
	return s
}

// argumentList renders a field list: a comma-separated list of all field
// names in the struct.
func (g *Generator) argumentList(s *sema.Struct) string {
	var parts []string
	for _, f := range s.Members() {
		parts = append(parts, g.typeName(f.Type(), false, true)+" "+f.Name())
	}
	return strings.Join(parts, ", ")
}

// xceptionList renders mutable exception lists.
func (g *Generator) xceptionList(s *sema.Struct) string {
	var parts []string
	for _, f := range s.Members() {
		parts = append(parts, g.typeName(f.Type(), false, false)+"* "+f.Name())
	}
	return strings.Join(parts, ", ")
}

// declareField declares a field, including any necessary initialization.
func (g *Generator) declareField(f *sema.Field, initField, pointer, constant, reference bool) string {
	result := ""
	if constant {
		result += "const "
	}
	result += g.typeName(f.Type(), false, false)
	if pointer {
		result += "*"
	}
	if reference {
		result += "*"
	}
	result += " " + f.Name()
	if initField {
		t := sema.TrueType(f.Type())

		if t.IsBaseType() {
			bt := t.(*sema.BaseType)
			switch bt.Base() {
			case sema.TypeVoid:
			case sema.TypeBool, sema.TypeI8, sema.TypeI16, sema.TypeI32, sema.TypeI64:
				result += " = 0"
			case sema.TypeDouble:
				result += " = (gdouble) 0"
			case sema.TypeString:
				result += " = NULL"
			default:
				emit.Throw("compiler error: no C intializer for base type %s", sema.BaseName(bt.Base()))
			}
		} else if t.IsEnum() {
			result += " = (" + g.typeName(t, false, false) + ") 0"
		} else if t.IsStruct() || t.IsContainer() {
			result += " = NULL"
		}
	}

	if !reference {
		result += ";"
	}

	return result
}

// constantValueWithStorage is constant_value_with_storage.
func (g *Generator) constantValueWithStorage(fname string, etype sema.Type, value *sema.ConstValue) string {
	var render strings.Builder
	if g.isNumeric(etype) {
		render.WriteString("    " + g.typeName(etype, false, false) + " *" + fname + " = " +
			"g_new (" + g.baseTypeName(etype) + ", 1);\n" +
			"    *" + fname + " = " + g.constantValue(fname, etype, value) + ";\n")
	} else {
		render.WriteString("    " + g.typeName(etype, false, false) + " " + fname + " = " +
			g.constantValue(fname, etype, value) + ";\n")
	}
	return render.String()
}

// declareLocalVariable is declare_local_variable.
func (g *Generator) declareLocalVariable(out *strings.Builder, ttype sema.Type, name string, forHashTable bool) {
	tname := g.typeName(ttype, false, false)

	// If the given type is a typedef, find its underlying type so we
	// can correctly determine how to generate a pointer to it
	ttype = sema.TrueType(ttype)
	ptr := ""
	if g.isNumeric(ttype) {
		ptr = "*"
	}

	if ttype.IsMap() {
		m := ttype.(*sema.Map)
		out.WriteString(g.indent() + tname + ptr + " " + name + " = " +
			g.generateNewHashFromType(m.KeyType(), m.ValType()) + "\n")
	} else if ttype.IsList() {
		l := ttype.(*sema.List)
		out.WriteString(g.indent() + tname + ptr + " " + name + " = " +
			g.generateNewArrayFromType(l.ElemType()) + "\n")
	} else if forHashTable && ttype.IsEnum() {
		out.WriteString(g.indent() + tname + " " + name + ";\n")
	} else {
		init := " = NULL"
		if ptr != "" {
			init = " = g_new (" + tname + ", 1)"
		}
		out.WriteString(g.indent() + tname + ptr + " " + name + init + ";\n")
	}
}

// declareLocalVariableForWrite is declore_local_variable_for_write (the
// C++ name is itself a typo).
func (g *Generator) declareLocalVariableForWrite(out *strings.Builder, ttype sema.Type, name string) {
	tname := g.typeName(ttype, false, false)
	ttype = sema.TrueType(ttype)
	ptr := "* "
	if ttype.IsString() || !ttype.IsBaseType() {
		ptr = " "
	}
	initVal := " = NULL"
	if ttype.IsEnum() {
		initVal = ""
	}
	out.WriteString(g.indent() + tname + ptr + name + initVal + ";\n")
}

// generateConstInitializer generates C code that initializes complex
// constants.
func (g *Generator) generateConstInitializer(name string, t sema.Type, value *sema.ConstValue, topLevel bool) {
	nameU := initialCapsToUnderscores(name)
	nameLC := toLowerCase(nameU)
	typeU := initialCapsToUnderscores(t.Name())
	typeUC := toUpperCase(typeU)
	maybeStatic := "static "
	if topLevel {
		maybeStatic = ""
	}

	switch {
	case t.IsStruct() || t.IsXception():
		st := t.(*sema.Struct)
		fields := st.Members()
		val := value.Map()
		var initializers strings.Builder

		// initialize any constants that may be referenced by this initializer
		for _, entry := range val {
			var fieldType sema.Type
			fieldName := ""
			for _, f := range fields {
				if f.Name() == entry.Key.String() {
					fieldType = f.Type()
					fieldName = f.Name()
					break
				}
			}
			if fieldType == nil {
				emit.Throw("type error: %s has no field %s", t.Name(), entry.Key.String())
			}
			fieldName = g.tmp(fieldName)

			g.generateConstInitializer(name+"_constant_"+fieldName, fieldType, entry.Value, false)
			initializers.WriteString("    constant->" + entry.Key.String() + " = " +
				g.constantValue(name+"_constant_"+fieldName, fieldType, entry.Value) + ";\n" +
				"    constant->__isset_" + entry.Key.String() + " = TRUE;\n")
		}

		// implement the initializer
		g.fTypesImpl.WriteString(maybeStatic + g.nspace + t.Name() + " *\n" +
			g.nspaceLC + nameLC + "_constant (void)\n")
		g.scopeUp(&g.fTypesImpl)
		g.fTypesImpl.WriteString(g.indent() + "static " + g.nspace + t.Name() + " *constant = NULL;\n" +
			g.indent() + "if (constant == NULL)\n")
		g.scopeUp(&g.fTypesImpl)
		g.fTypesImpl.WriteString(g.indent() + "constant = g_object_new (" + g.nspaceUC + "TYPE_" + typeUC + ", NULL);\n" +
			initializers.String())
		g.scopeDown(&g.fTypesImpl)

		// This loop matches the members up again but the result is unused in
		// the C++ generator; it is kept for parity of the tmp() counter.
		for _, entry := range val {
			var fieldType sema.Type
			fieldName := ""
			for _, f := range fields {
				if f.Name() == entry.Key.String() {
					fieldType = f.Type()
					fieldName = f.Name()
					break
				}
			}
			if fieldType == nil {
				emit.Throw("type error: %s has no field %s", t.Name(), entry.Key.String())
			}
			_ = g.tmp(fieldName)
		}

		g.fTypesImpl.WriteString(g.indent() + "return constant;\n")
		g.scopeDown(&g.fTypesImpl)
		g.fTypesImpl.WriteString("\n")
	case t.IsList():
		listType := "GPtrArray *"
		etype := t.(*sema.List).ElemType()
		// generate_free_func_from_type is called here in the C++ source for
		// its side effect (it throws for a void element type) even though
		// list_initializer is unconditionally overwritten immediately below.
		_ = g.generateFreeFuncFromType(etype)
		listAppender := "g_ptr_array_add"
		listVariable := false

		val := value.List()
		var initializers strings.Builder
		var appenders strings.Builder

		listInitializer := g.generateNewArrayFromType(etype)
		if etype.IsBaseType() {
			bt := etype.(*sema.BaseType)
			switch bt.Base() {
			case sema.TypeVoid:
				emit.Throw("compiler error: cannot determine array type")
			case sema.TypeBool, sema.TypeI8, sema.TypeI16, sema.TypeI32, sema.TypeI64, sema.TypeDouble:
				listType = "GArray *"
				listAppender = "g_array_append_val"
				listVariable = true
			case sema.TypeString:
			default:
				emit.Throw("compiler error: no array info for type")
			}
		} else if etype.IsEnum() {
			listType = "GArray *"
			listAppender = "g_array_append_val"
			listVariable = true
		}

		for _, v := range val {
			fname := g.tmp(name)

			g.generateConstInitializer(fname, etype, v, false)
			if listVariable {
				initializers.WriteString("    " + g.typeName(etype, false, false) + " " + fname + " = " +
					g.constantValue(fname, etype, v) + ";\n")
				appenders.WriteString("    " + listAppender + "(constant, " + fname + ");\n")
			} else {
				appenders.WriteString("    " + listAppender + "(constant, " + g.constantValue(fname, etype, v) + ");\n")
			}
		}

		g.fTypesImpl.WriteString(maybeStatic + listType + "\n" +
			g.nspaceLC + nameLC + "_constant (void)\n")
		g.scopeUp(&g.fTypesImpl)
		g.fTypesImpl.WriteString(g.indent() + "static " + listType + " constant = NULL;\n" +
			g.indent() + "if (constant == NULL)\n")
		g.scopeUp(&g.fTypesImpl)
		if initializers.Len() != 0 {
			g.fTypesImpl.WriteString(initializers.String() + "\n")
		}
		g.fTypesImpl.WriteString(g.indent() + "constant = " + listInitializer + "\n" + appenders.String())
		g.scopeDown(&g.fTypesImpl)
		g.fTypesImpl.WriteString(g.indent() + "return constant;\n")
		g.scopeDown(&g.fTypesImpl)
		g.fTypesImpl.WriteString("\n")
	case t.IsSet():
		etype := t.(*sema.Set).ElemType()
		val := value.List()
		var initializers strings.Builder
		var appenders strings.Builder

		for _, v := range val {
			fname := g.tmp(name)
			g.generateConstInitializer(fname, etype, v, false)
			initializers.WriteString(g.constantValueWithStorage(fname, etype, v))
			appenders.WriteString("    g_hash_table_insert (constant, " + fname + ", 0);\n")
		}

		g.fTypesImpl.WriteString(maybeStatic + "GHashTable *\n" +
			g.nspaceLC + nameLC + "_constant (void)\n")
		g.scopeUp(&g.fTypesImpl)
		g.fTypesImpl.WriteString(g.indent() + "static GHashTable *constant = NULL;\n" +
			g.indent() + "if (constant == NULL)\n")
		g.scopeUp(&g.fTypesImpl)
		g.fTypesImpl.WriteString(initializers.String() + "\n" +
			g.indent() + "constant = " + g.generateNewHashFromType(etype, nil) + "\n" + appenders.String())
		g.scopeDown(&g.fTypesImpl)
		g.fTypesImpl.WriteString(g.indent() + "return constant;\n")
		g.scopeDown(&g.fTypesImpl)
		g.fTypesImpl.WriteString("\n")
	case t.IsMap():
		m := t.(*sema.Map)
		ktype, vtype := m.KeyType(), m.ValType()
		val := value.Map()
		var initializers strings.Builder
		var appenders strings.Builder

		for _, entry := range val {
			fname := g.tmp(name)
			kname := fname + "key"
			vname := fname + "val"
			g.generateConstInitializer(kname, ktype, entry.Key, false)
			g.generateConstInitializer(vname, vtype, entry.Value, false)

			initializers.WriteString(g.constantValueWithStorage(kname, ktype, entry.Key))
			initializers.WriteString(g.constantValueWithStorage(vname, vtype, entry.Value))
			appenders.WriteString("    g_hash_table_insert (constant, " + kname + ", " + vname + ");\n")
		}

		g.fTypesImpl.WriteString(maybeStatic + "GHashTable *\n" +
			g.nspaceLC + nameLC + "_constant (void)\n")
		g.scopeUp(&g.fTypesImpl)
		g.fTypesImpl.WriteString(g.indent() + "static GHashTable *constant = NULL;\n" +
			g.indent() + "if (constant == NULL)\n")
		g.scopeUp(&g.fTypesImpl)
		g.fTypesImpl.WriteString(initializers.String() + "\n" +
			g.indent() + "constant = " + g.generateNewHashFromType(ktype, vtype) + "\n" + appenders.String())
		g.scopeDown(&g.fTypesImpl)
		g.fTypesImpl.WriteString(g.indent() + "return constant;\n")
		g.scopeDown(&g.fTypesImpl)
		g.fTypesImpl.WriteString("\n")
	}
}

// generateFreeFuncFromType is generate_free_func_from_type. ttype may be
// nil, matching a nullptr argument in the C++ source.
func (g *Generator) generateFreeFuncFromType(ttype sema.Type) string {
	if ttype == nil {
		return "NULL"
	}

	if ttype.IsBaseType() {
		bt := ttype.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeVoid:
			emit.Throw("compiler error: cannot determine hash type")
		case sema.TypeBool, sema.TypeI8, sema.TypeI16, sema.TypeI32, sema.TypeI64, sema.TypeDouble:
			return "g_free"
		case sema.TypeString:
			if bt.IsBinary() {
				return "thrift_string_free"
			}
			return "g_free"
		default:
			emit.Throw("compiler error: no hash table info for type")
		}
	} else if ttype.IsEnum() {
		return "NULL"
	} else if ttype.IsMap() || ttype.IsSet() {
		return "(GDestroyNotify) thrift_safe_hash_table_destroy"
	} else if ttype.IsStruct() {
		return "g_object_unref"
	} else if ttype.IsList() {
		etype := ttype.(*sema.List).ElemType()
		if etype.IsBaseType() {
			bt := etype.(*sema.BaseType)
			switch bt.Base() {
			case sema.TypeVoid:
				emit.Throw("compiler error: cannot determine array type")
			case sema.TypeBool, sema.TypeI8, sema.TypeI16, sema.TypeI32, sema.TypeI64, sema.TypeDouble:
				return "(GDestroyNotify) g_array_unref"
			case sema.TypeString:
				return "(GDestroyNotify) g_ptr_array_unref"
			default:
				emit.Throw("compiler error: no array info for type")
			}
		} else if etype.IsContainer() || etype.IsStruct() {
			return "(GDestroyNotify) g_ptr_array_unref"
		} else if etype.IsEnum() {
			return "(GDestroyNotify) g_array_unref"
		}
		emit.Throw("Type not expected inside array")
	} else if ttype.IsTypedef() {
		return g.generateFreeFuncFromType(ttype.(*sema.Typedef).Type())
	}
	emit.Throw("Type not expected")
	return ""
}

// generateHashFuncFromType is generate_hash_func_from_type.
func (g *Generator) generateHashFuncFromType(ttype sema.Type) string {
	if ttype == nil {
		return "NULL"
	}

	if ttype.IsBaseType() {
		bt := ttype.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeVoid:
			emit.Throw("compiler error: cannot determine hash type")
		case sema.TypeBool:
			return "thrift_boolean_hash"
		case sema.TypeI8:
			return "thrift_int8_hash"
		case sema.TypeI16:
			return "thrift_int16_hash"
		case sema.TypeI32:
			return "g_int_hash"
		case sema.TypeI64:
			return "g_int64_hash"
		case sema.TypeDouble:
			return "g_double_hash"
		case sema.TypeString:
			return "g_str_hash"
		default:
			emit.Throw("compiler error: no hash table info for type")
		}
	} else if ttype.IsEnum() {
		return "g_direct_hash"
	} else if ttype.IsContainer() || ttype.IsStruct() {
		return "g_direct_hash"
	} else if ttype.IsTypedef() {
		return g.generateHashFuncFromType(ttype.(*sema.Typedef).Type())
	}
	emit.Throw("Type not expected")
	return ""
}

// generateCmpFuncFromType is generate_cmp_func_from_type.
func (g *Generator) generateCmpFuncFromType(ttype sema.Type) string {
	if ttype == nil {
		return "NULL"
	}

	if ttype.IsBaseType() {
		bt := ttype.(*sema.BaseType)
		switch bt.Base() {
		case sema.TypeVoid:
			emit.Throw("compiler error: cannot determine hash type")
		case sema.TypeBool:
			return "thrift_boolean_equal"
		case sema.TypeI8:
			return "thrift_int8_equal"
		case sema.TypeI16:
			return "thrift_int16_equal"
		case sema.TypeI32:
			return "g_int_equal"
		case sema.TypeI64:
			return "g_int64_equal"
		case sema.TypeDouble:
			return "g_double_equal"
		case sema.TypeString:
			return "g_str_equal"
		default:
			emit.Throw("compiler error: no hash table info for type")
		}
	} else if ttype.IsEnum() {
		return "g_direct_equal"
	} else if ttype.IsContainer() || ttype.IsStruct() {
		return "g_direct_equal"
	} else if ttype.IsTypedef() {
		return g.generateCmpFuncFromType(ttype.(*sema.Typedef).Type())
	}
	emit.Throw("Type not expected")
	return ""
}

// generateNewHashFromType is generate_new_hash_from_type. value may be
// nil, matching a nullptr argument in the C++ source.
func (g *Generator) generateNewHashFromType(key, value sema.Type) string {
	hashFunc := g.generateHashFuncFromType(key)
	cmpFunc := g.generateCmpFuncFromType(key)
	keyFreeFunc := g.generateFreeFuncFromType(key)
	valueFreeFunc := g.generateFreeFuncFromType(value)

	return "g_hash_table_new_full (" + hashFunc + ", " + cmpFunc + ", " + keyFreeFunc + ", " + valueFreeFunc + ");"
}

// generateNewArrayFromType is generate_new_array_from_type.
func (g *Generator) generateNewArrayFromType(ttype sema.Type) string {
	if ttype.IsVoid() {
		emit.Throw("compiler error: cannot determine array type")
	}
	if g.isNumeric(ttype) {
		return "g_array_new (0, 1, sizeof (" + g.baseTypeName(ttype) + "));"
	}
	freeFunc := g.generateFreeFuncFromType(ttype)
	return "g_ptr_array_new_with_free_func (" + freeFunc + ");"
}
