/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package haxe

import (
	"strconv"
	"strings"

	"github.com/apache/thrift/compiler/go/generate/internal/emit"
	"github.com/apache/thrift/compiler/go/internal/version"
	"github.com/apache/thrift/compiler/go/sema"
)

// generator is t_haxe_generator for one program.
type generator struct {
	program *sema.Program
	opts    Options

	programName string
	serviceName string

	tmpCounter int
	level      int // indent_

	packageName string
	packageDir  string

	// fService is f_service_: the member ofstream generate_service_*
	// writes to without an explicit out parameter, exactly like the C++
	// class field.
	fService *strings.Builder
}

func newGenerator(program *sema.Program, opts Options) *generator {
	return &generator{program: program, opts: opts, programName: program.Name()}
}

// generate is t_generator::generate_program restricted to what
// t_haxe_generator overrides.
func (g *generator) generate() (err error) {
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(*emit.Error); ok {
				err = e
				return
			}
			panic(r)
		}
	}()
	g.initGenerator()
	for _, e := range g.program.Enums() {
		g.generateEnum(e)
	}
	for _, t := range g.program.Typedefs() {
		g.generateTypedef(t)
	}
	for _, s := range g.program.Objects() {
		if s.IsXception() {
			g.generateXception(s)
		} else {
			g.generateStruct(s)
		}
	}
	g.generateConsts(g.program.Consts())
	for _, s := range g.program.Services() {
		g.serviceName = s.Name()
		g.generateService(s)
	}
	g.closeGenerator()
	return nil
}

func (g *generator) closeGenerator() {
	// Nothing in haxe.
}

// ---- indent-tracked writer ----

// indent is indent(): two spaces per level (t_generator::indent_str).
func (g *generator) indent() string {
	return strings.Repeat("  ", g.level)
}

func (g *generator) indentUp()   { g.level++ }
func (g *generator) indentDown() { g.level-- }

// line is `indent(out) << s << '\n'`.
func (g *generator) line(out *strings.Builder, s string) {
	out.WriteString(g.indent())
	out.WriteString(s)
	out.WriteString("\n")
}

// indentRaw is `indent(out) << s`, with no trailing newline, for call
// sites that keep writing to the same line afterwards.
func (g *generator) indentRaw(out *strings.Builder, s string) {
	out.WriteString(g.indent())
	out.WriteString(s)
}

// scopeUp is t_oop_generator::scope_up.
func (g *generator) scopeUp(out *strings.Builder) {
	g.line(out, "{")
	g.indentUp()
}

// scopeDown is t_oop_generator::scope_down.
func (g *generator) scopeDown(out *strings.Builder) {
	g.indentDown()
	g.line(out, "}")
}

// tmp is t_generator::tmp: a name with a running number appended.
func (g *generator) tmp(name string) string {
	s := name + strconv.Itoa(g.tmpCounter)
	g.tmpCounter++
	return s
}

// upcaseString is t_oop_generator::upcase_string.
func upcaseString(in string) string { return strings.ToUpper(in) }

func isUpper(c byte) bool { return c >= 'A' && c <= 'Z' }
func isLower(c byte) bool { return c >= 'a' && c <= 'z' }
func toUpperByte(c byte) byte {
	if isLower(c) {
		return c - 'a' + 'A'
	}
	return c
}
func toLowerByte(c byte) byte {
	if isUpper(c) {
		return c - 'A' + 'a'
	}
	return c
}

// formatDouble mimics `ostream << double` with the default precision of
// six significant digits, as used by render_const_value's TYPE_DOUBLE case
// (no setprecision call is in effect there).
func formatDouble(f float64) string {
	return strconv.FormatFloat(f, 'g', 6, 64)
}

// itoa32 formats a 32-bit signed integer, like `ostream << int32_t`.
func itoa32(v int32) string {
	return strconv.FormatInt(int64(v), 10)
}

// ---- files ----

// outDir is t_generator::get_out_dir with out_dir_base_ == "gen-haxe".
func (g *generator) outDir() string {
	if g.program.IsOutPathAbsolute() {
		return g.program.OutPath() + "/"
	}
	return g.program.OutPath() + "gen-haxe" + "/"
}

// autogenComment is the base t_generator::autogen_comment (not overridden
// by t_haxe_generator).
func (g *generator) autogenComment() string {
	return "/**\n" +
		" * Autogenerated by Thrift Compiler (" + version.Version + ")\n" +
		" *\n" +
		" * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n" +
		" *  @generated\n" +
		" */\n"
}

// initGenerator is t_haxe_generator::init_generator.
func (g *generator) initGenerator() {
	emit.Mkdir(g.outDir())
	g.packageName = makePackageName(g.program.Namespace("haxe"))

	dir := g.packageName
	subdir := g.outDir()
	for {
		loc := strings.IndexByte(dir, '.')
		if loc < 0 {
			break
		}
		subdir = subdir + "/" + dir[:loc]
		emit.Mkdir(subdir)
		dir = dir[loc+1:]
	}
	if len(dir) > 0 {
		subdir = subdir + "/" + dir
		emit.Mkdir(subdir)
	}

	g.packageDir = subdir
}

// makePackageName is t_haxe_generator::make_package_name: Haxe package
// names start with lowercase letters.
func makePackageName(value string) string {
	if len(value) == 0 {
		return value
	}
	b := []byte(value)
	b[0] = toLowerByte(b[0])
	for i := 0; i < len(b); i++ {
		if b[i] == '.' && i+1 < len(b) {
			b[i+1] = toLowerByte(b[i+1])
		}
	}
	return string(b)
}

// haxePackage is t_haxe_generator::haxe_package.
func (g *generator) haxePackage() string {
	if g.packageName != "" {
		return "package " + g.packageName
	}
	return "package"
}

// haxeTypeImports is t_haxe_generator::haxe_type_imports.
func (g *generator) haxeTypeImports() string {
	return "import org.apache.thrift.helper.*;\n" +
		"import haxe.io.Bytes;\n" +
		"import haxe.ds.IntMap;\n" +
		"import haxe.ds.StringMap;\n" +
		"import haxe.ds.ObjectMap;\n" +
		"import org.apache.thrift.helper.ObjectSet;\n" +
		"\n" +
		"#if flash\n" +
		"import flash.errors.ArgumentError;\n" +
		"#end\n" +
		"\n"
}

// haxeThriftImports is t_haxe_generator::haxe_thrift_imports.
func (g *generator) haxeThriftImports() string {
	return "import org.apache.thrift.*;\n" +
		"import org.apache.thrift.meta_data.*;\n" +
		"import org.apache.thrift.protocol.*;\n" +
		"\n"
}

// haxeThriftAddImport is t_haxe_generator::haxe_thrift_add_import. It uses
// ttyp (not its true type) for the program and name lookups, only the
// true type for the base-type skip check, exactly like the C++ code.
func (g *generator) haxeThriftAddImport(ttyp sema.Type, imports *strings.Builder, excludeShortName string) {
	trueType := sema.TrueType(ttyp)
	if trueType.IsBaseType() {
		return
	}
	program := ttyp.Program()
	if program != nil && program != g.program {
		pkg := makePackageName(program.Namespace("haxe"))
		if pkg != "" {
			shortName := g.makeHaxeUserTypeName(ttyp.Name())
			// Skip if the short name matches the entity being defined — the
			// local definition takes precedence and an import of a
			// same-named foreign type would shadow it (THRIFT-5320).
			if excludeShortName != "" && shortName == excludeShortName {
				return
			}
			// Skip if a same-named type is already imported — two imports
			// with the same short name produce an unresolvable ambiguity
			// in Haxe.
			if strings.Contains(imports.String(), "."+shortName+";\n") {
				return
			}
			if !strings.Contains(imports.String(), pkg+"."+ttyp.Name()) {
				imports.WriteString("import " + pkg + "." + shortName + ";\n")
			}
		}
	}
}

// haxeThriftGenImportsStruct is the t_struct overload of
// t_haxe_generator::haxe_thrift_gen_imports.
func (g *generator) haxeThriftGenImportsStruct(tstruct *sema.Struct, imports *strings.Builder, excludeShortName string) {
	for _, m := range tstruct.Members() {
		g.haxeThriftAddImport(m.Type(), imports, excludeShortName)
	}
}

// haxeThriftGenImportsServiceInto is the t_service overload of
// t_haxe_generator::haxe_thrift_gen_imports.
func (g *generator) haxeThriftGenImportsServiceInto(tservice *sema.Service, imports *strings.Builder) {
	// Exclude same-named foreign types to prevent them from shadowing the
	// local service definition.
	exclude := g.makeHaxeUserTypeName(tservice.Name())

	for _, f := range tservice.Functions() {
		g.haxeThriftAddImport(f.ReturnType(), imports, exclude)

		// args and exceptions structs
		g.haxeThriftGenImportsStruct(f.Arglist(), imports, exclude)
		g.haxeThriftGenImportsStruct(f.Xceptions(), imports, exclude)
	}

	// service implements / extends
	g.haxeThriftAddImport(tservice, imports, exclude)
	if tservice.Extends() != nil {
		g.haxeThriftGenImportsServiceInto(tservice.Extends(), imports)
	}
}

// haxeThriftGenImportsService is the string-returning t_service overload
// of t_haxe_generator::haxe_thrift_gen_imports.
func (g *generator) haxeThriftGenImportsService(tservice *sema.Service) string {
	var imports strings.Builder
	g.haxeThriftGenImportsServiceInto(tservice, &imports)
	return imports.String()
}

// typeCanBeNull is t_haxe_generator::type_can_be_null.
func typeCanBeNull(ttype sema.Type) bool {
	ttype = sema.TrueType(ttype)

	if ttype.IsContainer() || ttype.IsStruct() || ttype.IsXception() || ttype.IsString() {
		return true
	}

	if ttype.IsBaseType() {
		switch ttype.(*sema.BaseType).Base() {
		case sema.TypeString:
			// case sema.TypeI64: Int64 is not really nullable, even though
			// it behaved that way before Haxe 3.2.0
			return true
		default:
			return false
		}
	}

	return false
}

// typeName is t_haxe_generator::type_name.
func (g *generator) typeName(ttype sema.Type) string {
	ttype = sema.TrueType(ttype)

	if ttype.IsBaseType() {
		return g.baseTypeName(ttype.(*sema.BaseType))
	}

	if ttype.IsEnum() {
		return "Int"
	}

	if ttype.IsMap() {
		m := ttype.(*sema.Map)
		tkey := sema.TrueType(m.KeyType())
		tval := m.ValType()
		if tkey.IsBaseType() {
			switch tkey.(*sema.BaseType).Base() {
			case sema.TypeString:
				if !tkey.IsBinary() {
					return "StringMap< " + g.typeName(tval) + ">"
				}
				return "BytesMap< " + g.typeName(tval) + ">" // content equality, not reference equality
			case sema.TypeUUID:
				return "StringMap< " + g.typeName(tval) + ">" // uuids are stored as strings
			case sema.TypeBool:
				return "BoolMap< " + g.typeName(tval) + ">"
			case sema.TypeDouble:
				return "FloatMap< " + g.typeName(tval) + ">"
			case sema.TypeI8, sema.TypeI16, sema.TypeI32:
				return "IntMap< " + g.typeName(tval) + ">"
			case sema.TypeI64:
				return "Int64Map< " + g.typeName(tval) + ">"
			default:
				// default to ObjectMap<>
			}
		}
		if tkey.IsEnum() {
			return "IntMap< " + g.typeName(tval) + ">"
		}
		return "ObjectMap< " + g.typeName(tkey) + ", " + g.typeName(tval) + ">"
	}

	if ttype.IsSet() {
		s := ttype.(*sema.Set)
		tkey := sema.TrueType(s.ElemType())
		if tkey.IsBaseType() {
			switch tkey.(*sema.BaseType).Base() {
			case sema.TypeString:
				if !tkey.IsBinary() {
					return "StringSet"
				}
				return "BytesSet" // content equality, not reference equality
			case sema.TypeUUID:
				return "StringSet" // uuids are stored as strings
			case sema.TypeBool:
				return "BoolSet"
			case sema.TypeDouble:
				return "FloatSet"
			case sema.TypeI8, sema.TypeI16, sema.TypeI32:
				return "IntSet"
			case sema.TypeI64:
				return "Int64Set"
			default:
				// default to ObjectSet
			}
		}
		if tkey.IsEnum() {
			return "IntSet"
		}
		return "ObjectSet< " + g.typeName(tkey) + ">"
	}

	if ttype.IsList() {
		l := ttype.(*sema.List)
		return "List< " + g.typeName(l.ElemType()) + ">"
	}

	// Check for namespacing
	program := ttype.Program()
	if program != nil && program != g.program {
		pkg := makePackageName(program.Namespace("haxe"))
		if pkg != "" {
			return pkg + "." + g.makeHaxeUserTypeName(ttype.Name())
		}
	}

	return g.makeHaxeUserTypeName(ttype.Name())
}

// baseTypeName is t_haxe_generator::base_type_name.
func (g *generator) baseTypeName(t *sema.BaseType) string {
	switch t.Base() {
	case sema.TypeVoid:
		return "Void"
	case sema.TypeString:
		if t.IsBinary() {
			return "haxe.io.Bytes"
		}
		return "String"
	case sema.TypeUUID:
		return "String"
	case sema.TypeBool:
		return "Bool"
	case sema.TypeI8, sema.TypeI16, sema.TypeI32:
		return "haxe.Int32"
	case sema.TypeI64:
		return "haxe.Int64"
	case sema.TypeDouble:
		return "Float"
	default:
		emit.Throw("compiler error: no Haxe name for base type %s", sema.BaseName(t.Base()))
		return ""
	}
}

// typeToEnum is t_haxe_generator::type_to_enum.
func (g *generator) typeToEnum(t sema.Type) string {
	t = sema.TrueType(t)

	if t.IsBaseType() {
		switch t.(*sema.BaseType).Base() {
		case sema.TypeVoid:
			emit.Throw("NO T_VOID CONSTRUCT")
		case sema.TypeString:
			return "TType.STRING"
		case sema.TypeUUID:
			return "TType.UUID"
		case sema.TypeBool:
			return "TType.BOOL"
		case sema.TypeI8:
			return "TType.BYTE"
		case sema.TypeI16:
			return "TType.I16"
		case sema.TypeI32:
			return "TType.I32"
		case sema.TypeI64:
			return "TType.I64"
		case sema.TypeDouble:
			return "TType.DOUBLE"
		}
	} else if t.IsEnum() {
		return "TType.I32"
	} else if t.IsStruct() || t.IsXception() {
		return "TType.STRUCT"
	} else if t.IsMap() {
		return "TType.MAP"
	} else if t.IsSet() {
		return "TType.SET"
	} else if t.IsList() {
		return "TType.LIST"
	}

	emit.Throw("INVALID TYPE IN type_to_enum: %s", t.Name())
	return ""
}

// getHaxeTypeString is t_haxe_generator::get_haxe_type_string.
func (g *generator) getHaxeTypeString(t sema.Type) string {
	switch {
	case t.IsList():
		return "TType.LIST"
	case t.IsMap():
		return "TType.MAP"
	case t.IsSet():
		return "TType.SET"
	case t.IsStruct() || t.IsXception():
		return "TType.STRUCT"
	case t.IsEnum():
		return "TType.I32"
	case t.IsTypedef():
		return g.getHaxeTypeString(t.(*sema.Typedef).Type())
	case t.IsBaseType():
		switch t.(*sema.BaseType).Base() {
		case sema.TypeVoid:
			return "TType.VOID_"
		case sema.TypeString:
			return "TType.STRING"
		case sema.TypeUUID:
			return "TType.UUID"
		case sema.TypeBool:
			return "TType.BOOL"
		case sema.TypeI8:
			return "TType.BYTE"
		case sema.TypeI16:
			return "TType.I16"
		case sema.TypeI32:
			return "TType.I32"
		case sema.TypeI64:
			return "TType.I64"
		case sema.TypeDouble:
			return "TType.DOUBLE"
		default:
			emit.Throw("Unknown thrift type \"%s\" passed to t_haxe_generator::get_haxe_type_string!", t.Name())
		}
	default:
		emit.Throw("Unknown thrift type \"%s\" passed to t_haxe_generator::get_haxe_type_string!", t.Name())
	}
	return ""
}

// getEnumClassName is t_haxe_generator::get_enum_class_name (the override
// of t_oop_generator::get_enum_class_name).
func (g *generator) getEnumClassName(t sema.Type) string {
	pkg := ""
	program := t.Program()
	if program != nil {
		pkg = makePackageName(program.Namespace("haxe")) + "."
	}
	return pkg + t.Name()
}

// escapeHaxeKeyword is t_haxe_generator::escape_haxe_keyword: appends a
// "_" suffix to any Haxe language keyword used as an identifier,
// preserving the original name in wire-format string literals.
func escapeHaxeKeyword(name string) string {
	if haxeKeywords[name] {
		return name + "_"
	}
	return name
}

var haxeKeywords = map[string]bool{
	"abstract": true, "break": true, "case": true, "cast": true, "catch": true, "class": true, "continue": true, "default": true,
	"do": true, "dynamic": true, "else": true, "enum": true, "extends": true, "extern": true, "false": true, "final": true,
	"for": true, "function": true, "if": true, "implements": true, "import": true, "in": true, "inline": true, "interface": true,
	"macro": true, "new": true, "null": true, "operator": true, "overload": true, "override": true, "package": true,
	"private": true, "public": true, "return": true, "static": true, "switch": true, "this": true, "throw": true, "true": true,
	"try": true, "typedef": true, "untyped": true, "using": true, "var": true, "while": true,
}

// getCapName is t_haxe_generator::get_cap_name.
func getCapName(name string) string {
	if len(name) == 0 {
		return name
	}

	// test.for.Generic< data.Type, or.the.Like> and handle it recursively
	genericFirst := strings.IndexByte(name, '<')
	genericLast := strings.LastIndexByte(name, '>')
	if genericFirst >= 0 && genericLast >= 0 {
		outerType := name[:genericFirst]
		innerTypes := name[genericFirst+1 : genericLast]

		newInner := ""
		commaStart := 0
		for commaStart < len(innerTypes) {
			commaPos := commaStart
			nested := 0
			for commaPos < len(innerTypes) {
				found := false
				switch innerTypes[commaPos] {
				case '<':
					nested++
				case '>':
					nested--
				case ',':
					found = nested == 0
				}
				if found {
					break
				}
				commaPos++
			}

			if len(newInner) > 0 {
				newInner += ","
			}

			inner := innerTypes[commaStart:commaPos]
			newInner += getCapName(inner)
			commaStart = commaPos + 1
		}

		return getCapName(outerType) + "<" + newInner + ">"
	}

	b := []byte(name)

	// package name
	index := indexNotOf(b, " \n\r\t")
	if index >= 0 && index < len(b) {
		b[index] = toLowerByte(b[index])
		idx := indexByteFrom(b, '.', 0)
		for idx >= 0 {
			idx++
			if idx < len(b) {
				b[idx] = toLowerByte(b[idx])
			}
			idx = indexByteFrom(b, '.', idx)
		}
	}

	// class name
	var classIndex int
	if dot := lastIndexByte(b, '.'); dot >= 0 {
		classIndex = dot + 1
	} else {
		ni := indexNotOf(b, " \n\r\t")
		if ni < 0 {
			classIndex = len(b)
		} else {
			classIndex = ni
		}
	}

	if classIndex < len(b) {
		b[classIndex] = toUpperByte(b[classIndex])
	}

	name = string(b)

	// Avoid clashing with Haxe built-in and standard-library type names.
	// Only list names that are never returned by type_name() for Thrift
	// base types, so that base-type annotations (Bool, Int, Float, String,
	// Void) are unaffected.
	dot := strings.LastIndexByte(name, '.')
	lastComponent := name
	if dot >= 0 {
		lastComponent = name[dot+1:]
	}
	if haxeReservedTypes[lastComponent] {
		name += "_"
	}

	return name
}

var haxeReservedTypes = map[string]bool{
	"Array": true, "Class": true, "Date": true, "DateTools": true, "Dynamic": true, "Enum": true, "EnumValue": true, "EReg": true,
	"IntIterator": true, "Iterable": true, "Iterator": true, "KeyValueIterable": true, "KeyValueIterator": true,
	"Lambda": true, "Map": true, "Math": true, "Null": true, "Reflect": true, "Single": true, "Std": true, "StringBuf": true,
	"Sys": true, "Type": true, "UInt": true, "Xml": true,
}

// haxeBaseTypeNames is the HAXE_BASE_TYPE_NAMES set of
// t_haxe_generator::make_haxe_user_type_name.
var haxeBaseTypeNames = map[string]bool{
	"String": true, "Bool": true, "Float": true, "Int": true, "Void": true,
}

// makeHaxeUserTypeName is t_haxe_generator::make_haxe_user_type_name: like
// getCapName but also renames user-defined types whose capitalized name
// would shadow a Haxe base type (String, Bool, Float, Int, Void). Must NOT
// be used for base-type annotations — only for user-defined
// struct/enum/service identifiers (file names, class headers, imports).
func (g *generator) makeHaxeUserTypeName(name string) string {
	result := getCapName(name)
	dot := strings.LastIndexByte(result, '.')
	lastComponent := result
	if dot >= 0 {
		lastComponent = result[dot+1:]
	}
	if haxeBaseTypeNames[lastComponent] {
		result += "_"
	}
	return result
}

// constantName is t_haxe_generator::constant_name.
func constantName(name string) string {
	var sb strings.Builder
	isFirst := true
	wasPreviousCharUpper := false
	for i := 0; i < len(name); i++ {
		c := name[i]
		up := isUpper(c)
		if up && !isFirst && !wasPreviousCharUpper {
			sb.WriteByte('_')
		}
		sb.WriteByte(toUpperByte(c))
		isFirst = false
		wasPreviousCharUpper = up
	}
	return sb.String()
}

// indexNotOf returns the index of the first byte in b that is not in cutset,
// or -1, like std::string::find_first_not_of.
func indexNotOf(b []byte, cutset string) int {
	for i, c := range b {
		if strings.IndexByte(cutset, c) < 0 {
			return i
		}
	}
	return -1
}

func indexByteFrom(b []byte, c byte, from int) int {
	if from < 0 || from > len(b) {
		return -1
	}
	for i := from; i < len(b); i++ {
		if b[i] == c {
			return i
		}
	}
	return -1
}

func lastIndexByte(b []byte, c byte) int {
	for i := len(b) - 1; i >= 0; i-- {
		if b[i] == c {
			return i
		}
	}
	return -1
}

// generateRttiDecoration is t_haxe_generator::generate_rtti_decoration.
func (g *generator) generateRttiDecoration(out *strings.Builder) {
	if g.opts.RTTI {
		out.WriteString("@:rtti\n")
	}
}

// generateMacroDecoration is t_haxe_generator::generate_macro_decoration.
func (g *generator) generateMacroDecoration(out *strings.Builder) {
	if g.opts.BuildMacro != "" {
		out.WriteString("#if ! macro\n")
		out.WriteString("@:build( " + g.opts.BuildMacro + ")\n")     // current class/interface
		out.WriteString("@:autoBuild( " + g.opts.BuildMacro + ")\n") // inherited classes/interfaces
		out.WriteString("#end\n")
	}
}

// docer is the doc-comment interface every commented IDL element
// satisfies (t_doc).
type docer interface {
	HasDoc() bool
	Doc() string
}

// generateHaxeDoc is the t_doc overload of t_haxe_generator::generate_haxe_doc.
func (g *generator) generateHaxeDoc(out *strings.Builder, tdoc docer) {
	if tdoc.HasDoc() {
		emit.DocstringComment(out, g.indent(), "/**\n", " * ", tdoc.Doc(), " */\n")
	}
}

// generateHaxeFunctionDoc is the t_function overload of
// t_haxe_generator::generate_haxe_doc.
func (g *generator) generateHaxeFunctionDoc(out *strings.Builder, tfunction *sema.Function) {
	if tfunction.HasDoc() {
		var ss strings.Builder
		ss.WriteString(tfunction.Doc())
		for _, p := range tfunction.Arglist().Members() {
			ss.WriteString("\n@param " + p.Name())
			if p.HasDoc() {
				ss.WriteString(" " + p.Doc())
			}
		}
		emit.DocstringComment(out, g.indent(), "/**\n", " * ", ss.String(), " */\n")
	}
}

// generateIssetCheckField is the t_field overload of
// t_haxe_generator::generate_isset_check.
func generateIssetCheckField(field *sema.Field) string {
	return generateIssetCheckName(escapeHaxeKeyword(field.Name()))
}

// generateIssetCheckName is the string overload of
// t_haxe_generator::generate_isset_check.
func generateIssetCheckName(fieldName string) string {
	return "is" + getCapName("set") + getCapName(fieldName) + "()"
}

// generateIssetSet is t_haxe_generator::generate_isset_set.
func (g *generator) generateIssetSet(out *strings.Builder, field *sema.Field) {
	if !typeCanBeNull(field.Type()) {
		g.line(out, "this.__isset_"+escapeHaxeKeyword(field.Name())+" = true;")
	}
}

// makeHaxeStringLiteral is t_haxe_generator::make_haxe_string_literal.
func makeHaxeStringLiteral(value string) string {
	if len(value) == 0 {
		return ""
	}

	var result strings.Builder
	result.WriteByte('"')
	for i := 0; i < len(value); i++ {
		c := value[i]
		switch {
		case c < 32:
			// convert ctrl chars, but leave UTF-8 alone; width = min(sizeof(signed char), 6) = 1
			result.WriteString("\\u{" + strconv.FormatInt(int64(c), 16) + "}")
		case c == '\\' || c == '"':
			result.WriteByte('\\')
			result.WriteByte(c)
		default:
			result.WriteByte(c)
		}
	}
	result.WriteByte('"')

	return result.String()
}

// generateDeprecationAttribute is t_haxe_generator::generate_deprecation_attribute.
func (g *generator) generateDeprecationAttribute(out *strings.Builder, fn *sema.Function, asComment bool) {
	values, ok := fn.Annotations()["deprecated"]
	if !ok {
		return
	}
	if asComment {
		out.WriteString(g.indent() + "// DEPRECATED")
	} else {
		out.WriteString(g.indent() + "@:deprecated")
	}

	// empty annotation values end up with "1" somewhere, ignore these as well
	last := ""
	if len(values) > 0 {
		last = values[len(values)-1]
	}
	if len(last) > 0 && last != "1" {
		text := makeHaxeStringLiteral(last)
		if asComment {
			out.WriteString(": " + text)
		} else {
			out.WriteString("(" + text + ")")
		}
	}

	out.WriteString("\n")
}
