// Code generated by Thrift Compiler (0.26.0). DO NOT EDIT.

package annotationtest

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"regexp"
	"strings"
	"time"

	thrift "github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO

// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

type Weekdays int64

const (
	Weekdays_SUNDAY    Weekdays = 0
	Weekdays_MONDAY    Weekdays = 1
	Weekdays_TUESDAY   Weekdays = 2
	Weekdays_WEDNESDAY Weekdays = 3
	Weekdays_THURSDAY  Weekdays = 4
	Weekdays_FRIDAY    Weekdays = 5
	Weekdays_SATURDAY  Weekdays = 6
)

var knownWeekdaysValues = []Weekdays{
	Weekdays_SUNDAY,
	Weekdays_MONDAY,
	Weekdays_TUESDAY,
	Weekdays_WEDNESDAY,
	Weekdays_THURSDAY,
	Weekdays_FRIDAY,
	Weekdays_SATURDAY,
}

func WeekdaysValues() iter.Seq[Weekdays] {
	return func(yield func(Weekdays) bool) {
		for _, v := range knownWeekdaysValues {
			if !yield(v) {
				return
			}
		}
	}
}
func (p Weekdays) String() string {
	switch p {
	case Weekdays_SUNDAY:
		return "SUNDAY"
	case Weekdays_MONDAY:
		return "MONDAY"
	case Weekdays_TUESDAY:
		return "TUESDAY"
	case Weekdays_WEDNESDAY:
		return "WEDNESDAY"
	case Weekdays_THURSDAY:
		return "THURSDAY"
	case Weekdays_FRIDAY:
		return "FRIDAY"
	case Weekdays_SATURDAY:
		return "SATURDAY"
	}
	return fmt.Sprintf("Weekdays(%d)", p)
}

func WeekdaysFromString(s string) (Weekdays, error) {
	switch s {
	case "SUNDAY":
		return Weekdays_SUNDAY, nil
	case "MONDAY":
		return Weekdays_MONDAY, nil
	case "TUESDAY":
		return Weekdays_TUESDAY, nil
	case "WEDNESDAY":
		return Weekdays_WEDNESDAY, nil
	case "THURSDAY":
		return Weekdays_THURSDAY, nil
	case "FRIDAY":
		return Weekdays_FRIDAY, nil
	case "SATURDAY":
		return Weekdays_SATURDAY, nil
	}
	return Weekdays(0), fmt.Errorf("not a valid Weekdays string")
}

func (p Weekdays) IsDefined() bool {
	switch p {
	case Weekdays_SUNDAY:
		return true
	case Weekdays_MONDAY:
		return true
	case Weekdays_TUESDAY:
		return true
	case Weekdays_WEDNESDAY:
		return true
	case Weekdays_THURSDAY:
		return true
	case Weekdays_FRIDAY:
		return true
	case Weekdays_SATURDAY:
		return true
	}
	return false
}

//go:fix inline
func WeekdaysPtr(v Weekdays) *Weekdays { return new(v) }

func (p Weekdays) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *Weekdays) UnmarshalText(text []byte) error {
	q, err := WeekdaysFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *Weekdays) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = Weekdays(v)
	return nil
}

func (p *Weekdays) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type IntLinkedList []int32

//go:fix inline
func IntLinkedListPtr(v IntLinkedList) *IntLinkedList { return new(v) }

type NonLatinString string

//go:fix inline
func NonLatinStringPtr(v NonLatinString) *NonLatinString { return new(v) }

type TinyFloatList []float64

//go:fix inline
func TinyFloatListPtr(v TinyFloatList) *TinyFloatList { return new(v) }

// Attributes:
//   - Bar
//   - Baz
//   - Qux
//   - Bop
type Foo struct {
	Bar int32 `thrift:"bar,1" db:"bar" json:"bar"`
	Baz int32 `thrift:"baz,2" db:"baz" json:"baz"`
	Qux int32 `thrift:"qux,3" db:"qux" json:"qux"`
	Bop int32 `thrift:"bop,4" db:"bop" json:"bop"`
}

func NewFoo() *Foo {
	return &Foo{}
}

func (p *Foo) GetBar() int32 {
	return p.Bar
}

func (p *Foo) GetBaz() int32 {
	return p.Baz
}

func (p *Foo) GetQux() int32 {
	return p.Qux
}

func (p *Foo) GetBop() int32 {
	return p.Bop
}

func (p *Foo) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Foo) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Bar = v
	}
	return nil
}

func (p *Foo) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Baz = v
	}
	return nil
}

func (p *Foo) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Qux = v
	}
	return nil
}

func (p *Foo) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.Bop = v
	}
	return nil
}

func (p *Foo) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "foo"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Foo) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "bar", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:bar: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Bar)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.bar (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:bar: ", p), err)
	}
	return err
}

func (p *Foo) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "baz", thrift.I32, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:baz: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Baz)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.baz (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:baz: ", p), err)
	}
	return err
}

func (p *Foo) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "qux", thrift.I32, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:qux: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Qux)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.qux (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:qux: ", p), err)
	}
	return err
}

func (p *Foo) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "bop", thrift.I32, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:bop: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Bop)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.bop (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:bop: ", p), err)
	}
	return err
}

func (p *Foo) Equals(other *Foo) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Bar != other.Bar {
		return false
	}
	if p.Baz != other.Baz {
		return false
	}
	if p.Qux != other.Qux {
		return false
	}
	if p.Bop != other.Bop {
		return false
	}
	return true
}

func (p *Foo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Foo(%+v)", *p)
}

func (p *Foo) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.Foo",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*Foo)(nil)

func (p *Foo) Validate() error {
	return nil
}

// Attributes:
//   - ErrorCode
//   - ErrorMsg
type FooError struct {
	ErrorCode int32  `thrift:"error_code,1" db:"error_code" json:"error_code"`
	ErrorMsg  string `thrift:"error_msg,2" db:"error_msg" json:"error_msg"`
}

func NewFooError() *FooError {
	return &FooError{}
}

func (p *FooError) GetErrorCode() int32 {
	return p.ErrorCode
}

func (p *FooError) GetErrorMsg() string {
	return p.ErrorMsg
}

func (p *FooError) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *FooError) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ErrorCode = v
	}
	return nil
}

func (p *FooError) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.ErrorMsg = v
	}
	return nil
}

func (p *FooError) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "foo_error"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *FooError) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "error_code", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:error_code: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.ErrorCode)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.error_code (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:error_code: ", p), err)
	}
	return err
}

func (p *FooError) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "error_msg", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:error_msg: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.ErrorMsg)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.error_msg (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:error_msg: ", p), err)
	}
	return err
}

func (p *FooError) Equals(other *FooError) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.ErrorCode != other.ErrorCode {
		return false
	}
	if p.ErrorMsg != other.ErrorMsg {
		return false
	}
	return true
}

func (p *FooError) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FooError(%+v)", *p)
}

func (p *FooError) Error() string {
	return p.String()
}

func (FooError) TExceptionType() thrift.TExceptionType {
	return thrift.TExceptionTypeCompiled
}

var _ thrift.TException = (*FooError)(nil)

func (p *FooError) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.FooError",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*FooError)(nil)

func (p *FooError) Validate() error {
	return nil
}

// Attributes:
//   - Bar
type OstrDefault struct {
	Bar int32 `thrift:"bar,1" db:"bar" json:"bar"`
}

func NewOstrDefault() *OstrDefault {
	return &OstrDefault{}
}

func (p *OstrDefault) GetBar() int32 {
	return p.Bar
}

func (p *OstrDefault) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *OstrDefault) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Bar = v
	}
	return nil
}

func (p *OstrDefault) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "ostr_default"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *OstrDefault) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "bar", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:bar: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Bar)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.bar (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:bar: ", p), err)
	}
	return err
}

func (p *OstrDefault) Equals(other *OstrDefault) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Bar != other.Bar {
		return false
	}
	return true
}

func (p *OstrDefault) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OstrDefault(%+v)", *p)
}

func (p *OstrDefault) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.OstrDefault",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*OstrDefault)(nil)

func (p *OstrDefault) Validate() error {
	return nil
}

// Attributes:
//   - Bar
type OstrCustom struct {
	Bar int32 `thrift:"bar,1" db:"bar" json:"bar"`
}

func NewOstrCustom() *OstrCustom {
	return &OstrCustom{}
}

func (p *OstrCustom) GetBar() int32 {
	return p.Bar
}

func (p *OstrCustom) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *OstrCustom) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Bar = v
	}
	return nil
}

func (p *OstrCustom) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "ostr_custom"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *OstrCustom) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "bar", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:bar: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Bar)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.bar (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:bar: ", p), err)
	}
	return err
}

func (p *OstrCustom) Equals(other *OstrCustom) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Bar != other.Bar {
		return false
	}
	return true
}

func (p *OstrCustom) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OstrCustom(%+v)", *p)
}

func (p *OstrCustom) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.OstrCustom",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*OstrCustom)(nil)

func (p *OstrCustom) Validate() error {
	return nil
}

type FooService interface {
	Foo(ctx context.Context) (_err error)
}

type FooServiceClient struct {
	c    thrift.TClient
	meta thrift.ResponseMeta
}

func NewFooServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *FooServiceClient {
	return &FooServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewFooServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *FooServiceClient {
	return &FooServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewFooServiceClient(c thrift.TClient) *FooServiceClient {
	return &FooServiceClient{
		c: c,
	}
}

func (p *FooServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *FooServiceClient) LastResponseMeta_() thrift.ResponseMeta {
	return p.meta
}

func (p *FooServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
	p.meta = meta
}

func (p *FooServiceClient) Foo(ctx context.Context) (_err error) {
	var _args0 FooServiceFooArgs
	var _result2 FooServiceFooResult
	var _meta1 thrift.ResponseMeta
	_meta1, _err = p.Client_().Call(ctx, "foo", &_args0, &_result2)
	p.SetLastResponseMeta_(_meta1)
	if _err != nil {
		return
	}
	return nil
}

type FooServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      FooService
}

func (p *FooServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *FooServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *FooServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewFooServiceProcessor(handler FooService) *FooServiceProcessor {

	self3 := &FooServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self3.processorMap["foo"] = &fooServiceProcessorFoo{handler: handler}
	return self3
}

func (p *FooServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
	if err2 != nil {
		return false, thrift.WrapTException(err2)
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(ctx, thrift.STRUCT)
	iprot.ReadMessageEnd(ctx)
	x4 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
	x4.Write(ctx, oprot)
	oprot.WriteMessageEnd(ctx)
	oprot.Flush(ctx)
	return false, x4
}

type fooServiceProcessorFoo struct {
	handler FooService
}

func (p *fooServiceProcessorFoo) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err5 thrift.TException
	args := FooServiceFooArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "foo", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := FooServiceFooResult{}
	if err2 := p.handler.Foo(ctx); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc6 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing foo: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "foo", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err5 = thrift.WrapTException(err2)
		}
		if err2 := _exc6.Write(ctx, oprot); _write_err5 == nil && err2 != nil {
			_write_err5 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err5 == nil && err2 != nil {
			_write_err5 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err5 == nil && err2 != nil {
			_write_err5 = thrift.WrapTException(err2)
		}
		if _write_err5 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err5,
				EndpointError: err,
			}
		}
		return true, err
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "foo", thrift.REPLY, seqId); err2 != nil {
		_write_err5 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err5 == nil && err2 != nil {
		_write_err5 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err5 == nil && err2 != nil {
		_write_err5 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err5 == nil && err2 != nil {
		_write_err5 = thrift.WrapTException(err2)
	}
	if _write_err5 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err5,
			EndpointError: err,
		}
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

type FooServiceFooArgs struct {
}

func NewFooServiceFooArgs() *FooServiceFooArgs {
	return &FooServiceFooArgs{}
}

func (p *FooServiceFooArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *FooServiceFooArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "foo_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *FooServiceFooArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FooServiceFooArgs(%+v)", *p)
}

func (p *FooServiceFooArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.FooServiceFooArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*FooServiceFooArgs)(nil)

type FooServiceFooResult struct {
}

func NewFooServiceFooResult() *FooServiceFooResult {
	return &FooServiceFooResult{}
}

func (p *FooServiceFooResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *FooServiceFooResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "foo_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *FooServiceFooResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FooServiceFooResult(%+v)", *p)
}

func (p *FooServiceFooResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.FooServiceFooResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*FooServiceFooResult)(nil)

type DeprecateEverything interface {
	// Deprecated: This method has neither 'x' nor "y"
	Foo(ctx context.Context) (_err error)
	// Deprecated: Fails to deliver 中文 колбаса
	Bar(ctx context.Context) (_err error)
	// Deprecated: Need this to work with tabs (	) or Umlauts (äöüÄÖÜß) too
	Baz(ctx context.Context) (_err error)
	// Deprecated: (no reason given)
	Deprecated(ctx context.Context) (_err error)
}

type DeprecateEverythingClient struct {
	c    thrift.TClient
	meta thrift.ResponseMeta
}

func NewDeprecateEverythingClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *DeprecateEverythingClient {
	return &DeprecateEverythingClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewDeprecateEverythingClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *DeprecateEverythingClient {
	return &DeprecateEverythingClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewDeprecateEverythingClient(c thrift.TClient) *DeprecateEverythingClient {
	return &DeprecateEverythingClient{
		c: c,
	}
}

func (p *DeprecateEverythingClient) Client_() thrift.TClient {
	return p.c
}

func (p *DeprecateEverythingClient) LastResponseMeta_() thrift.ResponseMeta {
	return p.meta
}

func (p *DeprecateEverythingClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
	p.meta = meta
}

// Deprecated: This method has neither 'x' nor "y"
func (p *DeprecateEverythingClient) Foo(ctx context.Context) (_err error) {
	var _args7 DeprecateEverythingFooArgs
	var _result9 DeprecateEverythingFooResult
	var _meta8 thrift.ResponseMeta
	_meta8, _err = p.Client_().Call(ctx, "Foo", &_args7, &_result9)
	p.SetLastResponseMeta_(_meta8)
	if _err != nil {
		return
	}
	return nil
}

// Deprecated: Fails to deliver 中文 колбаса
func (p *DeprecateEverythingClient) Bar(ctx context.Context) (_err error) {
	var _args10 DeprecateEverythingBarArgs
	var _result12 DeprecateEverythingBarResult
	var _meta11 thrift.ResponseMeta
	_meta11, _err = p.Client_().Call(ctx, "Bar", &_args10, &_result12)
	p.SetLastResponseMeta_(_meta11)
	if _err != nil {
		return
	}
	return nil
}

// Deprecated: Need this to work with tabs (	) or Umlauts (äöüÄÖÜß) too
func (p *DeprecateEverythingClient) Baz(ctx context.Context) (_err error) {
	var _args13 DeprecateEverythingBazArgs
	var _result15 DeprecateEverythingBazResult
	var _meta14 thrift.ResponseMeta
	_meta14, _err = p.Client_().Call(ctx, "Baz", &_args13, &_result15)
	p.SetLastResponseMeta_(_meta14)
	if _err != nil {
		return
	}
	return nil
}

// Deprecated: (no reason given)
func (p *DeprecateEverythingClient) Deprecated(ctx context.Context) (_err error) {
	var _args16 DeprecateEverythingDeprecatedArgs
	var _result18 DeprecateEverythingDeprecatedResult
	var _meta17 thrift.ResponseMeta
	_meta17, _err = p.Client_().Call(ctx, "Deprecated", &_args16, &_result18)
	p.SetLastResponseMeta_(_meta17)
	if _err != nil {
		return
	}
	return nil
}

type DeprecateEverythingProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      DeprecateEverything
}

func (p *DeprecateEverythingProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *DeprecateEverythingProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *DeprecateEverythingProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewDeprecateEverythingProcessor(handler DeprecateEverything) *DeprecateEverythingProcessor {

	self19 := &DeprecateEverythingProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self19.processorMap["Foo"] = &deprecateEverythingProcessorFoo{handler: handler}
	self19.processorMap["Bar"] = &deprecateEverythingProcessorBar{handler: handler}
	self19.processorMap["Baz"] = &deprecateEverythingProcessorBaz{handler: handler}
	self19.processorMap["Deprecated"] = &deprecateEverythingProcessorDeprecated{handler: handler}
	return self19
}

func (p *DeprecateEverythingProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
	if err2 != nil {
		return false, thrift.WrapTException(err2)
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(ctx, thrift.STRUCT)
	iprot.ReadMessageEnd(ctx)
	x20 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
	x20.Write(ctx, oprot)
	oprot.WriteMessageEnd(ctx)
	oprot.Flush(ctx)
	return false, x20
}

type deprecateEverythingProcessorFoo struct {
	handler DeprecateEverything
}

func (p *deprecateEverythingProcessorFoo) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err21 thrift.TException
	args := DeprecateEverythingFooArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "Foo", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := DeprecateEverythingFooResult{}
	if err2 := p.handler.Foo(ctx); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc22 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing Foo: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "Foo", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err21 = thrift.WrapTException(err2)
		}
		if err2 := _exc22.Write(ctx, oprot); _write_err21 == nil && err2 != nil {
			_write_err21 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err21 == nil && err2 != nil {
			_write_err21 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err21 == nil && err2 != nil {
			_write_err21 = thrift.WrapTException(err2)
		}
		if _write_err21 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err21,
				EndpointError: err,
			}
		}
		return true, err
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "Foo", thrift.REPLY, seqId); err2 != nil {
		_write_err21 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err21 == nil && err2 != nil {
		_write_err21 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err21 == nil && err2 != nil {
		_write_err21 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err21 == nil && err2 != nil {
		_write_err21 = thrift.WrapTException(err2)
	}
	if _write_err21 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err21,
			EndpointError: err,
		}
	}
	return true, err
}

type deprecateEverythingProcessorBar struct {
	handler DeprecateEverything
}

func (p *deprecateEverythingProcessorBar) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err23 thrift.TException
	args := DeprecateEverythingBarArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "Bar", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := DeprecateEverythingBarResult{}
	if err2 := p.handler.Bar(ctx); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc24 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing Bar: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "Bar", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err23 = thrift.WrapTException(err2)
		}
		if err2 := _exc24.Write(ctx, oprot); _write_err23 == nil && err2 != nil {
			_write_err23 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err23 == nil && err2 != nil {
			_write_err23 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err23 == nil && err2 != nil {
			_write_err23 = thrift.WrapTException(err2)
		}
		if _write_err23 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err23,
				EndpointError: err,
			}
		}
		return true, err
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "Bar", thrift.REPLY, seqId); err2 != nil {
		_write_err23 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err23 == nil && err2 != nil {
		_write_err23 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err23 == nil && err2 != nil {
		_write_err23 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err23 == nil && err2 != nil {
		_write_err23 = thrift.WrapTException(err2)
	}
	if _write_err23 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err23,
			EndpointError: err,
		}
	}
	return true, err
}

type deprecateEverythingProcessorBaz struct {
	handler DeprecateEverything
}

func (p *deprecateEverythingProcessorBaz) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err25 thrift.TException
	args := DeprecateEverythingBazArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "Baz", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := DeprecateEverythingBazResult{}
	if err2 := p.handler.Baz(ctx); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc26 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing Baz: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "Baz", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err25 = thrift.WrapTException(err2)
		}
		if err2 := _exc26.Write(ctx, oprot); _write_err25 == nil && err2 != nil {
			_write_err25 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err25 == nil && err2 != nil {
			_write_err25 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err25 == nil && err2 != nil {
			_write_err25 = thrift.WrapTException(err2)
		}
		if _write_err25 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err25,
				EndpointError: err,
			}
		}
		return true, err
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "Baz", thrift.REPLY, seqId); err2 != nil {
		_write_err25 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err25 == nil && err2 != nil {
		_write_err25 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err25 == nil && err2 != nil {
		_write_err25 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err25 == nil && err2 != nil {
		_write_err25 = thrift.WrapTException(err2)
	}
	if _write_err25 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err25,
			EndpointError: err,
		}
	}
	return true, err
}

type deprecateEverythingProcessorDeprecated struct {
	handler DeprecateEverything
}

func (p *deprecateEverythingProcessorDeprecated) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err27 thrift.TException
	args := DeprecateEverythingDeprecatedArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "Deprecated", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := DeprecateEverythingDeprecatedResult{}
	if err2 := p.handler.Deprecated(ctx); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc28 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing Deprecated: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "Deprecated", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err27 = thrift.WrapTException(err2)
		}
		if err2 := _exc28.Write(ctx, oprot); _write_err27 == nil && err2 != nil {
			_write_err27 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err27 == nil && err2 != nil {
			_write_err27 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err27 == nil && err2 != nil {
			_write_err27 = thrift.WrapTException(err2)
		}
		if _write_err27 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err27,
				EndpointError: err,
			}
		}
		return true, err
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "Deprecated", thrift.REPLY, seqId); err2 != nil {
		_write_err27 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err27 == nil && err2 != nil {
		_write_err27 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err27 == nil && err2 != nil {
		_write_err27 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err27 == nil && err2 != nil {
		_write_err27 = thrift.WrapTException(err2)
	}
	if _write_err27 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err27,
			EndpointError: err,
		}
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

type DeprecateEverythingFooArgs struct {
}

func NewDeprecateEverythingFooArgs() *DeprecateEverythingFooArgs {
	return &DeprecateEverythingFooArgs{}
}

func (p *DeprecateEverythingFooArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DeprecateEverythingFooArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Foo_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DeprecateEverythingFooArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeprecateEverythingFooArgs(%+v)", *p)
}

func (p *DeprecateEverythingFooArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.DeprecateEverythingFooArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*DeprecateEverythingFooArgs)(nil)

type DeprecateEverythingFooResult struct {
}

func NewDeprecateEverythingFooResult() *DeprecateEverythingFooResult {
	return &DeprecateEverythingFooResult{}
}

func (p *DeprecateEverythingFooResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DeprecateEverythingFooResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Foo_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DeprecateEverythingFooResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeprecateEverythingFooResult(%+v)", *p)
}

func (p *DeprecateEverythingFooResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.DeprecateEverythingFooResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*DeprecateEverythingFooResult)(nil)

type DeprecateEverythingBarArgs struct {
}

func NewDeprecateEverythingBarArgs() *DeprecateEverythingBarArgs {
	return &DeprecateEverythingBarArgs{}
}

func (p *DeprecateEverythingBarArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DeprecateEverythingBarArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Bar_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DeprecateEverythingBarArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeprecateEverythingBarArgs(%+v)", *p)
}

func (p *DeprecateEverythingBarArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.DeprecateEverythingBarArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*DeprecateEverythingBarArgs)(nil)

type DeprecateEverythingBarResult struct {
}

func NewDeprecateEverythingBarResult() *DeprecateEverythingBarResult {
	return &DeprecateEverythingBarResult{}
}

func (p *DeprecateEverythingBarResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DeprecateEverythingBarResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Bar_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DeprecateEverythingBarResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeprecateEverythingBarResult(%+v)", *p)
}

func (p *DeprecateEverythingBarResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.DeprecateEverythingBarResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*DeprecateEverythingBarResult)(nil)

type DeprecateEverythingBazArgs struct {
}

func NewDeprecateEverythingBazArgs() *DeprecateEverythingBazArgs {
	return &DeprecateEverythingBazArgs{}
}

func (p *DeprecateEverythingBazArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DeprecateEverythingBazArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Baz_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DeprecateEverythingBazArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeprecateEverythingBazArgs(%+v)", *p)
}

func (p *DeprecateEverythingBazArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.DeprecateEverythingBazArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*DeprecateEverythingBazArgs)(nil)

type DeprecateEverythingBazResult struct {
}

func NewDeprecateEverythingBazResult() *DeprecateEverythingBazResult {
	return &DeprecateEverythingBazResult{}
}

func (p *DeprecateEverythingBazResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DeprecateEverythingBazResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Baz_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DeprecateEverythingBazResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeprecateEverythingBazResult(%+v)", *p)
}

func (p *DeprecateEverythingBazResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.DeprecateEverythingBazResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*DeprecateEverythingBazResult)(nil)

type DeprecateEverythingDeprecatedArgs struct {
}

func NewDeprecateEverythingDeprecatedArgs() *DeprecateEverythingDeprecatedArgs {
	return &DeprecateEverythingDeprecatedArgs{}
}

func (p *DeprecateEverythingDeprecatedArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DeprecateEverythingDeprecatedArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Deprecated_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DeprecateEverythingDeprecatedArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeprecateEverythingDeprecatedArgs(%+v)", *p)
}

func (p *DeprecateEverythingDeprecatedArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.DeprecateEverythingDeprecatedArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*DeprecateEverythingDeprecatedArgs)(nil)

type DeprecateEverythingDeprecatedResult struct {
}

func NewDeprecateEverythingDeprecatedResult() *DeprecateEverythingDeprecatedResult {
	return &DeprecateEverythingDeprecatedResult{}
}

func (p *DeprecateEverythingDeprecatedResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DeprecateEverythingDeprecatedResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	ctx, err := thrift.CheckRecursionDepth(ctx)
	if err != nil {
		return err
	}
	defer thrift.DecrementRecursionDepth(ctx)
	if err := oprot.WriteStructBegin(ctx, "Deprecated_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DeprecateEverythingDeprecatedResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeprecateEverythingDeprecatedResult(%+v)", *p)
}

func (p *DeprecateEverythingDeprecatedResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*annotationtest.DeprecateEverythingDeprecatedResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*DeprecateEverythingDeprecatedResult)(nil)
